import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson06 = SentenceLessonDefinition(
  id: 'sentence_lesson_06',
  number: 6,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl6.title',
  subtitleKey: 'sl6.subtitle',
  descriptionKey: 'sl6.description',
  estimatedTime: '25–30 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl6.pattern.1',
    'sl6.pattern.2',
    'sl6.pattern.3',
    'sl6.pattern.4',
  ],
  storyFactory: getSentenceLesson06,
);

StoryData getSentenceLesson06() => dialogue()
    .story(6, tr('sl6.title'), tr('sl6.subtitle'))
    .description(tr('sl6.description'))
    .estimatedTime('25–30 min')
    .jlptFocus('N5')
    .scene('sl6_park', 'sl6_park')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .park('afternoon')
    .titleCard(tr('sl6.title'), tr('sl6.subtitle'), 2500)
    .n(tr('sl6.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl6.t_intro'), 'happy')
    .tanaka(tr('sl6.s1_intro'), 'speaking')
    .hide('tanaka')
    .show('ken', 'left', 'happy')
    .ken(tr('sl6.s1_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('sl6.s1_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl6.s1_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl6.s1_break'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl6.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl6.s1_a1'), 'speaking')
    .tanaka(tr('sl6.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl6.c1_natural'), 'sl6_p1_natural')
    .choice(tr('sl6.c1_formal'), 'sl6_p1_formal')
    .choice(tr('sl6.c1_mistake'), 'sl6_p1_mistake')
    .choice(tr('sl6.c1_own'), 'sl6_p1_own')
    .choice(tr('sl6.c1_min'), 'sl6_p1_min')
    .endMenu()
    .scene('sl6_p1_natural', 'sl6_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl6.p1_nat_yuki'), 'happy')
    .jump('sl6_after_p1')
    .scene('sl6_p1_formal', 'sl6_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl6.p1_form_ken'), 'laugh')
    .jump('sl6_after_p1')
    .scene('sl6_p1_mistake', 'sl6_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl6.p1_mis_tanaka'), 'neutral')
    .jump('sl6_p1_mistake2')
    .scene('sl6_p1_mistake2', 'sl6_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl6.p1_mis_relief'), 'happy')
    .jump('sl6_after_p1')
    .scene('sl6_p1_own', 'sl6_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl6.p1_own_yuki'), 'happy')
    .jump('sl6_after_p1')
    .scene('sl6_p1_min', 'sl6_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl6.p1_min_mei'), 'happy')
    .jump('sl6_after_p1')
    .scene('sl6_after_p1', 'sl6_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl6.s2_intro'), 'speaking')
    .tanaka(tr('sl6.s2_ex'), 'speaking')
    .tanaka(tr('sl6.s2_time'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl6.s2_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl6.s2_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl6.s2_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl6.s2_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl6.s2_ask'), 'neutral')
    .tanaka(tr('sl6.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl6.c2_natural'), 'sl6_p2_natural')
    .choice(tr('sl6.c2_formal'), 'sl6_p2_formal')
    .choice(tr('sl6.c2_mistake'), 'sl6_p2_mistake')
    .choice(tr('sl6.c2_own'), 'sl6_p2_own')
    .choice(tr('sl6.c2_min'), 'sl6_p2_min')
    .endMenu()
    .scene('sl6_p2_natural', 'sl6_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl6.p2_nat_mei'), 'happy')
    .jump('sl6_cafe')
    .scene('sl6_p2_formal', 'sl6_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl6.p2_form_ken'), 'laugh')
    .jump('sl6_cafe')
    .scene('sl6_p2_mistake', 'sl6_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c2_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl6.p2_mis_yuki'), 'neutral')
    .jump('sl6_p2_mistake2')
    .scene('sl6_p2_mistake2', 'sl6_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.p2_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl6.p2_mis_relief'), 'happy')
    .jump('sl6_cafe')
    .scene('sl6_p2_own', 'sl6_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl6.p2_own_mei'), 'happy')
    .jump('sl6_cafe')
    .scene('sl6_p2_min', 'sl6_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl6.p2_min_tanaka'), 'happy')
    .jump('sl6_cafe')
    .scene('sl6_cafe', 'sl6_cafe')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('afternoon')
    .n(tr('sl6.cafe'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl6.s3_intro'), 'speaking')
    .tanaka(tr('sl6.s3_ex'), 'speaking')
    .tanaka(tr('sl6.s3_means'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl6.s3_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl6.s3_a'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl6.ask_where'), 'neutral')
    .tanaka(tr('sl6.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl6.c3_natural'), 'sl6_p3_natural')
    .choice(tr('sl6.c3_formal'), 'sl6_p3_formal')
    .choice(tr('sl6.c3_mistake'), 'sl6_p3_mistake')
    .choice(tr('sl6.c3_own'), 'sl6_p3_own')
    .choice(tr('sl6.c3_min'), 'sl6_p3_min')
    .endMenu()
    .scene('sl6_p3_natural', 'sl6_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c3_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl6.p3_nat_ken'), 'happy')
    .jump('sl6_after_p3')
    .scene('sl6_p3_formal', 'sl6_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl6.p3_form_mei'), 'laugh')
    .jump('sl6_after_p3')
    .scene('sl6_p3_mistake', 'sl6_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl6.p3_mis_tanaka'), 'neutral')
    .jump('sl6_p3_mistake2')
    .scene('sl6_p3_mistake2', 'sl6_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl6.p3_mis_relief'), 'happy')
    .jump('sl6_after_p3')
    .scene('sl6_p3_own', 'sl6_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl6.p3_own_ken'), 'happy')
    .jump('sl6_after_p3')
    .scene('sl6_p3_min', 'sl6_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl6.p3_min_yuki'), 'gentle')
    .jump('sl6_after_p3')
    .scene('sl6_after_p3', 'sl6_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl6.s4_intro'), 'speaking')
    .tanaka(tr('sl6.s4_ex'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl6.s4_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl6.s4_a'), 'speaking')
    .tanaka(tr('sl6.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl6.c4_natural'), 'sl6_p4_natural')
    .choice(tr('sl6.c4_formal'), 'sl6_p4_formal')
    .choice(tr('sl6.c4_mistake'), 'sl6_p4_mistake')
    .choice(tr('sl6.c4_own'), 'sl6_p4_own')
    .choice(tr('sl6.c4_min'), 'sl6_p4_min')
    .endMenu()
    .scene('sl6_p4_natural', 'sl6_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl6.p4_nat_tanaka'), 'happy')
    .jump('sl6_talk')
    .scene('sl6_p4_formal', 'sl6_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c4_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl6.p4_form_yuki'), 'laugh')
    .jump('sl6_talk')
    .scene('sl6_p4_mistake', 'sl6_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c4_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl6.p4_mis_ken'), 'neutral')
    .jump('sl6_p4_mistake2')
    .scene('sl6_p4_mistake2', 'sl6_p4_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.p4_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl6.p4_mis_relief'), 'happy')
    .jump('sl6_talk')
    .scene('sl6_p4_own', 'sl6_p4_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c4_own'), 'happy')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl6.p4_own_ken'), 'laugh')
    .jump('sl6_talk')
    .scene('sl6_p4_min', 'sl6_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl6.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl6.p4_min_mei'), 'happy')
    .jump('sl6_talk')
    .scene('sl6_talk', 'sl6_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl6.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl6.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl6.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl6.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl6.talk_tanaka'), 'happy')
    .player(tr('sl6.talk_player'), 'neutral')
    .tanaka(tr('sl6.talk_close'), 'happy')
    .n(tr('sl6.complete'))
    .end()
    .build();
