import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson15 = SentenceLessonDefinition(
  id: 'sentence_lesson_15',
  number: 15,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl15.title',
  subtitleKey: 'sl15.subtitle',
  descriptionKey: 'sl15.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl15.pattern.1',
    'sl15.pattern.2',
    'sl15.pattern.3',
    'sl15.pattern.4',
  ],
  storyFactory: getSentenceLesson15,
);

StoryData getSentenceLesson15() => dialogue()
    .story(15, tr('sl15.title'), tr('sl15.subtitle'))
    .description(tr('sl15.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl15_party', 'sl15_party')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('evening')
    .titleCard(tr('sl15.title'), tr('sl15.subtitle'), 2500)
    .n(tr('sl15.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.t_intro'), 'happy')
    .tanaka(tr('sl15.s1_intro'), 'speaking')
    .tanaka(tr('sl15.s1_ex'), 'speaking')
    .tanaka(tr('sl15.s1_koto'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl15.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl15.s1_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl15.s1_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl15.s1_a2'), 'speaking')
    .tanaka(tr('sl15.tanaka_ask'), 'neutral')
    .tanaka(tr('sl15.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl15.c1_natural'), 'sl15_p1_natural')
    .choice(tr('sl15.c1_formal'), 'sl15_p1_formal')
    .choice(tr('sl15.c1_mistake'), 'sl15_p1_mistake')
    .choice(tr('sl15.c1_own'), 'sl15_p1_own')
    .choice(tr('sl15.c1_min'), 'sl15_p1_min')
    .endMenu()
    .scene('sl15_p1_natural', 'sl15_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p1_nat_tanaka'), 'happy')
    .jump('sl15_after_p1')
    .scene('sl15_p1_formal', 'sl15_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl15.p1_form_ken'), 'laugh')
    .jump('sl15_after_p1')
    .scene('sl15_p1_mistake', 'sl15_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl15.p1_mis_tanaka'), 'neutral')
    .jump('sl15_p1_mistake2')
    .scene('sl15_p1_mistake2', 'sl15_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p1_mis_relief'), 'happy')
    .jump('sl15_after_p1')
    .scene('sl15_p1_own', 'sl15_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p1_own_tanaka'), 'happy')
    .jump('sl15_after_p1')
    .scene('sl15_p1_min', 'sl15_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl15.p1_min_mei'), 'happy')
    .jump('sl15_after_p1')
    .scene('sl15_after_p1', 'sl15_after_p1')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl15.s2_intro'), 'speaking')
    .tanaka(tr('sl15.s2_neg'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl15.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl15.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl15.s2_q2'), 'neutral')
    .tanaka(tr('sl15.s2_a2'), 'speaking')
    .mei(tr('sl15.m_ask'), 'neutral')
    .tanaka(tr('sl15.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl15.c2_natural'), 'sl15_p2_natural')
    .choice(tr('sl15.c2_formal'), 'sl15_p2_formal')
    .choice(tr('sl15.c2_mistake'), 'sl15_p2_mistake')
    .choice(tr('sl15.c2_own'), 'sl15_p2_own')
    .choice(tr('sl15.c2_min'), 'sl15_p2_min')
    .endMenu()
    .scene('sl15_p2_natural', 'sl15_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl15.p2_nat_mei'), 'happy')
    .jump('sl15_after_p2')
    .scene('sl15_p2_formal', 'sl15_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl15.p2_form_yuki'), 'laugh')
    .jump('sl15_after_p2')
    .scene('sl15_p2_mistake', 'sl15_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl15.p2_mis_tanaka'), 'neutral')
    .jump('sl15_p2_mistake2')
    .scene('sl15_p2_mistake2', 'sl15_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p2_mis_relief'), 'happy')
    .jump('sl15_after_p2')
    .scene('sl15_p2_own', 'sl15_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl15.p2_own_mei'), 'happy')
    .jump('sl15_after_p2')
    .scene('sl15_p2_min', 'sl15_p2_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c2_min'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl15.p2_min_ken'), 'neutral')
    .jump('sl15_after_p2')
    .scene('sl15_after_p2', 'sl15_after_p2')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl15.s3_intro'), 'speaking')
    .tanaka(tr('sl15.s3_ex'), 'speaking')
    .tanaka(tr('sl15.s3_first'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl15.s3_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl15.s3_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl15.s3_q2'), 'neutral')
    .tanaka(tr('sl15.s3_a2'), 'speaking')
    .yuki(tr('sl15.y_ask'), 'neutral')
    .tanaka(tr('sl15.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl15.c3_natural'), 'sl15_p3_natural')
    .choice(tr('sl15.c3_formal'), 'sl15_p3_formal')
    .choice(tr('sl15.c3_mistake'), 'sl15_p3_mistake')
    .choice(tr('sl15.c3_own'), 'sl15_p3_own')
    .choice(tr('sl15.c3_min'), 'sl15_p3_min')
    .endMenu()
    .scene('sl15_p3_natural', 'sl15_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl15.p3_nat_yuki'), 'happy')
    .jump('sl15_after_p3')
    .scene('sl15_p3_formal', 'sl15_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl15.p3_form_ken'), 'laugh')
    .jump('sl15_after_p3')
    .scene('sl15_p3_mistake', 'sl15_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl15.p3_mis_tanaka'), 'neutral')
    .jump('sl15_p3_mistake2')
    .scene('sl15_p3_mistake2', 'sl15_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p3_mis_relief'), 'happy')
    .jump('sl15_after_p3')
    .scene('sl15_p3_own', 'sl15_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl15.p3_own_yuki'), 'happy')
    .jump('sl15_after_p3')
    .scene('sl15_p3_min', 'sl15_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl15.p3_min_mei'), 'happy')
    .jump('sl15_after_p3')
    .scene('sl15_after_p3', 'sl15_after_p3')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl15.s4_intro'), 'speaking')
    .tanaka(tr('sl15.s4_ex'), 'speaking')
    .tanaka(tr('sl15.s4_form'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl15.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl15.s4_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl15.s4_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl15.s4_a2'), 'speaking')
    .tanaka(tr('sl15.tanaka_holiday'), 'happy')
    .tanaka(tr('sl15.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl15.c4_natural'), 'sl15_p4_natural')
    .choice(tr('sl15.c4_formal'), 'sl15_p4_formal')
    .choice(tr('sl15.c4_mistake'), 'sl15_p4_mistake')
    .choice(tr('sl15.c4_own'), 'sl15_p4_own')
    .choice(tr('sl15.c4_min'), 'sl15_p4_min')
    .endMenu()
    .scene('sl15_p4_natural', 'sl15_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p4_nat_tanaka'), 'happy')
    .jump('sl15_talk')
    .scene('sl15_p4_formal', 'sl15_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl15.p4_form_mei'), 'laugh')
    .jump('sl15_talk')
    .scene('sl15_p4_mistake', 'sl15_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl15.p4_mis_tanaka'), 'neutral')
    .jump('sl15_p4_mistake2')
    .scene('sl15_p4_mistake2', 'sl15_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p4_mis_relief'), 'happy')
    .jump('sl15_talk')
    .scene('sl15_p4_own', 'sl15_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.p4_own_tanaka'), 'happy')
    .jump('sl15_talk')
    .scene('sl15_p4_min', 'sl15_p4_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl15.c4_min'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl15.p4_min_ken'), 'neutral')
    .jump('sl15_talk')
    .scene('sl15_talk', 'sl15_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl15.talk_mei'), 'happy')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl15.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl15.talk_yuki'), 'happy')
    .hide('yuki')
    .mei(tr('sl15.mei_thanks'), 'happy')
    .hide('mei')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl15.talk_tanaka'), 'happy')
    .player(tr('sl15.talk_player'), 'neutral')
    .tanaka(tr('sl15.talk_close'), 'happy')
    .n(tr('sl15.complete'))
    .end()
    .build();
