import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson17 = SentenceLessonDefinition(
  id: 'sentence_lesson_17',
  number: 17,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl17.title',
  subtitleKey: 'sl17.subtitle',
  descriptionKey: 'sl17.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl17.pattern.1',
    'sl17.pattern.2',
    'sl17.pattern.3',
    'sl17.pattern.4',
  ],
  storyFactory: getSentenceLesson17,
);

StoryData getSentenceLesson17() => dialogue()
    .story(17, tr('sl17.title'), tr('sl17.subtitle'))
    .description(tr('sl17.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl17_street', 'sl17_street')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .street('afternoon')
    .titleCard(tr('sl17.title'), tr('sl17.subtitle'), 2500)
    .n(tr('sl17.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl17.t_intro'), 'happy')
    .tanaka(tr('sl17.s1_intro'), 'speaking')
    .tanaka(tr('sl17.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl17.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl17.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl17.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl17.s1_a2'), 'speaking')
    .tanaka(tr('sl17.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl17.c1_natural'), 'sl17_p1_natural')
    .choice(tr('sl17.c1_formal'), 'sl17_p1_formal')
    .choice(tr('sl17.c1_mistake'), 'sl17_p1_mistake')
    .choice(tr('sl17.c1_own'), 'sl17_p1_own')
    .choice(tr('sl17.c1_min'), 'sl17_p1_min')
    .endMenu()
    .scene('sl17_p1_natural', 'sl17_p1_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c1_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl17.p1_nat_ken'), 'happy')
    .jump('sl17_after_p1')
    .scene('sl17_p1_formal', 'sl17_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl17.p1_form_mei'), 'laugh')
    .jump('sl17_after_p1')
    .scene('sl17_p1_mistake', 'sl17_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl17.p1_mis_tanaka'), 'neutral')
    .jump('sl17_p1_mistake2')
    .scene('sl17_p1_mistake2', 'sl17_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl17.p1_mis_relief'), 'happy')
    .jump('sl17_after_p1')
    .scene('sl17_p1_own', 'sl17_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl17.p1_own_ken'), 'happy')
    .jump('sl17_after_p1')
    .scene('sl17_p1_min', 'sl17_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl17.p1_min_yuki'), 'gentle')
    .jump('sl17_after_p1')
    .scene('sl17_after_p1', 'sl17_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl17.y_ninki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl17.s2_intro'), 'speaking')
    .tanaka(tr('sl17.s2_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl17.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl17.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl17.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl17.s2_a2'), 'speaking')
    .tanaka(tr('sl17.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl17.c2_natural'), 'sl17_p2_natural')
    .choice(tr('sl17.c2_formal'), 'sl17_p2_formal')
    .choice(tr('sl17.c2_mistake'), 'sl17_p2_mistake')
    .choice(tr('sl17.c2_own'), 'sl17_p2_own')
    .choice(tr('sl17.c2_min'), 'sl17_p2_min')
    .endMenu()
    .scene('sl17_p2_natural', 'sl17_p2_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c2_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl17.p2_nat_ken'), 'happy')
    .jump('sl17_after_p2')
    .scene('sl17_p2_formal', 'sl17_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl17.p2_form_yuki'), 'laugh')
    .jump('sl17_after_p2')
    .scene('sl17_p2_mistake', 'sl17_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl17.p2_mis_tanaka'), 'neutral')
    .jump('sl17_p2_mistake2')
    .scene('sl17_p2_mistake2', 'sl17_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl17.p2_mis_relief'), 'happy')
    .jump('sl17_after_p2')
    .scene('sl17_p2_own', 'sl17_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl17.p2_own_ken'), 'happy')
    .jump('sl17_after_p2')
    .scene('sl17_p2_min', 'sl17_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl17.p2_min_mei'), 'happy')
    .jump('sl17_after_p2')
    .scene('sl17_after_p2', 'sl17_after_p2')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('afternoon')
    .n(tr('sl17.shutter'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl17.s3_intro'), 'speaking')
    .tanaka(tr('sl17.s3_form'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl17.s3_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl17.s3_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl17.s3_q2'), 'neutral')
    .tanaka(tr('sl17.s3_a2'), 'speaking')
    .ken(tr('sl17.k_ask'), 'neutral')
    .tanaka(tr('sl17.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl17.c3_natural'), 'sl17_p3_natural')
    .choice(tr('sl17.c3_formal'), 'sl17_p3_formal')
    .choice(tr('sl17.c3_mistake'), 'sl17_p3_mistake')
    .choice(tr('sl17.c3_own'), 'sl17_p3_own')
    .choice(tr('sl17.c3_min'), 'sl17_p3_min')
    .endMenu()
    .scene('sl17_p3_natural', 'sl17_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c3_natural'), 'happy')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl17.p3_nat_ken'), 'surprised')
    .jump('sl17_after_p3')
    .scene('sl17_p3_formal', 'sl17_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl17.p3_form_mei'), 'laugh')
    .jump('sl17_after_p3')
    .scene('sl17_p3_mistake', 'sl17_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl17.p3_mis_tanaka'), 'neutral')
    .jump('sl17_p3_mistake2')
    .scene('sl17_p3_mistake2', 'sl17_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl17.p3_mis_relief'), 'happy')
    .jump('sl17_after_p3')
    .scene('sl17_p3_own', 'sl17_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl17.p3_own_ken'), 'happy')
    .jump('sl17_after_p3')
    .scene('sl17_p3_min', 'sl17_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl17.p3_min_yuki'), 'gentle')
    .jump('sl17_after_p3')
    .scene('sl17_after_p3', 'sl17_after_p3')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl17.s4_intro'), 'speaking')
    .tanaka(tr('sl17.s4_ex'), 'speaking')
    .tanaka(tr('sl17.s4_form'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl17.s4_q1'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl17.s4_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl17.s4_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl17.s4_a2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl17.y_news'), 'neutral')
    .tanaka(tr('sl17.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl17.c4_natural'), 'sl17_p4_natural')
    .choice(tr('sl17.c4_formal'), 'sl17_p4_formal')
    .choice(tr('sl17.c4_mistake'), 'sl17_p4_mistake')
    .choice(tr('sl17.c4_own'), 'sl17_p4_own')
    .choice(tr('sl17.c4_min'), 'sl17_p4_min')
    .endMenu()
    .scene('sl17_p4_natural', 'sl17_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c4_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl17.p4_nat_yuki'), 'happy')
    .jump('sl17_talk')
    .scene('sl17_p4_formal', 'sl17_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl17.p4_form_ken'), 'laugh')
    .jump('sl17_talk')
    .scene('sl17_p4_mistake', 'sl17_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl17.p4_mis_tanaka'), 'neutral')
    .jump('sl17_p4_mistake2')
    .scene('sl17_p4_mistake2', 'sl17_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl17.p4_mis_relief'), 'happy')
    .jump('sl17_talk')
    .scene('sl17_p4_own', 'sl17_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c4_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl17.p4_own_yuki'), 'happy')
    .jump('sl17_talk')
    .scene('sl17_p4_min', 'sl17_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl17.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl17.p4_min_mei'), 'happy')
    .jump('sl17_talk')
    .scene('sl17_talk', 'sl17_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl17.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl17.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl17.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl17.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl17.talk_tanaka'), 'happy')
    .player(tr('sl17.talk_player'), 'neutral')
    .tanaka(tr('sl17.talk_close'), 'happy')
    .n(tr('sl17.complete'))
    .end()
    .build();
