import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson01 = SentenceLessonDefinition(
  id: 'sentence_lesson_01',
  number: 1,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl1.title',
  subtitleKey: 'sl1.subtitle',
  descriptionKey: 'sl1.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl1.pattern.1',
    'sl1.pattern.2',
    'sl1.pattern.3',
    'sl1.pattern.4',
  ],
  storyFactory: getSentenceLesson01,
);

StoryData getSentenceLesson01() => dialogue()
    .story(1, tr('sl1.title'), tr('sl1.subtitle'))
    .description(tr('sl1.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('sl1_class', 'sl1_class')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('morning')
    .titleCard(tr('sl1.title'), tr('sl1.subtitle'), 2500)
    .n(tr('sl1.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.t_intro'), 'happy')
    .tanaka(tr('sl1.s1_model'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('sl1.s1_ken'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl1.s1_mei'), 'happy')
    .hide('mei')
    .tanaka(tr('sl1.s1_break'), 'speaking')
    .ken(tr('sl1.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl1.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl1.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl1.s1_a2'), 'speaking')
    .tanaka(tr('sl1.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl1.c1_natural'), 'sl1_p1_natural')
    .choice(tr('sl1.c1_formal'), 'sl1_p1_formal')
    .choice(tr('sl1.c1_mistake'), 'sl1_p1_mistake')
    .choice(tr('sl1.c1_own'), 'sl1_p1_own')
    .choice(tr('sl1.c1_min'), 'sl1_p1_min')
    .endMenu()
    .scene('sl1_p1_natural', 'sl1_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c1_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl1.p1_nat_mei'), 'happy')
    .jump('sl1_after_p1')
    .scene('sl1_p1_formal', 'sl1_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl1.p1_form_ken'), 'laugh')
    .jump('sl1_after_p1')
    .scene('sl1_p1_mistake', 'sl1_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl1.p1_mis_tanaka'), 'neutral')
    .jump('sl1_p1_mistake2')
    .scene('sl1_p1_mistake2', 'sl1_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.p1_mis_relief'), 'happy')
    .jump('sl1_after_p1')
    .scene('sl1_p1_own', 'sl1_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl1.p1_own_ken'), 'happy')
    .jump('sl1_after_p1')
    .scene('sl1_p1_min', 'sl1_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl1.p1_min_yuki'), 'gentle')
    .jump('sl1_after_p1')
    .scene('sl1_after_p1', 'sl1_after_p1')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl1.s2_intro'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl1.s2_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl1.s2_q'), 'neutral')
    .tanaka(tr('sl1.s2_a'), 'speaking')
    .yuki(tr('sl1.s2_joke'), 'playful')
    .tanaka(tr('sl1.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl1.c2_natural'), 'sl1_p2_natural')
    .choice(tr('sl1.c2_formal'), 'sl1_p2_formal')
    .choice(tr('sl1.c2_mistake'), 'sl1_p2_mistake')
    .choice(tr('sl1.c2_own'), 'sl1_p2_own')
    .choice(tr('sl1.c2_min'), 'sl1_p2_min')
    .endMenu()
    .scene('sl1_p2_natural', 'sl1_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl1.p2_nat_yuki'), 'laugh')
    .jump('sl1_after_p2')
    .scene('sl1_p2_formal', 'sl1_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl1.p2_form_mei'), 'laugh')
    .jump('sl1_after_p2')
    .scene('sl1_p2_mistake', 'sl1_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c2_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl1.p2_mis_ken'), 'surprised')
    .jump('sl1_p2_mistake2')
    .scene('sl1_p2_mistake2', 'sl1_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl1.p2_mis_relief'), 'happy')
    .jump('sl1_after_p2')
    .scene('sl1_p2_own', 'sl1_p2_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c2_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.p2_own_tanaka'), 'happy')
    .jump('sl1_after_p2')
    .scene('sl1_p2_min', 'sl1_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl1.p2_min_mei'), 'happy')
    .jump('sl1_after_p2')
    .scene('sl1_after_p2', 'sl1_after_p2')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl1.s3_intro'), 'speaking')
    .hide('tanaka')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl1.s3_mei'), 'neutral')
    .hide('mei')
    .show('ken', 'left', 'happy')
    .ken(tr('sl1.s3_ken'), 'happy')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl1.s3_yuki'), 'neutral')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl1.s3_tanaka'), 'speaking')
    .ken(tr('sl1.s3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl1.s3_a'), 'speaking')
    .tanaka(tr('sl1.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl1.c3_natural'), 'sl1_p3_natural')
    .choice(tr('sl1.c3_formal'), 'sl1_p3_formal')
    .choice(tr('sl1.c3_mistake'), 'sl1_p3_mistake')
    .choice(tr('sl1.c3_own'), 'sl1_p3_own')
    .choice(tr('sl1.c3_min'), 'sl1_p3_min')
    .endMenu()
    .scene('sl1_p3_natural', 'sl1_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl1.p3_nat_yuki'), 'happy')
    .jump('sl1_after_p3')
    .scene('sl1_p3_formal', 'sl1_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl1.p3_form_ken'), 'laugh')
    .jump('sl1_after_p3')
    .scene('sl1_p3_mistake', 'sl1_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c3_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl1.p3_mis_mei'), 'surprised')
    .jump('sl1_p3_mistake2')
    .scene('sl1_p3_mistake2', 'sl1_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.p3_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl1.p3_mis_relief'), 'happy')
    .jump('sl1_after_p3')
    .scene('sl1_p3_own', 'sl1_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl1.p3_own_yuki'), 'happy')
    .jump('sl1_after_p3')
    .scene('sl1_p3_min', 'sl1_p3_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c3_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.p3_min_tanaka'), 'happy')
    .jump('sl1_after_p3')
    .scene('sl1_after_p3', 'sl1_after_p3')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl1.s4_intro'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl1.s4_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl1.s4_a'), 'speaking')
    .tanaka(tr('sl1.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl1.c4_natural'), 'sl1_p4_natural')
    .choice(tr('sl1.c4_formal'), 'sl1_p4_formal')
    .choice(tr('sl1.c4_mistake'), 'sl1_p4_mistake')
    .choice(tr('sl1.c4_own'), 'sl1_p4_own')
    .choice(tr('sl1.c4_min'), 'sl1_p4_min')
    .endMenu()
    .scene('sl1_p4_natural', 'sl1_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.p4_nat_tanaka'), 'happy')
    .jump('sl1_talk')
    .scene('sl1_p4_formal', 'sl1_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c4_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl1.p4_form_yuki'), 'laugh')
    .jump('sl1_talk')
    .scene('sl1_p4_mistake', 'sl1_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c4_mistake'), 'concerned')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl1.p4_mis_ken'), 'laugh')
    .jump('sl1_p4_mistake2')
    .scene('sl1_p4_mistake2', 'sl1_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.p4_mis_relief'), 'happy')
    .jump('sl1_talk')
    .scene('sl1_p4_own', 'sl1_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c4_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl1.p4_own_mei'), 'happy')
    .jump('sl1_talk')
    .scene('sl1_p4_min', 'sl1_p4_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl1.c4_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.p4_min_tanaka'), 'happy')
    .jump('sl1_talk')
    .scene('sl1_talk', 'sl1_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl1.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl1.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl1.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl1.talk_tanaka'), 'happy')
    .player(tr('sl1.talk_player'), 'neutral')
    .tanaka(tr('sl1.talk_close'), 'happy')
    .n(tr('sl1.complete'))
    .end()
    .build();
