import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson09 = SentenceLessonDefinition(
  id: 'sentence_lesson_09',
  number: 9,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl9.title',
  subtitleKey: 'sl9.subtitle',
  descriptionKey: 'sl9.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl9.pattern.1',
    'sl9.pattern.2',
    'sl9.pattern.3',
    'sl9.pattern.4',
  ],
  storyFactory: getSentenceLesson09,
);

StoryData getSentenceLesson09() => dialogue()
    .story(9, tr('sl9.title'), tr('sl9.subtitle'))
    .description(tr('sl9.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5')
    .scene('sl9_cafe', 'sl9_cafe')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('afternoon')
    .titleCard(tr('sl9.title'), tr('sl9.subtitle'), 2500)
    .n(tr('sl9.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl9.t_intro'), 'happy')
    .tanaka(tr('sl9.s1_intro'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl9.s1_yuki'), 'happy')
    .hide('yuki')
    .show('ken', 'left', 'happy')
    .ken(tr('sl9.s1_ken'), 'happy')
    .tanaka(tr('sl9.s1_break'), 'speaking')
    .ken(tr('sl9.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl9.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl9.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl9.s1_a1b'), 'speaking')
    .tanaka(tr('sl9.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl9.c1_natural'), 'sl9_p1_natural')
    .choice(tr('sl9.c1_formal'), 'sl9_p1_formal')
    .choice(tr('sl9.c1_mistake'), 'sl9_p1_mistake')
    .choice(tr('sl9.c1_own'), 'sl9_p1_own')
    .choice(tr('sl9.c1_min'), 'sl9_p1_min')
    .endMenu()
    .scene('sl9_p1_natural', 'sl9_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl9.p1_nat_yuki'), 'happy')
    .jump('sl9_after_p1')
    .scene('sl9_p1_formal', 'sl9_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl9.p1_form_ken'), 'laugh')
    .jump('sl9_after_p1')
    .scene('sl9_p1_mistake', 'sl9_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl9.p1_mis_tanaka'), 'neutral')
    .jump('sl9_p1_mistake2')
    .scene('sl9_p1_mistake2', 'sl9_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl9.p1_mis_relief'), 'happy')
    .jump('sl9_after_p1')
    .scene('sl9_p1_own', 'sl9_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl9.p1_own_yuki'), 'happy')
    .jump('sl9_after_p1')
    .scene('sl9_p1_min', 'sl9_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl9.p1_min_mei'), 'happy')
    .jump('sl9_after_p1')
    .scene('sl9_after_p1', 'sl9_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl9.s2_intro'), 'speaking')
    .tanaka(tr('sl9.s2_ex'), 'speaking')
    .tanaka(tr('sl9.s2_neg'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl9.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl9.s2_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl9.s2_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl9.s2_a2'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('sl9.s2_mei'), 'happy')
    .tanaka(tr('sl9.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl9.c2_natural'), 'sl9_p2_natural')
    .choice(tr('sl9.c2_formal'), 'sl9_p2_formal')
    .choice(tr('sl9.c2_mistake'), 'sl9_p2_mistake')
    .choice(tr('sl9.c2_own'), 'sl9_p2_own')
    .choice(tr('sl9.c2_min'), 'sl9_p2_min')
    .endMenu()
    .scene('sl9_p2_natural', 'sl9_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl9.p2_nat_mei'), 'happy')
    .jump('sl9_after_p2')
    .scene('sl9_p2_formal', 'sl9_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl9.p2_form_yuki'), 'laugh')
    .jump('sl9_after_p2')
    .scene('sl9_p2_mistake', 'sl9_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c2_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl9.p2_mis_ken'), 'neutral')
    .jump('sl9_p2_mistake2')
    .scene('sl9_p2_mistake2', 'sl9_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl9.p2_mis_relief'), 'happy')
    .jump('sl9_after_p2')
    .scene('sl9_p2_own', 'sl9_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl9.p2_own_mei'), 'happy')
    .jump('sl9_after_p2')
    .scene('sl9_p2_min', 'sl9_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl9.p2_min_tanaka'), 'happy')
    .jump('sl9_after_p2')
    .scene('sl9_after_p2', 'sl9_after_p2')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl9.s3_intro'), 'speaking')
    .tanaka(tr('sl9.s3_ex'), 'speaking')
    .tanaka(tr('sl9.s3_na'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl9.s3_q1'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl9.s3_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl9.s3_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl9.s3_a2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl9.s3_natto'), 'neutral')
    .tanaka(tr('sl9.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl9.c3_natural'), 'sl9_p3_natural')
    .choice(tr('sl9.c3_formal'), 'sl9_p3_formal')
    .choice(tr('sl9.c3_mistake'), 'sl9_p3_mistake')
    .choice(tr('sl9.c3_own'), 'sl9_p3_own')
    .choice(tr('sl9.c3_min'), 'sl9_p3_min')
    .endMenu()
    .scene('sl9_p3_natural', 'sl9_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl9.p3_nat_yuki'), 'happy')
    .jump('sl9_after_p3')
    .scene('sl9_p3_formal', 'sl9_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl9.p3_form_mei'), 'laugh')
    .jump('sl9_after_p3')
    .scene('sl9_p3_mistake', 'sl9_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c3_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl9.p3_mis_ken'), 'neutral')
    .jump('sl9_p3_mistake2')
    .scene('sl9_p3_mistake2', 'sl9_p3_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.p3_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl9.p3_mis_relief'), 'happy')
    .jump('sl9_after_p3')
    .scene('sl9_p3_own', 'sl9_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl9.p3_own_yuki'), 'happy')
    .jump('sl9_after_p3')
    .scene('sl9_p3_min', 'sl9_p3_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c3_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl9.p3_min_tanaka'), 'happy')
    .jump('sl9_after_p3')
    .scene('sl9_after_p3', 'sl9_after_p3')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl9.s4_intro'), 'speaking')
    .tanaka(tr('sl9.s4_ex'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl9.s4_q1'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl9.s4_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl9.s4_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl9.s4_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl9.ask_like'), 'neutral')
    .tanaka(tr('sl9.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl9.c4_natural'), 'sl9_p4_natural')
    .choice(tr('sl9.c4_formal'), 'sl9_p4_formal')
    .choice(tr('sl9.c4_mistake'), 'sl9_p4_mistake')
    .choice(tr('sl9.c4_own'), 'sl9_p4_own')
    .choice(tr('sl9.c4_min'), 'sl9_p4_min')
    .endMenu()
    .scene('sl9_p4_natural', 'sl9_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c4_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl9.p4_nat_mei'), 'happy')
    .jump('sl9_talk')
    .scene('sl9_p4_formal', 'sl9_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl9.p4_form_ken'), 'laugh')
    .jump('sl9_talk')
    .scene('sl9_p4_mistake', 'sl9_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl9.p4_mis_tanaka'), 'neutral')
    .jump('sl9_p4_mistake2')
    .scene('sl9_p4_mistake2', 'sl9_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl9.p4_mis_relief'), 'happy')
    .jump('sl9_talk')
    .scene('sl9_p4_own', 'sl9_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c4_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl9.p4_own_mei'), 'happy')
    .jump('sl9_talk')
    .scene('sl9_p4_min', 'sl9_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl9.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl9.p4_min_yuki'), 'gentle')
    .jump('sl9_talk')
    .scene('sl9_talk', 'sl9_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl9.talk_open'), 'happy')
    .hide('tanaka')
    .show('ken', 'left', 'happy')
    .ken(tr('sl9.talk_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl9.talk_yuki'), 'happy')
    .hide('yuki')
    .show('mei', 'right', 'happy')
    .mei(tr('sl9.talk_mei'), 'happy')
    .hide('mei')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl9.talk_tanaka'), 'happy')
    .player(tr('sl9.talk_player'), 'neutral')
    .tanaka(tr('sl9.talk_close'), 'happy')
    .n(tr('sl9.complete'))
    .end()
    .build();
