import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson12 = SentenceLessonDefinition(
  id: 'sentence_lesson_12',
  number: 12,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl12.title',
  subtitleKey: 'sl12.subtitle',
  descriptionKey: 'sl12.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl12.pattern.1',
    'sl12.pattern.2',
    'sl12.pattern.3',
    'sl12.pattern.4',
  ],
  storyFactory: getSentenceLesson12,
);

StoryData getSentenceLesson12() => dialogue()
    .story(12, tr('sl12.title'), tr('sl12.subtitle'))
    .description(tr('sl12.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl12_temple', 'sl12_temple')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .park('afternoon')
    .titleCard(tr('sl12.title'), tr('sl12.subtitle'), 2500)
    .n(tr('sl12.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl12.t_intro'), 'happy')
    .tanaka(tr('sl12.s1_intro'), 'speaking')
    .tanaka(tr('sl12.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl12.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl12.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl12.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl12.s1_a2'), 'speaking')
    .n(tr('sl12.gate'))
    .tanaka(tr('sl12.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl12.c1_natural'), 'sl12_p1_natural')
    .choice(tr('sl12.c1_formal'), 'sl12_p1_formal')
    .choice(tr('sl12.c1_mistake'), 'sl12_p1_mistake')
    .choice(tr('sl12.c1_own'), 'sl12_p1_own')
    .choice(tr('sl12.c1_min'), 'sl12_p1_min')
    .endMenu()
    .scene('sl12_p1_natural', 'sl12_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl12.p1_nat_yuki'), 'happy')
    .jump('sl12_after_p1')
    .scene('sl12_p1_formal', 'sl12_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl12.p1_form_ken'), 'laugh')
    .jump('sl12_after_p1')
    .scene('sl12_p1_mistake', 'sl12_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl12.p1_mis_tanaka'), 'neutral')
    .jump('sl12_p1_mistake2')
    .scene('sl12_p1_mistake2', 'sl12_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl12.p1_mis_relief'), 'happy')
    .jump('sl12_after_p1')
    .scene('sl12_p1_own', 'sl12_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl12.p1_own_yuki'), 'happy')
    .jump('sl12_after_p1')
    .scene('sl12_p1_min', 'sl12_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl12.p1_min_mei'), 'happy')
    .jump('sl12_after_p1')
    .scene('sl12_after_p1', 'sl12_after_p1')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('sl12.inside'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl12.s2_intro'), 'speaking')
    .tanaka(tr('sl12.s2_ex'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl12.s2_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl12.s2_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl12.s2_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl12.s2_a2'), 'speaking')
    .tanaka(tr('sl12.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl12.c2_natural'), 'sl12_p2_natural')
    .choice(tr('sl12.c2_formal'), 'sl12_p2_formal')
    .choice(tr('sl12.c2_mistake'), 'sl12_p2_mistake')
    .choice(tr('sl12.c2_own'), 'sl12_p2_own')
    .choice(tr('sl12.c2_min'), 'sl12_p2_min')
    .endMenu()
    .scene('sl12_p2_natural', 'sl12_p2_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c2_natural'), 'surprised')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl12.p2_nat_ken'), 'surprised')
    .jump('sl12_after_p2')
    .scene('sl12_p2_formal', 'sl12_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl12.p2_form_mei'), 'laugh')
    .jump('sl12_after_p2')
    .scene('sl12_p2_mistake', 'sl12_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl12.p2_mis_tanaka'), 'neutral')
    .jump('sl12_p2_mistake2')
    .scene('sl12_p2_mistake2', 'sl12_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl12.p2_mis_relief'), 'happy')
    .jump('sl12_after_p2')
    .scene('sl12_p2_own', 'sl12_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl12.p2_own_ken'), 'happy')
    .jump('sl12_after_p2')
    .scene('sl12_p2_min', 'sl12_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl12.p2_min_yuki'), 'gentle')
    .jump('sl12_after_p2')
    .scene('sl12_after_p2', 'sl12_after_p2')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl12.s3_intro'), 'speaking')
    .tanaka(tr('sl12.s3_ex'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl12.s3_q1'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl12.s3_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl12.s3_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl12.s3_a2'), 'speaking')
    .tanaka(tr('sl12.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl12.c3_natural'), 'sl12_p3_natural')
    .choice(tr('sl12.c3_formal'), 'sl12_p3_formal')
    .choice(tr('sl12.c3_mistake'), 'sl12_p3_mistake')
    .choice(tr('sl12.c3_own'), 'sl12_p3_own')
    .choice(tr('sl12.c3_min'), 'sl12_p3_min')
    .endMenu()
    .scene('sl12_p3_natural', 'sl12_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl12.p3_nat_yuki'), 'happy')
    .jump('sl12_after_p3')
    .scene('sl12_p3_formal', 'sl12_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl12.p3_form_ken'), 'laugh')
    .jump('sl12_after_p3')
    .scene('sl12_p3_mistake', 'sl12_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl12.p3_mis_tanaka'), 'neutral')
    .jump('sl12_p3_mistake2')
    .scene('sl12_p3_mistake2', 'sl12_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl12.p3_mis_relief'), 'happy')
    .jump('sl12_after_p3')
    .scene('sl12_p3_own', 'sl12_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl12.p3_own_yuki'), 'happy')
    .jump('sl12_after_p3')
    .scene('sl12_p3_min', 'sl12_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl12.p3_min_mei'), 'happy')
    .jump('sl12_after_p3')
    .scene('sl12_after_p3', 'sl12_after_p3')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .bg('temple', 'afternoon')
    .n(tr('sl12.hall'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl12.s4_intro'), 'speaking')
    .tanaka(tr('sl12.s4_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl12.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl12.s4_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl12.s4_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl12.s4_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl12.m_ask'), 'neutral')
    .tanaka(tr('sl12.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl12.c4_natural'), 'sl12_p4_natural')
    .choice(tr('sl12.c4_formal'), 'sl12_p4_formal')
    .choice(tr('sl12.c4_mistake'), 'sl12_p4_mistake')
    .choice(tr('sl12.c4_own'), 'sl12_p4_own')
    .choice(tr('sl12.c4_min'), 'sl12_p4_min')
    .endMenu()
    .scene('sl12_p4_natural', 'sl12_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c4_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl12.p4_nat_mei'), 'happy')
    .jump('sl12_talk')
    .scene('sl12_p4_formal', 'sl12_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl12.p4_form_ken'), 'laugh')
    .jump('sl12_talk')
    .scene('sl12_p4_mistake', 'sl12_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl12.p4_mis_tanaka'), 'neutral')
    .jump('sl12_p4_mistake2')
    .scene('sl12_p4_mistake2', 'sl12_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl12.p4_mis_relief'), 'happy')
    .jump('sl12_talk')
    .scene('sl12_p4_own', 'sl12_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c4_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl12.p4_own_mei'), 'happy')
    .jump('sl12_talk')
    .scene('sl12_p4_min', 'sl12_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl12.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl12.p4_min_yuki'), 'gentle')
    .jump('sl12_talk')
    .scene('sl12_talk', 'sl12_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl12.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl12.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl12.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl12.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl12.talk_tanaka'), 'happy')
    .player(tr('sl12.talk_player'), 'neutral')
    .tanaka(tr('sl12.talk_close'), 'happy')
    .n(tr('sl12.complete'))
    .end()
    .build();
