import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson05 = SentenceLessonDefinition(
  id: 'sentence_lesson_05',
  number: 5,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl5.title',
  subtitleKey: 'sl5.subtitle',
  descriptionKey: 'sl5.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl5.pattern.1',
    'sl5.pattern.2',
    'sl5.pattern.3',
    'sl5.pattern.4',
  ],
  storyFactory: getSentenceLesson05,
);

StoryData getSentenceLesson05() => dialogue()
    .story(5, tr('sl5.title'), tr('sl5.subtitle'))
    .description(tr('sl5.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('sl5_stall', 'sl5_stall')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .street('afternoon')
    .titleCard(tr('sl5.title'), tr('sl5.subtitle'), 2500)
    .n(tr('sl5.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl5.t_intro'), 'happy')
    .tanaka(tr('sl5.s1_count'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl5.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl5.s1_a1'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('sl5.s1_hyaku'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl5.s1_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl5.s1_a2'), 'speaking')
    .tanaka(tr('sl5.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl5.c1_natural'), 'sl5_p1_natural')
    .choice(tr('sl5.c1_formal'), 'sl5_p1_formal')
    .choice(tr('sl5.c1_mistake'), 'sl5_p1_mistake')
    .choice(tr('sl5.c1_own'), 'sl5_p1_own')
    .choice(tr('sl5.c1_min'), 'sl5_p1_min')
    .endMenu()
    .scene('sl5_p1_natural', 'sl5_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c1_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl5.p1_nat_mei'), 'happy')
    .jump('sl5_after_p1')
    .scene('sl5_p1_formal', 'sl5_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl5.p1_form_ken'), 'laugh')
    .jump('sl5_after_p1')
    .scene('sl5_p1_mistake', 'sl5_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c1_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl5.p1_mis_yuki'), 'neutral')
    .jump('sl5_p1_mistake2')
    .scene('sl5_p1_mistake2', 'sl5_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.p1_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl5.p1_mis_relief'), 'happy')
    .jump('sl5_after_p1')
    .scene('sl5_p1_own', 'sl5_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p1_own_ken'), 'happy')
    .jump('sl5_after_p1')
    .scene('sl5_p1_min', 'sl5_p1_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c1_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl5.p1_min_tanaka'), 'happy')
    .jump('sl5_after_p1')
    .scene('sl5_after_p1', 'sl5_after_p1')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl5.s2_watch'), 'neutral')
    .hide('mei')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl5.s2_intro'), 'speaking')
    .tanaka(tr('sl5.s2_special'), 'speaking')
    .tanaka(tr('sl5.s2_min'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl5.s2_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl5.s2_a'), 'speaking')
    .tanaka(tr('sl5.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl5.c2_natural'), 'sl5_p2_natural')
    .choice(tr('sl5.c2_formal'), 'sl5_p2_formal')
    .choice(tr('sl5.c2_mistake'), 'sl5_p2_mistake')
    .choice(tr('sl5.c2_own'), 'sl5_p2_own')
    .choice(tr('sl5.c2_min'), 'sl5_p2_min')
    .endMenu()
    .scene('sl5_p2_natural', 'sl5_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl5.p2_nat_tanaka'), 'happy')
    .jump('sl5_after_p2')
    .scene('sl5_p2_formal', 'sl5_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl5.p2_form_yuki'), 'laugh')
    .jump('sl5_after_p2')
    .scene('sl5_p2_mistake', 'sl5_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c2_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl5.p2_mis_ken'), 'neutral')
    .jump('sl5_p2_mistake2')
    .scene('sl5_p2_mistake2', 'sl5_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p2_mis_relief'), 'happy')
    .jump('sl5_after_p2')
    .scene('sl5_p2_own', 'sl5_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl5.p2_own_mei'), 'happy')
    .jump('sl5_after_p2')
    .scene('sl5_p2_min', 'sl5_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl5.p2_min_yuki'), 'gentle')
    .jump('sl5_after_p2')
    .scene('sl5_after_p2', 'sl5_after_p2')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('sl5.sign'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl5.s3_intro'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl5.s3_q1'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl5.s3_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl5.s3_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl5.s3_a2'), 'speaking')
    .tanaka(tr('sl5.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl5.c3_natural'), 'sl5_p3_natural')
    .choice(tr('sl5.c3_formal'), 'sl5_p3_formal')
    .choice(tr('sl5.c3_mistake'), 'sl5_p3_mistake')
    .choice(tr('sl5.c3_own'), 'sl5_p3_own')
    .choice(tr('sl5.c3_min'), 'sl5_p3_min')
    .endMenu()
    .scene('sl5_p3_natural', 'sl5_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c3_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p3_nat_ken'), 'happy')
    .jump('sl5_after_p3')
    .scene('sl5_p3_formal', 'sl5_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl5.p3_form_ken'), 'laugh')
    .jump('sl5_after_p3')
    .scene('sl5_p3_mistake', 'sl5_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c3_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl5.p3_mis_mei'), 'surprised')
    .jump('sl5_p3_mistake2')
    .scene('sl5_p3_mistake2', 'sl5_p3_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.p3_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p3_mis_relief'), 'happy')
    .jump('sl5_after_p3')
    .scene('sl5_p3_own', 'sl5_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p3_own_ken'), 'happy')
    .jump('sl5_after_p3')
    .scene('sl5_p3_min', 'sl5_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl5.p3_min_yuki'), 'gentle')
    .jump('sl5_after_p3')
    .scene('sl5_after_p3', 'sl5_after_p3')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl5.s4_intro'), 'speaking')
    .tanaka(tr('sl5.s4_list'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl5.s4_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl5.s4_a'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.s4_total'), 'happy')
    .tanaka(tr('sl5.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl5.c4_natural'), 'sl5_p4_natural')
    .choice(tr('sl5.c4_formal'), 'sl5_p4_formal')
    .choice(tr('sl5.c4_mistake'), 'sl5_p4_mistake')
    .choice(tr('sl5.c4_own'), 'sl5_p4_own')
    .choice(tr('sl5.c4_min'), 'sl5_p4_min')
    .endMenu()
    .scene('sl5_p4_natural', 'sl5_p4_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c4_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p4_nat_ken'), 'happy')
    .jump('sl5_talk')
    .scene('sl5_p4_formal', 'sl5_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl5.p4_form_mei'), 'laugh')
    .jump('sl5_talk')
    .scene('sl5_p4_mistake', 'sl5_p4_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c4_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl5.p4_mis_yuki'), 'neutral')
    .jump('sl5_p4_mistake2')
    .scene('sl5_p4_mistake2', 'sl5_p4_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.p4_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p4_mis_relief'), 'happy')
    .jump('sl5_talk')
    .scene('sl5_p4_own', 'sl5_p4_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c4_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl5.p4_own_ken'), 'happy')
    .jump('sl5_talk')
    .scene('sl5_p4_min', 'sl5_p4_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl5.c4_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl5.p4_min_tanaka'), 'happy')
    .jump('sl5_talk')
    .scene('sl5_talk', 'sl5_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl5.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl5.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl5.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl5.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl5.talk_tanaka'), 'happy')
    .player(tr('sl5.talk_player'), 'neutral')
    .tanaka(tr('sl5.talk_close'), 'happy')
    .n(tr('sl5.complete'))
    .end()
    .build();
