import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson03 = SentenceLessonDefinition(
  id: 'sentence_lesson_03',
  number: 3,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl3.title',
  subtitleKey: 'sl3.subtitle',
  descriptionKey: 'sl3.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl3.pattern.1',
    'sl3.pattern.2',
    'sl3.pattern.3',
    'sl3.pattern.4',
  ],
  storyFactory: getSentenceLesson03,
);

StoryData getSentenceLesson03() => dialogue()
    .story(3, tr('sl3.title'), tr('sl3.subtitle'))
    .description(tr('sl3.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('sl3_hall', 'sl3_hall')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .bg('university_building', 'morning')
    .titleCard(tr('sl3.title'), tr('sl3.subtitle'), 2500)
    .n(tr('sl3.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.t_intro'), 'happy')
    .tanaka(tr('sl3.s1_koko'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl3.s1_soko'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl3.s1_yes'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('sl3.s1_asoko'), 'happy')
    .hide('mei')
    .tanaka(tr('sl3.s1_break'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl3.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl3.s1_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl3.s1_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl3.s1_a2'), 'speaking')
    .tanaka(tr('sl3.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl3.c1_natural'), 'sl3_p1_natural')
    .choice(tr('sl3.c1_formal'), 'sl3_p1_formal')
    .choice(tr('sl3.c1_mistake'), 'sl3_p1_mistake')
    .choice(tr('sl3.c1_own'), 'sl3_p1_own')
    .choice(tr('sl3.c1_min'), 'sl3_p1_min')
    .endMenu()
    .scene('sl3_p1_natural', 'sl3_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl3.p1_nat_yuki'), 'happy')
    .jump('sl3_class')
    .scene('sl3_p1_formal', 'sl3_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl3.p1_form_ken'), 'laugh')
    .jump('sl3_class')
    .scene('sl3_p1_mistake', 'sl3_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c1_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl3.p1_mis_mei'), 'surprised')
    .jump('sl3_p1_mistake2')
    .scene('sl3_p1_mistake2', 'sl3_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.p1_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl3.p1_mis_relief'), 'happy')
    .jump('sl3_class')
    .scene('sl3_p1_own', 'sl3_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl3.p1_own_yuki'), 'happy')
    .jump('sl3_class')
    .scene('sl3_p1_min', 'sl3_p1_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c1_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.p1_min_tanaka'), 'happy')
    .jump('sl3_class')
    .scene('sl3_class', 'sl3_class')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('morning')
    .n(tr('sl3.class'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl3.s2_intro'), 'speaking')
    .tanaka(tr('sl3.s2_ex'), 'speaking')
    .tanaka(tr('sl3.s2_break'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl3.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl3.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl3.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl3.s2_a2'), 'speaking')
    .tanaka(tr('sl3.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl3.c2_natural'), 'sl3_p2_natural')
    .choice(tr('sl3.c2_formal'), 'sl3_p2_formal')
    .choice(tr('sl3.c2_mistake'), 'sl3_p2_mistake')
    .choice(tr('sl3.c2_own'), 'sl3_p2_own')
    .choice(tr('sl3.c2_min'), 'sl3_p2_min')
    .endMenu()
    .scene('sl3_p2_natural', 'sl3_p2_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c2_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl3.p2_nat_ken'), 'happy')
    .jump('sl3_after_p2')
    .scene('sl3_p2_formal', 'sl3_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl3.p2_form_mei'), 'laugh')
    .jump('sl3_after_p2')
    .scene('sl3_p2_mistake', 'sl3_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c2_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl3.p2_mis_ken'), 'neutral')
    .jump('sl3_p2_mistake2')
    .scene('sl3_p2_mistake2', 'sl3_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl3.p2_mis_relief'), 'happy')
    .jump('sl3_after_p2')
    .scene('sl3_p2_own', 'sl3_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl3.p2_own_ken'), 'happy')
    .jump('sl3_after_p2')
    .scene('sl3_p2_min', 'sl3_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.p2_min_tanaka'), 'happy')
    .jump('sl3_after_p2')
    .scene('sl3_after_p2', 'sl3_after_p2')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl3.s3_neko'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl3.s3_intro'), 'speaking')
    .tanaka(tr('sl3.s3_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl3.s3_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl3.s3_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl3.s3_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl3.s3_a2'), 'speaking')
    .tanaka(tr('sl3.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl3.c3_natural'), 'sl3_p3_natural')
    .choice(tr('sl3.c3_formal'), 'sl3_p3_formal')
    .choice(tr('sl3.c3_mistake'), 'sl3_p3_mistake')
    .choice(tr('sl3.c3_own'), 'sl3_p3_own')
    .choice(tr('sl3.c3_min'), 'sl3_p3_min')
    .endMenu()
    .scene('sl3_p3_natural', 'sl3_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl3.p3_nat_mei'), 'happy')
    .jump('sl3_after_p3')
    .scene('sl3_p3_formal', 'sl3_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl3.p3_form_yuki'), 'laugh')
    .jump('sl3_after_p3')
    .scene('sl3_p3_mistake', 'sl3_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c3_mistake'), 'concerned')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl3.p3_mis_ken'), 'laugh')
    .jump('sl3_p3_mistake2')
    .scene('sl3_p3_mistake2', 'sl3_p3_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.p3_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl3.p3_mis_relief'), 'happy')
    .jump('sl3_after_p3')
    .scene('sl3_p3_own', 'sl3_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl3.p3_own_yuki'), 'happy')
    .jump('sl3_after_p3')
    .scene('sl3_p3_min', 'sl3_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl3.p3_min_mei'), 'happy')
    .jump('sl3_after_p3')
    .scene('sl3_after_p3', 'sl3_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl3.s4_intro'), 'speaking')
    .tanaka(tr('sl3.s4_ex'), 'speaking')
    .tanaka(tr('sl3.s4_pos'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl3.s4_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl3.s4_a'), 'speaking')
    .tanaka(tr('sl3.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl3.c4_natural'), 'sl3_p4_natural')
    .choice(tr('sl3.c4_formal'), 'sl3_p4_formal')
    .choice(tr('sl3.c4_mistake'), 'sl3_p4_mistake')
    .choice(tr('sl3.c4_own'), 'sl3_p4_own')
    .choice(tr('sl3.c4_min'), 'sl3_p4_min')
    .endMenu()
    .scene('sl3_p4_natural', 'sl3_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.p4_nat_tanaka'), 'happy')
    .jump('sl3_talk')
    .scene('sl3_p4_formal', 'sl3_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl3.p4_form_ken'), 'laugh')
    .jump('sl3_talk')
    .scene('sl3_p4_mistake', 'sl3_p4_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c4_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl3.p4_mis_mei'), 'laugh')
    .jump('sl3_p4_mistake2')
    .scene('sl3_p4_mistake2', 'sl3_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.p4_mis_relief'), 'happy')
    .jump('sl3_talk')
    .scene('sl3_p4_own', 'sl3_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.p4_own_tanaka'), 'happy')
    .jump('sl3_talk')
    .scene('sl3_p4_min', 'sl3_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl3.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl3.p4_min_yuki'), 'gentle')
    .jump('sl3_talk')
    .scene('sl3_talk', 'sl3_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl3.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl3.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl3.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl3.talk_tanaka'), 'happy')
    .player(tr('sl3.talk_player'), 'neutral')
    .tanaka(tr('sl3.talk_close'), 'happy')
    .n(tr('sl3.complete'))
    .end()
    .build();
