import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson18 = SentenceLessonDefinition(
  id: 'sentence_lesson_18',
  number: 18,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl18.title',
  subtitleKey: 'sl18.subtitle',
  descriptionKey: 'sl18.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl18.pattern.1',
    'sl18.pattern.2',
    'sl18.pattern.3',
    'sl18.pattern.4',
  ],
  storyFactory: getSentenceLesson18,
);

StoryData getSentenceLesson18() => dialogue()
    .story(18, tr('sl18.title'), tr('sl18.subtitle'))
    .description(tr('sl18.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl18_class', 'sl18_class')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('afternoon')
    .titleCard(tr('sl18.title'), tr('sl18.subtitle'), 2500)
    .n(tr('sl18.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.t_intro'), 'happy')
    .tanaka(tr('sl18.s1_intro'), 'speaking')
    .tanaka(tr('sl18.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl18.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl18.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl18.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl18.s1_a2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl18.s1_q3'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl18.s1_a3'), 'speaking')
    .tanaka(tr('sl18.tanaka_ask'), 'neutral')
    .tanaka(tr('sl18.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl18.c1_natural'), 'sl18_p1_natural')
    .choice(tr('sl18.c1_formal'), 'sl18_p1_formal')
    .choice(tr('sl18.c1_mistake'), 'sl18_p1_mistake')
    .choice(tr('sl18.c1_own'), 'sl18_p1_own')
    .choice(tr('sl18.c1_min'), 'sl18_p1_min')
    .endMenu()
    .scene('sl18_p1_natural', 'sl18_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.p1_nat_tanaka'), 'happy')
    .jump('sl18_after_p1')
    .scene('sl18_p1_formal', 'sl18_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl18.p1_form_ken'), 'laugh')
    .jump('sl18_after_p1')
    .scene('sl18_p1_mistake', 'sl18_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl18.p1_mis_tanaka'), 'neutral')
    .jump('sl18_p1_mistake2')
    .scene('sl18_p1_mistake2', 'sl18_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.p1_mis_relief'), 'happy')
    .jump('sl18_after_p1')
    .scene('sl18_p1_own', 'sl18_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.p1_own_tanaka'), 'happy')
    .jump('sl18_after_p1')
    .scene('sl18_p1_min', 'sl18_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl18.p1_min_yuki'), 'gentle')
    .jump('sl18_after_p1')
    .scene('sl18_after_p1', 'sl18_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl18.s2_intro'), 'speaking')
    .tanaka(tr('sl18.s2_potential'), 'speaking')
    .tanaka(tr('sl18.s2_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl18.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl18.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl18.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl18.s2_a2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl18.y_ask'), 'neutral')
    .tanaka(tr('sl18.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl18.c2_natural'), 'sl18_p2_natural')
    .choice(tr('sl18.c2_formal'), 'sl18_p2_formal')
    .choice(tr('sl18.c2_mistake'), 'sl18_p2_mistake')
    .choice(tr('sl18.c2_own'), 'sl18_p2_own')
    .choice(tr('sl18.c2_min'), 'sl18_p2_min')
    .endMenu()
    .scene('sl18_p2_natural', 'sl18_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl18.p2_nat_yuki'), 'happy')
    .jump('sl18_after_p2')
    .scene('sl18_p2_formal', 'sl18_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl18.p2_form_mei'), 'laugh')
    .jump('sl18_after_p2')
    .scene('sl18_p2_mistake', 'sl18_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl18.p2_mis_tanaka'), 'neutral')
    .jump('sl18_p2_mistake2')
    .scene('sl18_p2_mistake2', 'sl18_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.p2_mis_relief'), 'happy')
    .jump('sl18_after_p2')
    .scene('sl18_p2_own', 'sl18_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl18.p2_own_mei'), 'happy')
    .jump('sl18_after_p2')
    .scene('sl18_p2_min', 'sl18_p2_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c2_min'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl18.p2_min_ken'), 'neutral')
    .jump('sl18_after_p2')
    .scene('sl18_after_p2', 'sl18_after_p2')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl18.s3_intro'), 'speaking')
    .tanaka(tr('sl18.s3_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl18.s3_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl18.s3_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl18.s3_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl18.s3_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl18.m_ask'), 'neutral')
    .tanaka(tr('sl18.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl18.c3_natural'), 'sl18_p3_natural')
    .choice(tr('sl18.c3_formal'), 'sl18_p3_formal')
    .choice(tr('sl18.c3_mistake'), 'sl18_p3_mistake')
    .choice(tr('sl18.c3_own'), 'sl18_p3_own')
    .choice(tr('sl18.c3_min'), 'sl18_p3_min')
    .endMenu()
    .scene('sl18_p3_natural', 'sl18_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl18.p3_nat_mei'), 'happy')
    .jump('sl18_after_p3')
    .scene('sl18_p3_formal', 'sl18_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl18.p3_form_ken'), 'laugh')
    .jump('sl18_after_p3')
    .scene('sl18_p3_mistake', 'sl18_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl18.p3_mis_tanaka'), 'neutral')
    .jump('sl18_p3_mistake2')
    .scene('sl18_p3_mistake2', 'sl18_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.p3_mis_relief'), 'happy')
    .jump('sl18_after_p3')
    .scene('sl18_p3_own', 'sl18_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c3_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl18.p3_own_mei'), 'happy')
    .jump('sl18_after_p3')
    .scene('sl18_p3_min', 'sl18_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl18.p3_min_yuki'), 'gentle')
    .jump('sl18_after_p3')
    .scene('sl18_after_p3', 'sl18_after_p3')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl18.s4_intro'), 'speaking')
    .tanaka(tr('sl18.s4_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl18.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl18.s4_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl18.s4_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl18.s4_a2'), 'speaking')
    .tanaka(tr('sl18.tanaka_future'), 'happy')
    .tanaka(tr('sl18.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl18.c4_natural'), 'sl18_p4_natural')
    .choice(tr('sl18.c4_formal'), 'sl18_p4_formal')
    .choice(tr('sl18.c4_mistake'), 'sl18_p4_mistake')
    .choice(tr('sl18.c4_own'), 'sl18_p4_own')
    .choice(tr('sl18.c4_min'), 'sl18_p4_min')
    .endMenu()
    .scene('sl18_p4_natural', 'sl18_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.p4_nat_tanaka'), 'happy')
    .jump('sl18_talk')
    .scene('sl18_p4_formal', 'sl18_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl18.p4_form_mei'), 'laugh')
    .jump('sl18_talk')
    .scene('sl18_p4_mistake', 'sl18_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c4_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl18.p4_mis_ken'), 'neutral')
    .jump('sl18_p4_mistake2')
    .scene('sl18_p4_mistake2', 'sl18_p4_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.p4_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl18.p4_mis_relief'), 'happy')
    .jump('sl18_talk')
    .scene('sl18_p4_own', 'sl18_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.p4_own_tanaka'), 'happy')
    .jump('sl18_talk')
    .scene('sl18_p4_min', 'sl18_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl18.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl18.p4_min_yuki'), 'gentle')
    .jump('sl18_talk')
    .scene('sl18_talk', 'sl18_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl18.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'happy')
    .ken(tr('sl18.talk_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl18.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl18.talk_tanaka'), 'happy')
    .player(tr('sl18.talk_player'), 'neutral')
    .tanaka(tr('sl18.talk_close'), 'happy')
    .n(tr('sl18.complete'))
    .end()
    .build();
