import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson10 = SentenceLessonDefinition(
  id: 'sentence_lesson_10',
  number: 10,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl10.title',
  subtitleKey: 'sl10.subtitle',
  descriptionKey: 'sl10.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl10.pattern.1',
    'sl10.pattern.2',
    'sl10.pattern.3',
    'sl10.pattern.4',
  ],
  storyFactory: getSentenceLesson10,
);

StoryData getSentenceLesson10() => dialogue()
    .story(10, tr('sl10.title'), tr('sl10.subtitle'))
    .description(tr('sl10.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5')
    .scene('sl10_class', 'sl10_class')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('afternoon')
    .titleCard(tr('sl10.title'), tr('sl10.subtitle'), 2500)
    .n(tr('sl10.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl10.t_intro'), 'happy')
    .tanaka(tr('sl10.s1_intro'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('sl10.s1_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl10.s1_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl10.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl10.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl10.s1_a2'), 'speaking')
    .tanaka(tr('sl10.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl10.c1_natural'), 'sl10_p1_natural')
    .choice(tr('sl10.c1_formal'), 'sl10_p1_formal')
    .choice(tr('sl10.c1_mistake'), 'sl10_p1_mistake')
    .choice(tr('sl10.c1_own'), 'sl10_p1_own')
    .choice(tr('sl10.c1_min'), 'sl10_p1_min')
    .endMenu()
    .scene('sl10_p1_natural', 'sl10_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c1_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl10.p1_nat_mei'), 'happy')
    .jump('sl10_after_p1')
    .scene('sl10_p1_formal', 'sl10_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl10.p1_form_ken'), 'laugh')
    .jump('sl10_after_p1')
    .scene('sl10_p1_mistake', 'sl10_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl10.p1_mis_tanaka'), 'neutral')
    .jump('sl10_p1_mistake2')
    .scene('sl10_p1_mistake2', 'sl10_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.p1_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl10.p1_mis_relief'), 'happy')
    .jump('sl10_after_p1')
    .scene('sl10_p1_own', 'sl10_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c1_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl10.p1_own_mei'), 'happy')
    .jump('sl10_after_p1')
    .scene('sl10_p1_min', 'sl10_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl10.p1_min_yuki'), 'gentle')
    .jump('sl10_after_p1')
    .scene('sl10_after_p1', 'sl10_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl10.s2_intro'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('sl10.s2_ken'), 'happy')
    .hide('ken')
    .tanaka(tr('sl10.s2_a'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl10.s2_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl10.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl10.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl10.s2_a2'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('sl10.p2_ken'), 'happy')
    .tanaka(tr('sl10.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl10.c2_natural'), 'sl10_p2_natural')
    .choice(tr('sl10.c2_formal'), 'sl10_p2_formal')
    .choice(tr('sl10.c2_mistake'), 'sl10_p2_mistake')
    .choice(tr('sl10.c2_own'), 'sl10_p2_own')
    .choice(tr('sl10.c2_min'), 'sl10_p2_min')
    .endMenu()
    .scene('sl10_p2_natural', 'sl10_p2_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c2_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl10.p2_nat_ken'), 'happy')
    .jump('sl10_after_p2')
    .scene('sl10_p2_formal', 'sl10_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl10.p2_form_mei'), 'laugh')
    .jump('sl10_after_p2')
    .scene('sl10_p2_mistake', 'sl10_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c2_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl10.p2_mis_ken'), 'surprised')
    .jump('sl10_p2_mistake2')
    .scene('sl10_p2_mistake2', 'sl10_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl10.p2_mis_relief'), 'happy')
    .jump('sl10_after_p2')
    .scene('sl10_p2_own', 'sl10_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl10.p2_own_ken'), 'happy')
    .jump('sl10_after_p2')
    .scene('sl10_p2_min', 'sl10_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl10.p2_min_tanaka'), 'happy')
    .jump('sl10_after_p2')
    .scene('sl10_after_p2', 'sl10_after_p2')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl10.s3_intro'), 'speaking')
    .tanaka(tr('sl10.s3_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl10.s3_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl10.s3_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl10.s3_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl10.s3_a2'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl10.y_invite'), 'happy')
    .tanaka(tr('sl10.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl10.c3_natural'), 'sl10_p3_natural')
    .choice(tr('sl10.c3_formal'), 'sl10_p3_formal')
    .choice(tr('sl10.c3_mistake'), 'sl10_p3_mistake')
    .choice(tr('sl10.c3_own'), 'sl10_p3_own')
    .choice(tr('sl10.c3_min'), 'sl10_p3_min')
    .endMenu()
    .scene('sl10_p3_natural', 'sl10_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl10.p3_nat_yuki'), 'happy')
    .jump('sl10_after_p3')
    .scene('sl10_p3_formal', 'sl10_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl10.p3_form_ken'), 'laugh')
    .jump('sl10_after_p3')
    .scene('sl10_p3_mistake', 'sl10_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c3_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl10.p3_mis_mei'), 'surprised')
    .jump('sl10_p3_mistake2')
    .scene('sl10_p3_mistake2', 'sl10_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.p3_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl10.p3_mis_relief'), 'happy')
    .jump('sl10_after_p3')
    .scene('sl10_p3_own', 'sl10_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl10.p3_own_yuki'), 'happy')
    .jump('sl10_after_p3')
    .scene('sl10_p3_min', 'sl10_p3_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c3_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl10.p3_min_tanaka'), 'happy')
    .jump('sl10_after_p3')
    .scene('sl10_after_p3', 'sl10_after_p3')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .station('afternoon')
    .n(tr('sl10.station'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl10.s4_intro'), 'speaking')
    .tanaka(tr('sl10.s4_ex'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl10.s4_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl10.s4_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl10.s4_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl10.s4_a2'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('sl10.m_ask'), 'happy')
    .tanaka(tr('sl10.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl10.c4_natural'), 'sl10_p4_natural')
    .choice(tr('sl10.c4_formal'), 'sl10_p4_formal')
    .choice(tr('sl10.c4_mistake'), 'sl10_p4_mistake')
    .choice(tr('sl10.c4_own'), 'sl10_p4_own')
    .choice(tr('sl10.c4_min'), 'sl10_p4_min')
    .endMenu()
    .scene('sl10_p4_natural', 'sl10_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c4_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl10.p4_nat_mei'), 'happy')
    .jump('sl10_talk')
    .scene('sl10_p4_formal', 'sl10_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl10.p4_form_ken'), 'laugh')
    .jump('sl10_talk')
    .scene('sl10_p4_mistake', 'sl10_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl10.p4_mis_tanaka'), 'neutral')
    .jump('sl10_p4_mistake2')
    .scene('sl10_p4_mistake2', 'sl10_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl10.p4_mis_relief'), 'happy')
    .jump('sl10_talk')
    .scene('sl10_p4_own', 'sl10_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c4_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl10.p4_own_mei'), 'happy')
    .jump('sl10_talk')
    .scene('sl10_p4_min', 'sl10_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl10.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl10.p4_min_yuki'), 'gentle')
    .jump('sl10_talk')
    .scene('sl10_talk', 'sl10_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl10.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl10.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl10.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl10.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl10.talk_tanaka'), 'happy')
    .tanaka(tr('sl10.talk_recap'), 'speaking')
    .player(tr('sl10.talk_player'), 'neutral')
    .tanaka(tr('sl10.talk_close'), 'happy')
    .n(tr('sl10.complete'))
    .end()
    .build();
