import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson13 = SentenceLessonDefinition(
  id: 'sentence_lesson_13',
  number: 13,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl13.title',
  subtitleKey: 'sl13.subtitle',
  descriptionKey: 'sl13.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl13.pattern.1',
    'sl13.pattern.2',
    'sl13.pattern.3',
    'sl13.pattern.4',
  ],
  storyFactory: getSentenceLesson13,
);

StoryData getSentenceLesson13() => dialogue()
    .story(13, tr('sl13.title'), tr('sl13.subtitle'))
    .description(tr('sl13.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl13_street', 'sl13_street')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .street('afternoon')
    .titleCard(tr('sl13.title'), tr('sl13.subtitle'), 2500)
    .n(tr('sl13.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl13.t_intro'), 'happy')
    .tanaka(tr('sl13.s1_intro'), 'speaking')
    .tanaka(tr('sl13.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl13.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl13.s1_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl13.s1_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl13.s1_a2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl13.k_ask'), 'neutral')
    .tanaka(tr('sl13.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl13.c1_natural'), 'sl13_p1_natural')
    .choice(tr('sl13.c1_formal'), 'sl13_p1_formal')
    .choice(tr('sl13.c1_mistake'), 'sl13_p1_mistake')
    .choice(tr('sl13.c1_own'), 'sl13_p1_own')
    .choice(tr('sl13.c1_min'), 'sl13_p1_min')
    .endMenu()
    .scene('sl13_p1_natural', 'sl13_p1_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c1_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl13.p1_nat_ken'), 'happy')
    .jump('sl13_cafe')
    .scene('sl13_p1_formal', 'sl13_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl13.p1_form_mei'), 'laugh')
    .jump('sl13_cafe')
    .scene('sl13_p1_mistake', 'sl13_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl13.p1_mis_tanaka'), 'neutral')
    .jump('sl13_p1_mistake2')
    .scene('sl13_p1_mistake2', 'sl13_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl13.p1_mis_relief'), 'happy')
    .jump('sl13_cafe')
    .scene('sl13_p1_own', 'sl13_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl13.p1_own_ken'), 'happy')
    .jump('sl13_cafe')
    .scene('sl13_p1_min', 'sl13_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl13.p1_min_yuki'), 'gentle')
    .jump('sl13_cafe')
    .scene('sl13_cafe', 'sl13_cafe')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('afternoon')
    .n(tr('sl13.cafe'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl13.s2_intro'), 'speaking')
    .tanaka(tr('sl13.s2_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl13.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl13.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl13.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl13.s2_a2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl13.y_ask'), 'neutral')
    .tanaka(tr('sl13.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl13.c2_natural'), 'sl13_p2_natural')
    .choice(tr('sl13.c2_formal'), 'sl13_p2_formal')
    .choice(tr('sl13.c2_mistake'), 'sl13_p2_mistake')
    .choice(tr('sl13.c2_own'), 'sl13_p2_own')
    .choice(tr('sl13.c2_min'), 'sl13_p2_min')
    .endMenu()
    .scene('sl13_p2_natural', 'sl13_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl13.p2_nat_yuki'), 'happy')
    .jump('sl13_after_cafe')
    .scene('sl13_p2_formal', 'sl13_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl13.p2_form_ken'), 'laugh')
    .jump('sl13_after_cafe')
    .scene('sl13_p2_mistake', 'sl13_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl13.p2_mis_tanaka'), 'neutral')
    .jump('sl13_p2_mistake2')
    .scene('sl13_p2_mistake2', 'sl13_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl13.p2_mis_relief'), 'happy')
    .jump('sl13_after_cafe')
    .scene('sl13_p2_own', 'sl13_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c2_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl13.p2_own_yuki'), 'happy')
    .jump('sl13_after_cafe')
    .scene('sl13_p2_min', 'sl13_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl13.p2_min_mei'), 'happy')
    .jump('sl13_after_cafe')
    .scene('sl13_after_cafe', 'sl13_after_cafe')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .street('evening')
    .n(tr('sl13.evening'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl13.s3_intro'), 'speaking')
    .tanaka(tr('sl13.s3_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl13.s3_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl13.s3_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl13.s3_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl13.s3_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl13.m_ask'), 'neutral')
    .tanaka(tr('sl13.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl13.c3_natural'), 'sl13_p3_natural')
    .choice(tr('sl13.c3_formal'), 'sl13_p3_formal')
    .choice(tr('sl13.c3_mistake'), 'sl13_p3_mistake')
    .choice(tr('sl13.c3_own'), 'sl13_p3_own')
    .choice(tr('sl13.c3_min'), 'sl13_p3_min')
    .endMenu()
    .scene('sl13_p3_natural', 'sl13_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl13.p3_nat_mei'), 'happy')
    .jump('sl13_after_p3')
    .scene('sl13_p3_formal', 'sl13_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl13.p3_form_ken'), 'laugh')
    .jump('sl13_after_p3')
    .scene('sl13_p3_mistake', 'sl13_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl13.p3_mis_tanaka'), 'neutral')
    .jump('sl13_p3_mistake2')
    .scene('sl13_p3_mistake2', 'sl13_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl13.p3_mis_relief'), 'happy')
    .jump('sl13_after_p3')
    .scene('sl13_p3_own', 'sl13_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c3_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl13.p3_own_mei'), 'happy')
    .jump('sl13_after_p3')
    .scene('sl13_p3_min', 'sl13_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl13.p3_min_yuki'), 'gentle')
    .jump('sl13_after_p3')
    .scene('sl13_after_p3', 'sl13_after_p3')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl13.s4_intro'), 'speaking')
    .tanaka(tr('sl13.s4_ex'), 'speaking')
    .tanaka(tr('sl13.s4_same'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl13.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl13.s4_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl13.s4_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl13.s4_a2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl13.k_kyoto'), 'neutral')
    .tanaka(tr('sl13.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl13.c4_natural'), 'sl13_p4_natural')
    .choice(tr('sl13.c4_formal'), 'sl13_p4_formal')
    .choice(tr('sl13.c4_mistake'), 'sl13_p4_mistake')
    .choice(tr('sl13.c4_own'), 'sl13_p4_own')
    .choice(tr('sl13.c4_min'), 'sl13_p4_min')
    .endMenu()
    .scene('sl13_p4_natural', 'sl13_p4_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c4_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl13.p4_nat_ken'), 'happy')
    .jump('sl13_talk')
    .scene('sl13_p4_formal', 'sl13_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl13.p4_form_mei'), 'laugh')
    .jump('sl13_talk')
    .scene('sl13_p4_mistake', 'sl13_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl13.p4_mis_tanaka'), 'neutral')
    .jump('sl13_p4_mistake2')
    .scene('sl13_p4_mistake2', 'sl13_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl13.p4_mis_relief'), 'happy')
    .jump('sl13_talk')
    .scene('sl13_p4_own', 'sl13_p4_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c4_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl13.p4_own_ken'), 'happy')
    .jump('sl13_talk')
    .scene('sl13_p4_min', 'sl13_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl13.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl13.p4_min_yuki'), 'gentle')
    .jump('sl13_talk')
    .scene('sl13_talk', 'sl13_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl13.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl13.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl13.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl13.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl13.talk_tanaka'), 'happy')
    .player(tr('sl13.talk_player'), 'neutral')
    .tanaka(tr('sl13.talk_close'), 'happy')
    .n(tr('sl13.complete'))
    .end()
    .build();
