import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson02 = SentenceLessonDefinition(
  id: 'sentence_lesson_02',
  number: 2,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl2.title',
  subtitleKey: 'sl2.subtitle',
  descriptionKey: 'sl2.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl2.pattern.1',
    'sl2.pattern.2',
    'sl2.pattern.3',
    'sl2.pattern.4',
  ],
  storyFactory: getSentenceLesson02,
);

StoryData getSentenceLesson02() => dialogue()
    .story(2, tr('sl2.title'), tr('sl2.subtitle'))
    .description(tr('sl2.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('sl2_cafe', 'sl2_cafe')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('afternoon')
    .titleCard(tr('sl2.title'), tr('sl2.subtitle'), 2500)
    .n(tr('sl2.setup'))
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.y_welcome'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl2.t_intro'), 'happy')
    .tanaka(tr('sl2.s1_kore'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl2.s1_sore'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl2.s1_no'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('sl2.s1_are'), 'happy')
    .hide('mei')
    .tanaka(tr('sl2.s1_break'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl2.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl2.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl2.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl2.s1_a2'), 'speaking')
    .tanaka(tr('sl2.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl2.c1_natural'), 'sl2_p1_natural')
    .choice(tr('sl2.c1_formal'), 'sl2_p1_formal')
    .choice(tr('sl2.c1_mistake'), 'sl2_p1_mistake')
    .choice(tr('sl2.c1_own'), 'sl2_p1_own')
    .choice(tr('sl2.c1_min'), 'sl2_p1_min')
    .endMenu()
    .scene('sl2_p1_natural', 'sl2_p1_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c1_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl2.p1_nat_ken'), 'happy')
    .jump('sl2_after_p1')
    .scene('sl2_p1_formal', 'sl2_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c1_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl2.p1_form_yuki'), 'laugh')
    .jump('sl2_after_p1')
    .scene('sl2_p1_mistake', 'sl2_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c1_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl2.p1_mis_mei'), 'surprised')
    .jump('sl2_p1_mistake2')
    .scene('sl2_p1_mistake2', 'sl2_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.p1_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl2.p1_mis_relief'), 'happy')
    .jump('sl2_after_p1')
    .scene('sl2_p1_own', 'sl2_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl2.p1_own_ken'), 'happy')
    .jump('sl2_after_p1')
    .scene('sl2_p1_min', 'sl2_p1_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c1_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl2.p1_min_tanaka'), 'happy')
    .jump('sl2_after_p1')
    .scene('sl2_after_p1', 'sl2_after_p1')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl2.s2_ken'), 'happy')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl2.s2_intro'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl2.s2_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl2.s2_a'), 'speaking')
    .tanaka(tr('sl2.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl2.c2_natural'), 'sl2_p2_natural')
    .choice(tr('sl2.c2_formal'), 'sl2_p2_formal')
    .choice(tr('sl2.c2_mistake'), 'sl2_p2_mistake')
    .choice(tr('sl2.c2_own'), 'sl2_p2_own')
    .choice(tr('sl2.c2_min'), 'sl2_p2_min')
    .endMenu()
    .scene('sl2_p2_natural', 'sl2_p2_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c2_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl2.p2_nat_ken'), 'happy')
    .jump('sl2_after_p2')
    .scene('sl2_p2_formal', 'sl2_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl2.p2_form_ken'), 'laugh')
    .jump('sl2_after_p2')
    .scene('sl2_p2_mistake', 'sl2_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c2_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl2.p2_mis_yuki'), 'neutral')
    .jump('sl2_p2_mistake2')
    .scene('sl2_p2_mistake2', 'sl2_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.p2_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.p2_mis_relief'), 'happy')
    .jump('sl2_after_p2')
    .scene('sl2_p2_own', 'sl2_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl2.p2_own_ken'), 'happy')
    .jump('sl2_after_p2')
    .scene('sl2_p2_min', 'sl2_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl2.p2_min_tanaka'), 'happy')
    .jump('sl2_after_p2')
    .scene('sl2_after_p2', 'sl2_after_p2')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('sl2.dish'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl2.s3_intro'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl2.s3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl2.s3_a'), 'speaking')
    .tanaka(tr('sl2.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl2.c3_natural'), 'sl2_p3_natural')
    .choice(tr('sl2.c3_formal'), 'sl2_p3_formal')
    .choice(tr('sl2.c3_mistake'), 'sl2_p3_mistake')
    .choice(tr('sl2.c3_own'), 'sl2_p3_own')
    .choice(tr('sl2.c3_min'), 'sl2_p3_min')
    .endMenu()
    .scene('sl2_p3_natural', 'sl2_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.p3_nat_yuki'), 'happy')
    .jump('sl2_after_p3')
    .scene('sl2_p3_formal', 'sl2_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl2.p3_form_yuki'), 'laugh')
    .jump('sl2_after_p3')
    .scene('sl2_p3_mistake', 'sl2_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c3_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl2.p3_mis_ken'), 'surprised')
    .jump('sl2_p3_mistake2')
    .scene('sl2_p3_mistake2', 'sl2_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.p3_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.p3_mis_relief'), 'happy')
    .jump('sl2_after_p3')
    .scene('sl2_p3_own', 'sl2_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.p3_own_yuki'), 'happy')
    .jump('sl2_after_p3')
    .scene('sl2_p3_min', 'sl2_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl2.p3_min_mei'), 'happy')
    .jump('sl2_after_p3')
    .scene('sl2_after_p3', 'sl2_after_p3')
    .hide('ken')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl2.s4_yuki'), 'neutral')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl2.s4_intro'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl2.s4_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl2.s4_a'), 'speaking')
    .tanaka(tr('sl2.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl2.c4_natural'), 'sl2_p4_natural')
    .choice(tr('sl2.c4_formal'), 'sl2_p4_formal')
    .choice(tr('sl2.c4_mistake'), 'sl2_p4_mistake')
    .choice(tr('sl2.c4_own'), 'sl2_p4_own')
    .choice(tr('sl2.c4_min'), 'sl2_p4_min')
    .endMenu()
    .scene('sl2_p4_natural', 'sl2_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c4_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.p4_nat_yuki'), 'happy')
    .jump('sl2_talk')
    .scene('sl2_p4_formal', 'sl2_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl2.p4_form_ken'), 'laugh')
    .jump('sl2_talk')
    .scene('sl2_p4_mistake', 'sl2_p4_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c4_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl2.p4_mis_mei'), 'surprised')
    .jump('sl2_p4_mistake2')
    .scene('sl2_p4_mistake2', 'sl2_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.p4_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.p4_mis_relief'), 'happy')
    .jump('sl2_talk')
    .scene('sl2_p4_own', 'sl2_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c4_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.p4_own_yuki'), 'happy')
    .jump('sl2_talk')
    .scene('sl2_p4_min', 'sl2_p4_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl2.c4_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl2.p4_min_tanaka'), 'happy')
    .jump('sl2_talk')
    .scene('sl2_talk', 'sl2_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl2.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl2.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl2.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl2.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl2.talk_tanaka'), 'happy')
    .player(tr('sl2.talk_player'), 'neutral')
    .tanaka(tr('sl2.talk_close'), 'happy')
    .n(tr('sl2.complete'))
    .end()
    .build();
