import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson11 = SentenceLessonDefinition(
  id: 'sentence_lesson_11',
  number: 11,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl11.title',
  subtitleKey: 'sl11.subtitle',
  descriptionKey: 'sl11.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl11.pattern.1',
    'sl11.pattern.2',
    'sl11.pattern.3',
    'sl11.pattern.4',
  ],
  storyFactory: getSentenceLesson11,
);

StoryData getSentenceLesson11() => dialogue()
    .story(11, tr('sl11.title'), tr('sl11.subtitle'))
    .description(tr('sl11.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl11_train', 'sl11_train')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .train('afternoon')
    .titleCard(tr('sl11.title'), tr('sl11.subtitle'), 2500)
    .n(tr('sl11.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl11.t_intro'), 'happy')
    .tanaka(tr('sl11.s1_intro'), 'speaking')
    .tanaka(tr('sl11.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl11.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl11.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl11.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl11.s1_a2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl11.y_ask'), 'neutral')
    .tanaka(tr('sl11.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl11.c1_natural'), 'sl11_p1_natural')
    .choice(tr('sl11.c1_formal'), 'sl11_p1_formal')
    .choice(tr('sl11.c1_mistake'), 'sl11_p1_mistake')
    .choice(tr('sl11.c1_own'), 'sl11_p1_own')
    .choice(tr('sl11.c1_min'), 'sl11_p1_min')
    .endMenu()
    .scene('sl11_p1_natural', 'sl11_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl11.p1_nat_yuki'), 'happy')
    .jump('sl11_after_p1')
    .scene('sl11_p1_formal', 'sl11_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl11.p1_form_ken'), 'laugh')
    .jump('sl11_after_p1')
    .scene('sl11_p1_mistake', 'sl11_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl11.p1_mis_tanaka'), 'neutral')
    .jump('sl11_p1_mistake2')
    .scene('sl11_p1_mistake2', 'sl11_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl11.p1_mis_relief'), 'happy')
    .jump('sl11_after_p1')
    .scene('sl11_p1_own', 'sl11_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl11.p1_own_yuki'), 'happy')
    .jump('sl11_after_p1')
    .scene('sl11_p1_min', 'sl11_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl11.p1_min_mei'), 'happy')
    .jump('sl11_after_p1')
    .scene('sl11_after_p1', 'sl11_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .park('afternoon')
    .n(tr('sl11.temple'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl11.s2_intro'), 'speaking')
    .tanaka(tr('sl11.s2_ex'), 'speaking')
    .tanaka(tr('sl11.s2_more'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl11.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl11.s2_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl11.s2_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl11.s2_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl11.m_ask'), 'neutral')
    .tanaka(tr('sl11.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl11.c2_natural'), 'sl11_p2_natural')
    .choice(tr('sl11.c2_formal'), 'sl11_p2_formal')
    .choice(tr('sl11.c2_mistake'), 'sl11_p2_mistake')
    .choice(tr('sl11.c2_own'), 'sl11_p2_own')
    .choice(tr('sl11.c2_min'), 'sl11_p2_min')
    .endMenu()
    .scene('sl11_p2_natural', 'sl11_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl11.p2_nat_mei'), 'happy')
    .jump('sl11_after_p2')
    .scene('sl11_p2_formal', 'sl11_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl11.p2_form_yuki'), 'laugh')
    .jump('sl11_after_p2')
    .scene('sl11_p2_mistake', 'sl11_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c2_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl11.p2_mis_ken'), 'neutral')
    .jump('sl11_p2_mistake2')
    .scene('sl11_p2_mistake2', 'sl11_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl11.p2_mis_relief'), 'happy')
    .jump('sl11_after_p2')
    .scene('sl11_p2_own', 'sl11_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl11.p2_own_mei'), 'happy')
    .jump('sl11_after_p2')
    .scene('sl11_p2_min', 'sl11_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl11.p2_min_tanaka'), 'happy')
    .jump('sl11_after_p2')
    .scene('sl11_after_p2', 'sl11_after_p2')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl11.s3_intro'), 'speaking')
    .tanaka(tr('sl11.s3_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl11.s3_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl11.s3_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl11.s3_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl11.s3_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl11.m_lunch'), 'neutral')
    .tanaka(tr('sl11.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl11.c3_natural'), 'sl11_p3_natural')
    .choice(tr('sl11.c3_formal'), 'sl11_p3_formal')
    .choice(tr('sl11.c3_mistake'), 'sl11_p3_mistake')
    .choice(tr('sl11.c3_own'), 'sl11_p3_own')
    .choice(tr('sl11.c3_min'), 'sl11_p3_min')
    .endMenu()
    .scene('sl11_p3_natural', 'sl11_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl11.p3_nat_mei'), 'happy')
    .jump('sl11_after_p3')
    .scene('sl11_p3_formal', 'sl11_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl11.p3_form_ken'), 'laugh')
    .jump('sl11_after_p3')
    .scene('sl11_p3_mistake', 'sl11_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl11.p3_mis_tanaka'), 'neutral')
    .jump('sl11_p3_mistake2')
    .scene('sl11_p3_mistake2', 'sl11_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.p3_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl11.p3_mis_relief'), 'happy')
    .jump('sl11_after_p3')
    .scene('sl11_p3_own', 'sl11_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c3_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl11.p3_own_mei'), 'happy')
    .jump('sl11_after_p3')
    .scene('sl11_p3_min', 'sl11_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl11.p3_min_yuki'), 'gentle')
    .jump('sl11_after_p3')
    .scene('sl11_after_p3', 'sl11_after_p3')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl11.s4_intro'), 'speaking')
    .tanaka(tr('sl11.s4_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl11.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl11.s4_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl11.s4_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl11.s4_a2'), 'speaking')
    .tanaka(tr('sl11.tanaka_ask'), 'happy')
    .tanaka(tr('sl11.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl11.c4_natural'), 'sl11_p4_natural')
    .choice(tr('sl11.c4_formal'), 'sl11_p4_formal')
    .choice(tr('sl11.c4_mistake'), 'sl11_p4_mistake')
    .choice(tr('sl11.c4_own'), 'sl11_p4_own')
    .choice(tr('sl11.c4_min'), 'sl11_p4_min')
    .endMenu()
    .scene('sl11_p4_natural', 'sl11_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl11.p4_nat_tanaka'), 'happy')
    .jump('sl11_talk')
    .scene('sl11_p4_formal', 'sl11_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl11.p4_form_mei'), 'laugh')
    .jump('sl11_talk')
    .scene('sl11_p4_mistake', 'sl11_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c4_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl11.p4_mis_ken'), 'neutral')
    .jump('sl11_p4_mistake2')
    .scene('sl11_p4_mistake2', 'sl11_p4_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.p4_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl11.p4_mis_relief'), 'happy')
    .jump('sl11_talk')
    .scene('sl11_p4_own', 'sl11_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c4_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl11.p4_own_yuki'), 'happy')
    .jump('sl11_talk')
    .scene('sl11_p4_min', 'sl11_p4_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl11.c4_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl11.p4_min_tanaka'), 'happy')
    .jump('sl11_talk')
    .scene('sl11_talk', 'sl11_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl11.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl11.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl11.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl11.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl11.talk_tanaka'), 'happy')
    .player(tr('sl11.talk_player'), 'neutral')
    .tanaka(tr('sl11.talk_close'), 'happy')
    .n(tr('sl11.complete'))
    .end()
    .build();
