import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson16 = SentenceLessonDefinition(
  id: 'sentence_lesson_16',
  number: 16,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl16.title',
  subtitleKey: 'sl16.subtitle',
  descriptionKey: 'sl16.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl16.pattern.1',
    'sl16.pattern.2',
    'sl16.pattern.3',
    'sl16.pattern.4',
  ],
  storyFactory: getSentenceLesson16,
);

StoryData getSentenceLesson16() => dialogue()
    .story(16, tr('sl16.title'), tr('sl16.subtitle'))
    .description(tr('sl16.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl16_class', 'sl16_class')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('afternoon')
    .titleCard(tr('sl16.title'), tr('sl16.subtitle'), 2500)
    .n(tr('sl16.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.t_intro'), 'happy')
    .tanaka(tr('sl16.s1_intro'), 'speaking')
    .tanaka(tr('sl16.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl16.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl16.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl16.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl16.s1_a2'), 'speaking')
    .tanaka(tr('sl16.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl16.c1_natural'), 'sl16_p1_natural')
    .choice(tr('sl16.c1_formal'), 'sl16_p1_formal')
    .choice(tr('sl16.c1_mistake'), 'sl16_p1_mistake')
    .choice(tr('sl16.c1_own'), 'sl16_p1_own')
    .choice(tr('sl16.c1_min'), 'sl16_p1_min')
    .endMenu()
    .scene('sl16_p1_natural', 'sl16_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.p1_nat_tanaka'), 'happy')
    .jump('sl16_after_p1')
    .scene('sl16_p1_formal', 'sl16_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl16.p1_form_ken'), 'laugh')
    .jump('sl16_after_p1')
    .scene('sl16_p1_mistake', 'sl16_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl16.p1_mis_tanaka'), 'neutral')
    .jump('sl16_p1_mistake2')
    .scene('sl16_p1_mistake2', 'sl16_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.p1_mis_relief'), 'happy')
    .jump('sl16_after_p1')
    .scene('sl16_p1_own', 'sl16_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.p1_own_tanaka'), 'happy')
    .jump('sl16_after_p1')
    .scene('sl16_p1_min', 'sl16_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl16.p1_min_yuki'), 'gentle')
    .jump('sl16_after_p1')
    .scene('sl16_after_p1', 'sl16_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl16.s2_intro'), 'speaking')
    .tanaka(tr('sl16.s2_ans'), 'speaking')
    .tanaka(tr('sl16.s2_neg'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl16.s2_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl16.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl16.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl16.s2_a2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl16.k_ask'), 'neutral')
    .tanaka(tr('sl16.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl16.c2_natural'), 'sl16_p2_natural')
    .choice(tr('sl16.c2_formal'), 'sl16_p2_formal')
    .choice(tr('sl16.c2_mistake'), 'sl16_p2_mistake')
    .choice(tr('sl16.c2_own'), 'sl16_p2_own')
    .choice(tr('sl16.c2_min'), 'sl16_p2_min')
    .endMenu()
    .scene('sl16_p2_natural', 'sl16_p2_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c2_natural'), 'happy')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl16.p2_nat_ken'), 'surprised')
    .jump('sl16_after_p2')
    .scene('sl16_p2_formal', 'sl16_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl16.p2_form_mei'), 'laugh')
    .jump('sl16_after_p2')
    .scene('sl16_p2_mistake', 'sl16_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl16.p2_mis_tanaka'), 'neutral')
    .jump('sl16_p2_mistake2')
    .scene('sl16_p2_mistake2', 'sl16_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.p2_mis_relief'), 'happy')
    .jump('sl16_after_p2')
    .scene('sl16_p2_own', 'sl16_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl16.p2_own_ken'), 'happy')
    .jump('sl16_after_p2')
    .scene('sl16_p2_min', 'sl16_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl16.p2_min_yuki'), 'gentle')
    .jump('sl16_after_p2')
    .scene('sl16_after_p2', 'sl16_after_p2')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl16.s3_intro'), 'speaking')
    .tanaka(tr('sl16.s3_ex'), 'speaking')
    .tanaka(tr('sl16.s3_te'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl16.s3_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl16.s3_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl16.s3_q2'), 'neutral')
    .tanaka(tr('sl16.s3_a2'), 'speaking')
    .yuki(tr('sl16.y_say'), 'happy')
    .tanaka(tr('sl16.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl16.c3_natural'), 'sl16_p3_natural')
    .choice(tr('sl16.c3_formal'), 'sl16_p3_formal')
    .choice(tr('sl16.c3_mistake'), 'sl16_p3_mistake')
    .choice(tr('sl16.c3_own'), 'sl16_p3_own')
    .choice(tr('sl16.c3_min'), 'sl16_p3_min')
    .endMenu()
    .scene('sl16_p3_natural', 'sl16_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c3_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl16.p3_nat_ken'), 'happy')
    .jump('sl16_after_p3')
    .scene('sl16_p3_formal', 'sl16_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl16.p3_form_mei'), 'laugh')
    .jump('sl16_after_p3')
    .scene('sl16_p3_mistake', 'sl16_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl16.p3_mis_tanaka'), 'neutral')
    .jump('sl16_p3_mistake2')
    .scene('sl16_p3_mistake2', 'sl16_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.p3_mis_relief'), 'happy')
    .jump('sl16_after_p3')
    .scene('sl16_p3_own', 'sl16_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl16.p3_own_ken'), 'happy')
    .jump('sl16_after_p3')
    .scene('sl16_p3_min', 'sl16_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl16.p3_min_mei'), 'happy')
    .jump('sl16_after_p3')
    .scene('sl16_after_p3', 'sl16_after_p3')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl16.s4_intro'), 'speaking')
    .tanaka(tr('sl16.s4_ex'), 'speaking')
    .tanaka(tr('sl16.s4_form'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl16.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl16.s4_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl16.s4_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl16.s4_a2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl16.k_weather'), 'neutral')
    .tanaka(tr('sl16.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl16.c4_natural'), 'sl16_p4_natural')
    .choice(tr('sl16.c4_formal'), 'sl16_p4_formal')
    .choice(tr('sl16.c4_mistake'), 'sl16_p4_mistake')
    .choice(tr('sl16.c4_own'), 'sl16_p4_own')
    .choice(tr('sl16.c4_min'), 'sl16_p4_min')
    .endMenu()
    .scene('sl16_p4_natural', 'sl16_p4_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c4_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl16.p4_nat_ken'), 'happy')
    .jump('sl16_talk')
    .scene('sl16_p4_formal', 'sl16_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c4_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl16.p4_form_yuki'), 'laugh')
    .jump('sl16_talk')
    .scene('sl16_p4_mistake', 'sl16_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl16.p4_mis_tanaka'), 'neutral')
    .jump('sl16_p4_mistake2')
    .scene('sl16_p4_mistake2', 'sl16_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.p4_mis_relief'), 'happy')
    .jump('sl16_talk')
    .scene('sl16_p4_own', 'sl16_p4_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c4_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl16.p4_own_ken'), 'happy')
    .jump('sl16_talk')
    .scene('sl16_p4_min', 'sl16_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl16.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl16.p4_min_mei'), 'happy')
    .jump('sl16_talk')
    .scene('sl16_talk', 'sl16_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl16.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl16.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl16.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl16.talk_tanaka'), 'happy')
    .player(tr('sl16.talk_player'), 'neutral')
    .tanaka(tr('sl16.talk_close'), 'happy')
    .n(tr('sl16.complete'))
    .end()
    .build();
