import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson07 = SentenceLessonDefinition(
  id: 'sentence_lesson_07',
  number: 7,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl7.title',
  subtitleKey: 'sl7.subtitle',
  descriptionKey: 'sl7.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl7.pattern.1',
    'sl7.pattern.2',
    'sl7.pattern.3',
    'sl7.pattern.4',
  ],
  storyFactory: getSentenceLesson07,
);

StoryData getSentenceLesson07() => dialogue()
    .story(7, tr('sl7.title'), tr('sl7.subtitle'))
    .description(tr('sl7.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5')
    .scene('sl7_class', 'sl7_class')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('morning')
    .titleCard(tr('sl7.title'), tr('sl7.subtitle'), 2500)
    .n(tr('sl7.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.t_intro'), 'happy')
    .tanaka(tr('sl7.s1_intro'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('sl7.s1_ken'), 'happy')
    .show('mei', 'right', 'concerned')
    .mei(tr('sl7.s1_mei'), 'concerned')
    .hide('mei')
    .tanaka(tr('sl7.s1_neg'), 'speaking')
    .ken(tr('sl7.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl7.s1_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl7.s1_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl7.s1_a2'), 'speaking')
    .tanaka(tr('sl7.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl7.c1_natural'), 'sl7_p1_natural')
    .choice(tr('sl7.c1_formal'), 'sl7_p1_formal')
    .choice(tr('sl7.c1_mistake'), 'sl7_p1_mistake')
    .choice(tr('sl7.c1_own'), 'sl7_p1_own')
    .choice(tr('sl7.c1_min'), 'sl7_p1_min')
    .endMenu()
    .scene('sl7_p1_natural', 'sl7_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.p1_nat_tanaka'), 'happy')
    .jump('sl7_after_p1')
    .scene('sl7_p1_formal', 'sl7_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl7.p1_form_mei'), 'laugh')
    .jump('sl7_after_p1')
    .scene('sl7_p1_mistake', 'sl7_p1_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c1_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl7.p1_mis_ken'), 'neutral')
    .jump('sl7_p1_mistake2')
    .scene('sl7_p1_mistake2', 'sl7_p1_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.p1_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl7.p1_mis_relief'), 'happy')
    .jump('sl7_after_p1')
    .scene('sl7_p1_own', 'sl7_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl7.p1_own_yuki'), 'happy')
    .jump('sl7_after_p1')
    .scene('sl7_p1_min', 'sl7_p1_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c1_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.p1_min_tanaka'), 'happy')
    .jump('sl7_after_p1')
    .scene('sl7_after_p1', 'sl7_after_p1')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl7.s2_intro'), 'speaking')
    .tanaka(tr('sl7.s2_ex'), 'speaking')
    .tanaka(tr('sl7.s2_break'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl7.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl7.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl7.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl7.s2_a2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl7.ask_price'), 'neutral')
    .tanaka(tr('sl7.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl7.c2_natural'), 'sl7_p2_natural')
    .choice(tr('sl7.c2_formal'), 'sl7_p2_formal')
    .choice(tr('sl7.c2_mistake'), 'sl7_p2_mistake')
    .choice(tr('sl7.c2_own'), 'sl7_p2_own')
    .choice(tr('sl7.c2_min'), 'sl7_p2_min')
    .endMenu()
    .scene('sl7_p2_natural', 'sl7_p2_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c2_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl7.p2_nat_ken'), 'happy')
    .jump('sl7_after_p2')
    .scene('sl7_p2_formal', 'sl7_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl7.p2_form_yuki'), 'laugh')
    .jump('sl7_after_p2')
    .scene('sl7_p2_mistake', 'sl7_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c2_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl7.p2_mis_mei'), 'surprised')
    .jump('sl7_p2_mistake2')
    .scene('sl7_p2_mistake2', 'sl7_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.p2_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl7.p2_mis_relief'), 'happy')
    .jump('sl7_after_p2')
    .scene('sl7_p2_own', 'sl7_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl7.p2_own_ken'), 'happy')
    .jump('sl7_after_p2')
    .scene('sl7_p2_min', 'sl7_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.p2_min_tanaka'), 'happy')
    .jump('sl7_after_p2')
    .scene('sl7_after_p2', 'sl7_after_p2')
    .hide('ken')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl7.s3_intro'), 'speaking')
    .tanaka(tr('sl7.s3_ex'), 'speaking')
    .tanaka(tr('sl7.s3_break'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl7.s3_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl7.s3_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl7.s3_ask'), 'neutral')
    .tanaka(tr('sl7.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl7.c3_natural'), 'sl7_p3_natural')
    .choice(tr('sl7.c3_formal'), 'sl7_p3_formal')
    .choice(tr('sl7.c3_mistake'), 'sl7_p3_mistake')
    .choice(tr('sl7.c3_own'), 'sl7_p3_own')
    .choice(tr('sl7.c3_min'), 'sl7_p3_min')
    .endMenu()
    .scene('sl7_p3_natural', 'sl7_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl7.p3_nat_mei'), 'happy')
    .jump('sl7_after_p3')
    .scene('sl7_p3_formal', 'sl7_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl7.p3_form_ken'), 'laugh')
    .jump('sl7_after_p3')
    .scene('sl7_p3_mistake', 'sl7_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl7.p3_mis_tanaka'), 'neutral')
    .jump('sl7_p3_mistake2')
    .scene('sl7_p3_mistake2', 'sl7_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.p3_mis_relief'), 'happy')
    .jump('sl7_after_p3')
    .scene('sl7_p3_own', 'sl7_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c3_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl7.p3_own_mei'), 'happy')
    .jump('sl7_after_p3')
    .scene('sl7_p3_min', 'sl7_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl7.p3_min_yuki'), 'gentle')
    .jump('sl7_after_p3')
    .scene('sl7_after_p3', 'sl7_after_p3')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl7.s4_intro'), 'speaking')
    .tanaka(tr('sl7.s4_na'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl7.s4_q1'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl7.s4_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl7.s4_q2'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl7.s4_a2'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl7.ask_fest'), 'happy')
    .tanaka(tr('sl7.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl7.c4_natural'), 'sl7_p4_natural')
    .choice(tr('sl7.c4_formal'), 'sl7_p4_formal')
    .choice(tr('sl7.c4_mistake'), 'sl7_p4_mistake')
    .choice(tr('sl7.c4_own'), 'sl7_p4_own')
    .choice(tr('sl7.c4_min'), 'sl7_p4_min')
    .endMenu()
    .scene('sl7_p4_natural', 'sl7_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c4_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl7.p4_nat_yuki'), 'happy')
    .jump('sl7_talk')
    .scene('sl7_p4_formal', 'sl7_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl7.p4_form_mei'), 'laugh')
    .jump('sl7_talk')
    .scene('sl7_p4_mistake', 'sl7_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c4_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl7.p4_mis_ken'), 'neutral')
    .jump('sl7_p4_mistake2')
    .scene('sl7_p4_mistake2', 'sl7_p4_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.p4_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl7.p4_mis_relief'), 'happy')
    .jump('sl7_talk')
    .scene('sl7_p4_own', 'sl7_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c4_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl7.p4_own_yuki'), 'happy')
    .jump('sl7_talk')
    .scene('sl7_p4_min', 'sl7_p4_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl7.c4_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.p4_min_tanaka'), 'happy')
    .jump('sl7_talk')
    .scene('sl7_talk', 'sl7_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl7.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl7.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl7.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl7.talk_tanaka'), 'happy')
    .player(tr('sl7.talk_player'), 'neutral')
    .tanaka(tr('sl7.talk_close'), 'happy')
    .n(tr('sl7.complete'))
    .end()
    .build();
