import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson14 = SentenceLessonDefinition(
  id: 'sentence_lesson_14',
  number: 14,
  level: SentenceLessonLevel.elementary,
  titleKey: 'sl14.title',
  subtitleKey: 'sl14.subtitle',
  descriptionKey: 'sl14.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  patternKeys: <String>[
    'sl14.pattern.1',
    'sl14.pattern.2',
    'sl14.pattern.3',
    'sl14.pattern.4',
  ],
  storyFactory: getSentenceLesson14,
);

StoryData getSentenceLesson14() => dialogue()
    .story(14, tr('sl14.title'), tr('sl14.subtitle'))
    .description(tr('sl14.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5-N4')
    .scene('sl14_class', 'sl14_class')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('morning')
    .titleCard(tr('sl14.title'), tr('sl14.subtitle'), 2500)
    .n(tr('sl14.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.t_intro'), 'happy')
    .tanaka(tr('sl14.s1_intro'), 'speaking')
    .tanaka(tr('sl14.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl14.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl14.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl14.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl14.s1_a2'), 'speaking')
    .tanaka(tr('sl14.tanaka_ask'), 'neutral')
    .tanaka(tr('sl14.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl14.c1_natural'), 'sl14_p1_natural')
    .choice(tr('sl14.c1_formal'), 'sl14_p1_formal')
    .choice(tr('sl14.c1_mistake'), 'sl14_p1_mistake')
    .choice(tr('sl14.c1_own'), 'sl14_p1_own')
    .choice(tr('sl14.c1_min'), 'sl14_p1_min')
    .endMenu()
    .scene('sl14_p1_natural', 'sl14_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.p1_nat_tanaka'), 'happy')
    .jump('sl14_after_p1')
    .scene('sl14_p1_formal', 'sl14_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl14.p1_form_ken'), 'laugh')
    .jump('sl14_after_p1')
    .scene('sl14_p1_mistake', 'sl14_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl14.p1_mis_tanaka'), 'neutral')
    .jump('sl14_p1_mistake2')
    .scene('sl14_p1_mistake2', 'sl14_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.p1_mis_relief'), 'happy')
    .jump('sl14_after_p1')
    .scene('sl14_p1_own', 'sl14_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.p1_own_tanaka'), 'happy')
    .jump('sl14_after_p1')
    .scene('sl14_p1_min', 'sl14_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl14.p1_min_yuki'), 'gentle')
    .jump('sl14_after_p1')
    .scene('sl14_after_p1', 'sl14_after_p1')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl14.s2_intro'), 'speaking')
    .tanaka(tr('sl14.s2_form'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl14.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl14.s2_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl14.s2_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl14.s2_a2'), 'speaking')
    .tanaka(tr('sl14.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl14.c2_natural'), 'sl14_p2_natural')
    .choice(tr('sl14.c2_formal'), 'sl14_p2_formal')
    .choice(tr('sl14.c2_mistake'), 'sl14_p2_mistake')
    .choice(tr('sl14.c2_own'), 'sl14_p2_own')
    .choice(tr('sl14.c2_min'), 'sl14_p2_min')
    .endMenu()
    .scene('sl14_p2_natural', 'sl14_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.p2_nat_tanaka'), 'happy')
    .jump('sl14_after_p2')
    .scene('sl14_p2_formal', 'sl14_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl14.p2_form_mei'), 'laugh')
    .jump('sl14_after_p2')
    .scene('sl14_p2_mistake', 'sl14_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c2_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl14.p2_mis_ken'), 'neutral')
    .jump('sl14_p2_mistake2')
    .scene('sl14_p2_mistake2', 'sl14_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl14.p2_mis_relief'), 'happy')
    .jump('sl14_after_p2')
    .scene('sl14_p2_own', 'sl14_p2_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c2_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.p2_own_tanaka'), 'happy')
    .jump('sl14_after_p2')
    .scene('sl14_p2_min', 'sl14_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl14.p2_min_yuki'), 'gentle')
    .jump('sl14_after_p2')
    .scene('sl14_after_p2', 'sl14_after_p2')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl14.s3_intro'), 'speaking')
    .tanaka(tr('sl14.s3_ex'), 'speaking')
    .tanaka(tr('sl14.s3_form'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl14.s3_q1'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl14.s3_a1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl14.s3_q2'), 'neutral')
    .tanaka(tr('sl14.s3_a2'), 'speaking')
    .ken(tr('sl14.k_invite'), 'happy')
    .tanaka(tr('sl14.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl14.c3_natural'), 'sl14_p3_natural')
    .choice(tr('sl14.c3_formal'), 'sl14_p3_formal')
    .choice(tr('sl14.c3_mistake'), 'sl14_p3_mistake')
    .choice(tr('sl14.c3_own'), 'sl14_p3_own')
    .choice(tr('sl14.c3_min'), 'sl14_p3_min')
    .endMenu()
    .scene('sl14_p3_natural', 'sl14_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c3_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl14.p3_nat_ken'), 'happy')
    .jump('sl14_after_p3')
    .scene('sl14_p3_formal', 'sl14_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl14.p3_form_yuki'), 'laugh')
    .jump('sl14_after_p3')
    .scene('sl14_p3_mistake', 'sl14_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl14.p3_mis_tanaka'), 'neutral')
    .jump('sl14_p3_mistake2')
    .scene('sl14_p3_mistake2', 'sl14_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.p3_mis_relief'), 'happy')
    .jump('sl14_after_p3')
    .scene('sl14_p3_own', 'sl14_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl14.p3_own_ken'), 'happy')
    .jump('sl14_after_p3')
    .scene('sl14_p3_min', 'sl14_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl14.p3_min_mei'), 'happy')
    .jump('sl14_after_p3')
    .scene('sl14_after_p3', 'sl14_after_p3')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .bg('university_building', 'afternoon')
    .n(tr('sl14.hall'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl14.s4_intro'), 'speaking')
    .tanaka(tr('sl14.s4_ex'), 'speaking')
    .tanaka(tr('sl14.s4_kureru'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl14.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl14.s4_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl14.s4_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl14.s4_a2'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('sl14.m_wait'), 'happy')
    .tanaka(tr('sl14.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl14.c4_natural'), 'sl14_p4_natural')
    .choice(tr('sl14.c4_formal'), 'sl14_p4_formal')
    .choice(tr('sl14.c4_mistake'), 'sl14_p4_mistake')
    .choice(tr('sl14.c4_own'), 'sl14_p4_own')
    .choice(tr('sl14.c4_min'), 'sl14_p4_min')
    .endMenu()
    .scene('sl14_p4_natural', 'sl14_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c4_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl14.p4_nat_mei'), 'happy')
    .jump('sl14_talk')
    .scene('sl14_p4_formal', 'sl14_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl14.p4_form_ken'), 'laugh')
    .jump('sl14_talk')
    .scene('sl14_p4_mistake', 'sl14_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl14.p4_mis_tanaka'), 'neutral')
    .jump('sl14_p4_mistake2')
    .scene('sl14_p4_mistake2', 'sl14_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.p4_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl14.p4_mis_relief'), 'happy')
    .jump('sl14_talk')
    .scene('sl14_p4_own', 'sl14_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c4_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl14.p4_own_mei'), 'happy')
    .jump('sl14_talk')
    .scene('sl14_p4_min', 'sl14_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl14.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl14.p4_min_yuki'), 'gentle')
    .jump('sl14_talk')
    .scene('sl14_talk', 'sl14_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl14.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl14.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl14.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl14.talk_tanaka'), 'happy')
    .player(tr('sl14.talk_player'), 'neutral')
    .tanaka(tr('sl14.talk_close'), 'happy')
    .n(tr('sl14.complete'))
    .end()
    .build();
