import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson08 = SentenceLessonDefinition(
  id: 'sentence_lesson_08',
  number: 8,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl8.title',
  subtitleKey: 'sl8.subtitle',
  descriptionKey: 'sl8.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl8.pattern.1',
    'sl8.pattern.2',
    'sl8.pattern.3',
    'sl8.pattern.4',
  ],
  storyFactory: getSentenceLesson08,
);

StoryData getSentenceLesson08() => dialogue()
    .story(8, tr('sl8.title'), tr('sl8.subtitle'))
    .description(tr('sl8.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5')
    .scene('sl8_class', 'sl8_class')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('afternoon')
    .titleCard(tr('sl8.title'), tr('sl8.subtitle'), 2500)
    .n(tr('sl8.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.t_intro'), 'happy')
    .tanaka(tr('sl8.s1_intro'), 'speaking')
    .tanaka(tr('sl8.s1_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl8.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl8.s1_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl8.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl8.s1_a2'), 'speaking')
    .tanaka(tr('sl8.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl8.c1_natural'), 'sl8_p1_natural')
    .choice(tr('sl8.c1_formal'), 'sl8_p1_formal')
    .choice(tr('sl8.c1_mistake'), 'sl8_p1_mistake')
    .choice(tr('sl8.c1_own'), 'sl8_p1_own')
    .choice(tr('sl8.c1_min'), 'sl8_p1_min')
    .endMenu()
    .scene('sl8_p1_natural', 'sl8_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.p1_nat_tanaka'), 'happy')
    .jump('sl8_after_p1')
    .scene('sl8_p1_formal', 'sl8_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl8.p1_form_ken'), 'laugh')
    .jump('sl8_after_p1')
    .scene('sl8_p1_mistake', 'sl8_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c1_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl8.p1_mis_mei'), 'surprised')
    .jump('sl8_p1_mistake2')
    .scene('sl8_p1_mistake2', 'sl8_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.p1_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl8.p1_mis_relief'), 'happy')
    .jump('sl8_after_p1')
    .scene('sl8_p1_own', 'sl8_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.p1_own_tanaka'), 'happy')
    .jump('sl8_after_p1')
    .scene('sl8_p1_min', 'sl8_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl8.p1_min_yuki'), 'gentle')
    .jump('sl8_after_p1')
    .scene('sl8_after_p1', 'sl8_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl8.s2_intro'), 'speaking')
    .tanaka(tr('sl8.s2_rule'), 'speaking')
    .tanaka(tr('sl8.s2_rule2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl8.s2_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl8.s2_a1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl8.s2_q2'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl8.s2_a2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl8.m_walk'), 'neutral')
    .tanaka(tr('sl8.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl8.c2_natural'), 'sl8_p2_natural')
    .choice(tr('sl8.c2_formal'), 'sl8_p2_formal')
    .choice(tr('sl8.c2_mistake'), 'sl8_p2_mistake')
    .choice(tr('sl8.c2_own'), 'sl8_p2_own')
    .choice(tr('sl8.c2_min'), 'sl8_p2_min')
    .endMenu()
    .scene('sl8_p2_natural', 'sl8_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl8.p2_nat_mei'), 'happy')
    .jump('sl8_after_p2')
    .scene('sl8_p2_formal', 'sl8_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl8.p2_form_ken'), 'laugh')
    .jump('sl8_after_p2')
    .scene('sl8_p2_mistake', 'sl8_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl8.p2_mis_tanaka'), 'neutral')
    .jump('sl8_p2_mistake2')
    .scene('sl8_p2_mistake2', 'sl8_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.p2_mis_relief'), 'happy')
    .jump('sl8_after_p2')
    .scene('sl8_p2_own', 'sl8_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('sl8.p2_own_mei'), 'happy')
    .jump('sl8_after_p2')
    .scene('sl8_p2_min', 'sl8_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl8.p2_min_yuki'), 'gentle')
    .jump('sl8_after_p2')
    .scene('sl8_after_p2', 'sl8_after_p2')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('sl8.door'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl8.s3_intro'), 'speaking')
    .tanaka(tr('sl8.s3_rule'), 'speaking')
    .tanaka(tr('sl8.s3_ex'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl8.s3_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl8.s3_a'), 'speaking')
    .tanaka(tr('sl8.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl8.c3_natural'), 'sl8_p3_natural')
    .choice(tr('sl8.c3_formal'), 'sl8_p3_formal')
    .choice(tr('sl8.c3_mistake'), 'sl8_p3_mistake')
    .choice(tr('sl8.c3_own'), 'sl8_p3_own')
    .choice(tr('sl8.c3_min'), 'sl8_p3_min')
    .endMenu()
    .scene('sl8_p3_natural', 'sl8_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c3_natural'), 'happy')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl8.p3_nat_ken'), 'surprised')
    .jump('sl8_after_p3')
    .scene('sl8_p3_formal', 'sl8_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl8.p3_form_yuki'), 'laugh')
    .jump('sl8_after_p3')
    .scene('sl8_p3_mistake', 'sl8_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl8.p3_mis_tanaka'), 'neutral')
    .jump('sl8_p3_mistake2')
    .scene('sl8_p3_mistake2', 'sl8_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.p3_mis_relief'), 'happy')
    .jump('sl8_after_p3')
    .scene('sl8_p3_own', 'sl8_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl8.p3_own_ken'), 'happy')
    .jump('sl8_after_p3')
    .scene('sl8_p3_min', 'sl8_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl8.p3_min_mei'), 'happy')
    .jump('sl8_after_p3')
    .scene('sl8_after_p3', 'sl8_after_p3')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl8.s4_intro'), 'speaking')
    .tanaka(tr('sl8.s4_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl8.s4_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl8.s4_a1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl8.s4_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl8.s4_a2'), 'speaking')
    .n(tr('sl8.station'))
    .station('afternoon')
    .tanaka(tr('sl8.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl8.c4_natural'), 'sl8_p4_natural')
    .choice(tr('sl8.c4_formal'), 'sl8_p4_formal')
    .choice(tr('sl8.c4_mistake'), 'sl8_p4_mistake')
    .choice(tr('sl8.c4_own'), 'sl8_p4_own')
    .choice(tr('sl8.c4_min'), 'sl8_p4_min')
    .endMenu()
    .scene('sl8_p4_natural', 'sl8_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c4_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl8.p4_nat_yuki'), 'happy')
    .jump('sl8_talk')
    .scene('sl8_p4_formal', 'sl8_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl8.p4_form_ken'), 'laugh')
    .jump('sl8_talk')
    .scene('sl8_p4_mistake', 'sl8_p4_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c4_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('sl8.p4_mis_mei'), 'surprised')
    .jump('sl8_p4_mistake2')
    .scene('sl8_p4_mistake2', 'sl8_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.p4_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl8.p4_mis_relief'), 'happy')
    .jump('sl8_talk')
    .scene('sl8_p4_own', 'sl8_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c4_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl8.p4_own_yuki'), 'happy')
    .jump('sl8_talk')
    .scene('sl8_p4_min', 'sl8_p4_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl8.c4_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.p4_min_tanaka'), 'happy')
    .jump('sl8_talk')
    .scene('sl8_talk', 'sl8_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl8.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl8.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl8.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl8.talk_tanaka'), 'happy')
    .player(tr('sl8.talk_player'), 'neutral')
    .tanaka(tr('sl8.talk_close'), 'happy')
    .n(tr('sl8.complete'))
    .end()
    .build();
