import '../dialogue_builder.dart';
import 'sentence_lesson.dart';

const sentenceLesson04 = SentenceLessonDefinition(
  id: 'sentence_lesson_04',
  number: 4,
  level: SentenceLessonLevel.beginner,
  titleKey: 'sl4.title',
  subtitleKey: 'sl4.subtitle',
  descriptionKey: 'sl4.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  patternKeys: <String>[
    'sl4.pattern.1',
    'sl4.pattern.2',
    'sl4.pattern.3',
    'sl4.pattern.4',
  ],
  storyFactory: getSentenceLesson04,
);

StoryData getSentenceLesson04() => dialogue()
    .story(4, tr('sl4.title'), tr('sl4.subtitle'))
    .description(tr('sl4.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('sl4_class', 'sl4_class')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('afternoon')
    .titleCard(tr('sl4.title'), tr('sl4.subtitle'), 2500)
    .n(tr('sl4.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.t_intro'), 'happy')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl4.s1_photo'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl4.s1_ans'), 'happy')
    .tanaka(tr('sl4.s1_dare'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl4.s1_q1'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl4.s1_a1'), 'speaking')
    .tanaka(tr('sl4.s1_dare_no'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl4.s1_q2'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl4.s1_a2'), 'speaking')
    .n(tr('sl4.bag'))
    .tanaka(tr('sl4.p1_prompt'), 'happy')
    .menu()
    .choice(tr('sl4.c1_natural'), 'sl4_p1_natural')
    .choice(tr('sl4.c1_formal'), 'sl4_p1_formal')
    .choice(tr('sl4.c1_mistake'), 'sl4_p1_mistake')
    .choice(tr('sl4.c1_own'), 'sl4_p1_own')
    .choice(tr('sl4.c1_min'), 'sl4_p1_min')
    .endMenu()
    .scene('sl4_p1_natural', 'sl4_p1_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c1_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl4.p1_nat_ken'), 'happy')
    .jump('sl4_after_p1')
    .scene('sl4_p1_formal', 'sl4_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl4.p1_form_mei'), 'laugh')
    .jump('sl4_after_p1')
    .scene('sl4_p1_mistake', 'sl4_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('sl4.p1_mis_tanaka'), 'neutral')
    .jump('sl4_p1_mistake2')
    .scene('sl4_p1_mistake2', 'sl4_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.p1_mis_relief'), 'happy')
    .jump('sl4_after_p1')
    .scene('sl4_p1_own', 'sl4_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl4.p1_own_ken'), 'happy')
    .jump('sl4_after_p1')
    .scene('sl4_p1_min', 'sl4_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl4.p1_min_yuki'), 'gentle')
    .jump('sl4_after_p1')
    .scene('sl4_after_p1', 'sl4_after_p1')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl4.s2_intro'), 'speaking')
    .tanaka(tr('sl4.s2_week'), 'speaking')
    .tanaka(tr('sl4.s2_ex'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl4.s2_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('sl4.s2_a'), 'speaking')
    .tanaka(tr('sl4.p2_prompt'), 'happy')
    .menu()
    .choice(tr('sl4.c2_natural'), 'sl4_p2_natural')
    .choice(tr('sl4.c2_formal'), 'sl4_p2_formal')
    .choice(tr('sl4.c2_mistake'), 'sl4_p2_mistake')
    .choice(tr('sl4.c2_own'), 'sl4_p2_own')
    .choice(tr('sl4.c2_min'), 'sl4_p2_min')
    .endMenu()
    .scene('sl4_p2_natural', 'sl4_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.p2_nat_tanaka'), 'happy')
    .jump('sl4_after_p2')
    .scene('sl4_p2_formal', 'sl4_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('sl4.p2_form_yuki'), 'laugh')
    .jump('sl4_after_p2')
    .scene('sl4_p2_mistake', 'sl4_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c2_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('sl4.p2_mis_ken'), 'surprised')
    .jump('sl4_p2_mistake2')
    .scene('sl4_p2_mistake2', 'sl4_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('sl4.p2_mis_relief'), 'happy')
    .jump('sl4_after_p2')
    .scene('sl4_p2_own', 'sl4_p2_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c2_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.p2_own_tanaka'), 'happy')
    .jump('sl4_after_p2')
    .scene('sl4_p2_min', 'sl4_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl4.p2_min_mei'), 'happy')
    .jump('sl4_after_p2')
    .scene('sl4_after_p2', 'sl4_after_p2')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl4.s3_ken'), 'happy')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl4.s3_intro'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl4.s3_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('sl4.s3_a'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl4.s3_youbi'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl4.s3_youbi_a'), 'speaking')
    .tanaka(tr('sl4.p3_prompt'), 'happy')
    .menu()
    .choice(tr('sl4.c3_natural'), 'sl4_p3_natural')
    .choice(tr('sl4.c3_formal'), 'sl4_p3_formal')
    .choice(tr('sl4.c3_mistake'), 'sl4_p3_mistake')
    .choice(tr('sl4.c3_own'), 'sl4_p3_own')
    .choice(tr('sl4.c3_min'), 'sl4_p3_min')
    .endMenu()
    .scene('sl4_p3_natural', 'sl4_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c3_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl4.p3_nat_ken'), 'happy')
    .jump('sl4_after_p3')
    .scene('sl4_p3_formal', 'sl4_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('sl4.p3_form_ken'), 'laugh')
    .jump('sl4_after_p3')
    .scene('sl4_p3_mistake', 'sl4_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c3_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('sl4.p3_mis_yuki'), 'neutral')
    .jump('sl4_p3_mistake2')
    .scene('sl4_p3_mistake2', 'sl4_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.p3_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl4.p3_mis_relief'), 'happy')
    .jump('sl4_after_p3')
    .scene('sl4_p3_own', 'sl4_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('sl4.p3_own_ken'), 'happy')
    .jump('sl4_after_p3')
    .scene('sl4_p3_min', 'sl4_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('sl4.p3_min_mei'), 'happy')
    .jump('sl4_after_p3')
    .scene('sl4_after_p3', 'sl4_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('sl4.s4_intro'), 'speaking')
    .tanaka(tr('sl4.s4_ex'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('sl4.s4_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('sl4.s4_a'), 'speaking')
    .tanaka(tr('sl4.p4_prompt'), 'happy')
    .menu()
    .choice(tr('sl4.c4_natural'), 'sl4_p4_natural')
    .choice(tr('sl4.c4_formal'), 'sl4_p4_formal')
    .choice(tr('sl4.c4_mistake'), 'sl4_p4_mistake')
    .choice(tr('sl4.c4_own'), 'sl4_p4_own')
    .choice(tr('sl4.c4_min'), 'sl4_p4_min')
    .endMenu()
    .scene('sl4_p4_natural', 'sl4_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.p4_nat_tanaka'), 'happy')
    .jump('sl4_talk')
    .scene('sl4_p4_formal', 'sl4_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('sl4.p4_form_mei'), 'laugh')
    .jump('sl4_talk')
    .scene('sl4_p4_mistake', 'sl4_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c4_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl4.p4_mis_ken'), 'neutral')
    .jump('sl4_p4_mistake2')
    .scene('sl4_p4_mistake2', 'sl4_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.p4_mis_relief'), 'happy')
    .jump('sl4_talk')
    .scene('sl4_p4_own', 'sl4_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.p4_own_tanaka'), 'happy')
    .jump('sl4_talk')
    .scene('sl4_p4_min', 'sl4_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('sl4.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('sl4.p4_min_yuki'), 'gentle')
    .jump('sl4_talk')
    .scene('sl4_talk', 'sl4_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('sl4.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('sl4.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('sl4.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('sl4.talk_tanaka'), 'happy')
    .player(tr('sl4.talk_player'), 'neutral')
    .tanaka(tr('sl4.talk_close'), 'happy')
    .n(tr('sl4.complete'))
    .end()
    .build();
