import '../dialogue_builder.dart';

final story0Vocabulary = <StoryWord>[
  {
    'japanese': 'おはようございます',
    'reading': null,
    'romaji': 'ohayou gozaimasu',
    'english': 'Good morning (polite)',
    'category': 'greetings',
    'jlptLevel': 'N5',
    'example': '先生、おはようございます。',
    'exampleTranslation': 'Good morning, teacher.',
    'storyId': 0,
  },
  {
    'japanese': '初めまして',
    'reading': 'はじめまして',
    'romaji': 'hajimemashite',
    'english': 'Nice to meet you',
    'category': 'greetings',
    'jlptLevel': 'N5',
    'example': '初めまして、私は田中です。',
    'exampleTranslation': 'Nice to meet you, I am Tanaka.',
    'storyId': 0,
  },
  {
    'japanese': 'よろしくお願いします',
    'reading': 'よろしくおねがいします',
    'romaji': 'yoroshiku onegaishimasu',
    'english': 'Please be kind to me / Nice to meet you',
    'category': 'greetings',
    'jlptLevel': 'N5',
    'example': '田中です。よろしくお願いします。',
    'exampleTranslation': 'I am Tanaka. Nice to meet you.',
    'storyId': 0,
  },
  {
    'japanese': '私',
    'reading': 'わたし',
    'romaji': 'watashi',
    'english': 'I / me',
    'category': 'daily-life',
    'jlptLevel': 'N5',
    'example': '私は学生です。',
    'exampleTranslation': 'I am a student.',
    'storyId': 0,
  },
  {
    'japanese': '先生',
    'reading': 'せんせい',
    'romaji': 'sensei',
    'english': 'Teacher',
    'category': 'classroom',
    'jlptLevel': 'N5',
    'example': '田中先生は優しいです。',
    'exampleTranslation': 'Tanaka-sensei is kind.',
    'storyId': 0,
  },
  {
    'japanese': '学生',
    'reading': 'がくせい',
    'romaji': 'gakusei',
    'english': 'Student',
    'category': 'classroom',
    'jlptLevel': 'N5',
    'example': '私は日本語の学生です。',
    'exampleTranslation': 'I am a Japanese language student.',
    'storyId': 0,
  },
  {
    'japanese': '日本語',
    'reading': 'にほんご',
    'romaji': 'nihongo',
    'english': 'Japanese language',
    'category': 'classroom',
    'jlptLevel': 'N5',
    'example': '日本語は難しいですか？',
    'exampleTranslation': 'Is Japanese difficult?',
    'storyId': 0,
  },
  {
    'japanese': 'ありがとうございます',
    'reading': null,
    'romaji': 'arigatou gozaimasu',
    'english': 'Thank you (polite)',
    'category': 'greetings',
    'jlptLevel': 'N5',
    'example': '手伝ってくれて、ありがとうございます。',
    'exampleTranslation': 'Thank you for helping me.',
    'storyId': 0,
  },
  {
    'japanese': '友達',
    'reading': 'ともだち',
    'romaji': 'tomodachi',
    'english': 'Friend',
    'category': 'daily-life',
    'jlptLevel': 'N5',
    'example': 'ケンは私の友達です。',
    'exampleTranslation': 'Ken is my friend.',
    'storyId': 0,
  },
  {
    'japanese': 'カフェ',
    'reading': null,
    'romaji': 'kafe',
    'english': 'Cafe',
    'category': 'places',
    'jlptLevel': 'N5',
    'example': 'カフェでコーヒーを飲みましょう。',
    'exampleTranslation': "Let's drink coffee at the cafe.",
    'storyId': 0,
  },
  {
    'japanese': '教室',
    'reading': 'きょうしつ',
    'romaji': 'kyoushitsu',
    'english': 'Classroom',
    'category': 'classroom',
    'jlptLevel': 'N5',
    'example': '教室は二階にあります。',
    'exampleTranslation': 'The classroom is on the second floor.',
    'storyId': 0,
  },
  {
    'japanese': '名前',
    'reading': 'なまえ',
    'romaji': 'namae',
    'english': 'Name',
    'category': 'daily-life',
    'jlptLevel': 'N5',
    'example': 'お名前は何ですか？',
    'exampleTranslation': 'What is your name?',
    'storyId': 0,
  },
  {
    'japanese': 'どうぞ',
    'reading': null,
    'romaji': 'douzo',
    'english': 'Please / Go ahead',
    'category': 'greetings',
    'jlptLevel': 'N5',
    'example': 'どうぞ、座ってください。',
    'exampleTranslation': 'Please, have a seat.',
    'storyId': 0,
  },
  {
    'japanese': '勉強',
    'reading': 'べんきょう',
    'romaji': 'benkyou',
    'english': 'Study',
    'category': 'classroom',
    'jlptLevel': 'N5',
    'example': '毎日日本語を勉強します。',
    'exampleTranslation': 'I study Japanese every day.',
    'storyId': 0,
  },
  {
    'japanese': '頑張る',
    'reading': 'がんばる',
    'romaji': 'ganbaru',
    'english': 'To do one\'s best',
    'category': 'verbs',
    'jlptLevel': 'N5',
    'example': '頑張ります！',
    'exampleTranslation': 'I will do my best!',
    'storyId': 0,
  },
];

final story1Vocabulary = <StoryWord>[
  // Greetings & Meeting
  {
    'japanese': '初めまして',
    'reading': 'はじめまして',
    'romaji': 'hajimemashite',
    'english': 'Nice to meet you (first time)',
    'category': 'greetings',
    'jlptLevel': 'N5',
    'example': '初めまして、りんです。',
    'exampleTranslation': 'Nice to meet you, I\'m Rin.',
    'storyId': 1,
  },
  {
    'japanese': '久しぶり',
    'reading': 'ひさしぶり',
    'romaji': 'hisashiburi',
    'english': 'Long time no see',
    'category': 'greetings',
    'jlptLevel': 'N5',
    'example': '久しぶり！元気だった？',
    'exampleTranslation': 'Long time no see! How have you been?',
    'storyId': 1,
  },
  {
    'japanese': 'やっと会えた',
    'reading': 'やっとあえた',
    'romaji': 'yatto aeta',
    'english': 'Finally we meet',
    'category': 'greetings',
    'jlptLevel': 'N4',
    'example': 'やっと会えた！嬉しい！',
    'exampleTranslation': 'We finally meet! I\'m so happy!',
    'storyId': 1,
  },
  {
    'japanese': 'お待たせしました',
    'reading': 'おまたせしました',
    'romaji': 'omatase shimashita',
    'english': 'Sorry for making you wait',
    'category': 'greetings',
    'jlptLevel': 'N4',
    'example': 'お待たせしました。行きましょう。',
    'exampleTranslation': 'Sorry for the wait. Let\'s go.',
    'storyId': 1,
  },
  // Café vocabulary
  {
    'japanese': 'コーヒー',
    'reading': null,
    'romaji': 'koohii',
    'english': 'Coffee',
    'category': 'food',
    'jlptLevel': 'N5',
    'example': 'コーヒーを一つください。',
    'exampleTranslation': 'One coffee, please.',
    'storyId': 1,
  },
  {
    'japanese': '抹茶ラテ',
    'reading': 'まっちゃラテ',
    'romaji': 'matcha rate',
    'english': 'Matcha latte',
    'category': 'food',
    'jlptLevel': 'N4',
    'example': '抹茶ラテ、おいしいですよ。',
    'exampleTranslation': 'The matcha latte is delicious.',
    'storyId': 1,
  },
  {
    'japanese': '注文',
    'reading': 'ちゅうもん',
    'romaji': 'chuumon',
    'english': 'Order',
    'category': 'daily-life',
    'jlptLevel': 'N4',
    'example': 'ご注文はお決まりですか？',
    'exampleTranslation': 'Are you ready to order?',
    'storyId': 1,
  },
  {
    'japanese': 'お願いします',
    'reading': 'おねがいします',
    'romaji': 'onegaishimasu',
    'english': 'Please (request)',
    'category': 'phrases',
    'jlptLevel': 'N5',
    'example': 'これ、お願いします。',
    'exampleTranslation': 'This one, please.',
    'storyId': 1,
  },
  {
    'japanese': 'いただきます',
    'reading': null,
    'romaji': 'itadakimasu',
    'english': 'Phrase before eating/drinking',
    'category': 'phrases',
    'jlptLevel': 'N5',
    'example': 'いただきます！',
    'exampleTranslation': 'Let\'s eat! / Bon appétit!',
    'notes': 'Said before eating to express gratitude for the meal',
    'storyId': 1,
  },
  // Emotions & Nervousness
  {
    'japanese': '緊張',
    'reading': 'きんちょう',
    'romaji': 'kinchou',
    'english': 'Nervousness/tension',
    'category': 'emotions',
    'jlptLevel': 'N4',
    'example': '緊張しています。',
    'exampleTranslation': 'I\'m nervous.',
    'storyId': 1,
  },
  {
    'japanese': 'ドキドキ',
    'reading': null,
    'romaji': 'dokidoki',
    'english': 'Heart pounding (onomatopoeia)',
    'category': 'emotions',
    'jlptLevel': 'N4',
    'example': '心がドキドキする。',
    'exampleTranslation': 'My heart is pounding.',
    'notes': 'Onomatopoeia for heartbeat, used for nervousness or excitement',
    'storyId': 1,
  },
  {
    'japanese': '心配',
    'reading': 'しんぱい',
    'romaji': 'shinpai',
    'english': 'Worry/anxiety',
    'category': 'emotions',
    'jlptLevel': 'N5',
    'example': '心配しないで。',
    'exampleTranslation': 'Don\'t worry.',
    'storyId': 1,
  },
  {
    'japanese': '嬉しい',
    'reading': 'うれしい',
    'romaji': 'ureshii',
    'english': 'Happy/glad',
    'category': 'emotions',
    'jlptLevel': 'N5',
    'example': '会えて嬉しいです。',
    'exampleTranslation': 'I\'m glad to meet you.',
    'storyId': 1,
  },
  {
    'japanese': '安心',
    'reading': 'あんしん',
    'romaji': 'anshin',
    'english': 'Relief/peace of mind',
    'category': 'emotions',
    'jlptLevel': 'N4',
    'example': '安心しました。',
    'exampleTranslation': 'I\'m relieved.',
    'storyId': 1,
  },
  // Communication
  {
    'japanese': 'メッセージ',
    'reading': null,
    'romaji': 'messeeji',
    'english': 'Message',
    'category': 'daily-life',
    'jlptLevel': 'N4',
    'example': 'メッセージを送りました。',
    'exampleTranslation': 'I sent a message.',
    'storyId': 1,
  },
  {
    'japanese': 'ビデオ通話',
    'reading': 'ビデオつうわ',
    'romaji': 'bideo tsuuwa',
    'english': 'Video call',
    'category': 'daily-life',
    'jlptLevel': 'N4',
    'example': 'ビデオ通話しよう。',
    'exampleTranslation': 'Let\'s do a video call.',
    'storyId': 1,
  },
  {
    'japanese': '言語交換',
    'reading': 'げんごこうかん',
    'romaji': 'gengo koukan',
    'english': 'Language exchange',
    'category': 'daily-life',
    'jlptLevel': 'N3',
    'example': '言語交換パートナーを探しています。',
    'exampleTranslation': 'I\'m looking for a language exchange partner.',
    'storyId': 1,
  },
  {
    'japanese': '友達',
    'reading': 'ともだち',
    'romaji': 'tomodachi',
    'english': 'Friend',
    'category': 'daily-life',
    'jlptLevel': 'N5',
    'example': '私たちは友達です。',
    'exampleTranslation': 'We are friends.',
    'storyId': 1,
  },
  // Places
  {
    'japanese': '駅',
    'reading': 'えき',
    'romaji': 'eki',
    'english': 'Station',
    'category': 'places',
    'jlptLevel': 'N5',
    'example': '駅で待っています。',
    'exampleTranslation': 'I\'m waiting at the station.',
    'storyId': 1,
  },
  {
    'japanese': '改札',
    'reading': 'かいさつ',
    'romaji': 'kaisatsu',
    'english': 'Ticket gate',
    'category': 'places',
    'jlptLevel': 'N4',
    'example': '改札の前で会いましょう。',
    'exampleTranslation': 'Let\'s meet in front of the ticket gate.',
    'storyId': 1,
  },
  {
    'japanese': 'カフェ',
    'reading': null,
    'romaji': 'kafe',
    'english': 'Café',
    'category': 'places',
    'jlptLevel': 'N5',
    'example': 'カフェでコーヒーを飲みました。',
    'exampleTranslation': 'I drank coffee at a café.',
    'storyId': 1,
  },
  // Useful expressions
  {
    'japanese': '本当に',
    'reading': 'ほんとうに',
    'romaji': 'hontou ni',
    'english': 'Really/truly',
    'category': 'phrases',
    'jlptLevel': 'N5',
    'example': '本当にありがとう。',
    'exampleTranslation': 'Thank you so much.',
    'storyId': 1,
  },
  {
    'japanese': 'やっぱり',
    'reading': null,
    'romaji': 'yappari',
    'english': 'As expected / After all',
    'category': 'phrases',
    'jlptLevel': 'N4',
    'example': 'やっぱりそうだと思った。',
    'exampleTranslation': 'I thought so after all.',
    'storyId': 1,
  },
  {
    'japanese': '実は',
    'reading': 'じつは',
    'romaji': 'jitsu wa',
    'english': 'Actually / To tell the truth',
    'category': 'phrases',
    'jlptLevel': 'N4',
    'example': '実は、緊張していました。',
    'exampleTranslation': 'Actually, I was nervous.',
    'storyId': 1,
  },
  {
    'japanese': '自分',
    'reading': 'じぶん',
    'romaji': 'jibun',
    'english': 'Oneself / yourself',
    'category': 'daily-life',
    'jlptLevel': 'N5',
    'example': '自分を信じて。',
    'exampleTranslation': 'Believe in yourself.',
    'storyId': 1,
  },
  {
    'japanese': '出会い',
    'reading': 'であい',
    'romaji': 'deai',
    'english': 'Encounter/meeting',
    'category': 'daily-life',
    'jlptLevel': 'N4',
    'example': '素敵な出会いでした。',
    'exampleTranslation': 'It was a wonderful encounter.',
    'storyId': 1,
  },
  {
    'japanese': '今日',
    'reading': 'きょう',
    'romaji': 'kyou',
    'english': 'Today',
    'category': 'time',
    'jlptLevel': 'N5',
    'example': '今日は楽しかったです。',
    'exampleTranslation': 'Today was fun.',
    'storyId': 1,
  },
];
