// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNloTScikm2fbkP5PiUEmCXnSB1VZ5zo',
    appId: '1:997752747793:web:3e7f10798193943c84beb0',
    messagingSenderId: '997752747793',
    projectId: 'projects-d2d97',
    authDomain: 'projects-d2d97.firebaseapp.com',
    databaseURL: 'https://projects-d2d97-default-rtdb.firebaseio.com',
    storageBucket: 'projects-d2d97.firebasestorage.app',
    measurementId: 'G-4XFGYQ7QSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDXnj4gzgvnXU8Du3SB1_1OTYvnzXlw2A',
    appId: '1:997752747793:android:79b9f7d1dadb343c84beb0',
    messagingSenderId: '997752747793',
    projectId: 'projects-d2d97',
    databaseURL: 'https://projects-d2d97-default-rtdb.firebaseio.com',
    storageBucket: 'projects-d2d97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCra9b30919h3ZZNTZktbl8SJgXgDhbkmU',
    appId: '1:997752747793:ios:1d724ace1648a38c84beb0',
    messagingSenderId: '997752747793',
    projectId: 'projects-d2d97',
    databaseURL: 'https://projects-d2d97-default-rtdb.firebaseio.com',
    storageBucket: 'projects-d2d97.firebasestorage.app',
    iosBundleId: 'io.github.taalaydev.kizunaQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCra9b30919h3ZZNTZktbl8SJgXgDhbkmU',
    appId: '1:997752747793:ios:0cfe27639d8583d084beb0',
    messagingSenderId: '997752747793',
    projectId: 'projects-d2d97',
    databaseURL: 'https://projects-d2d97-default-rtdb.firebaseio.com',
    storageBucket: 'projects-d2d97.firebasestorage.app',
    iosBundleId: 'io.github.taalaydev.kizunaQuest.tsuzukiConnectGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdhbFC9LSJPQYbVk1NY1K8S2kvjpjBVF0',
    appId: '1:997752747793:web:f6c4126cea8e575c84beb0',
    messagingSenderId: '997752747793',
    projectId: 'projects-d2d97',
    authDomain: 'projects-d2d97.firebaseapp.com',
    databaseURL: 'https://projects-d2d97-default-rtdb.firebaseio.com',
    storageBucket: 'projects-d2d97.firebasestorage.app',
    measurementId: 'G-9GEF2W9408',
  );

}