import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson14 = VocabularyLessonDefinition(
  id: 'vocab_lesson_14',
  number: 14,
  level: VocabularyLessonLevel.intermediate,
  titleKey: 'vl14.title',
  subtitleKey: 'vl14.subtitle',
  descriptionKey: 'vl14.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  wordIds: <String>[
    'vocab_n4_6539_672d',
    'vocab_n4_7dca_5f35',
    'vocab_n4_9053_306b_8ff7_3046',
    'vocab_n4_6065_305a_304b_3057_3044',
    'vocab_n4_7df4_7fd2',
    'vocab_n4_85ac_5c40',
    'vocab_n4_3082_3089_3046',
    'vocab_n4_3084_3063_3071_308a',
    'vocab_n4_3088_304b_3063_305f',
    'vocab_n4_8a00_8449',
  ],
  storyFactory: getVocabularyLesson14,
);

StoryData getVocabularyLesson14() => dialogue()
    .story(14, tr('vl14.title'), tr('vl14.subtitle'))
    .description(tr('vl14.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N4')
    .scene('vl14_home', 'vl14_home')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .station('afternoon')
    .titleCard(tr('vl14.title'), tr('vl14.subtitle'), 2500)
    .n(tr('vl14.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.t_intro'), 'happy')
    .tanaka(tr('vl14.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl14.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl14.w1_a'), 'speaking')
    .tanaka(tr('vl14.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl14.c1_natural'), 'vl14_p1_natural')
    .choice(tr('vl14.c1_formal'), 'vl14_p1_formal')
    .choice(tr('vl14.c1_mistake'), 'vl14_p1_mistake')
    .choice(tr('vl14.c1_own'), 'vl14_p1_own')
    .choice(tr('vl14.c1_min'), 'vl14_p1_min')
    .endMenu()
    .scene('vl14_p1_natural', 'vl14_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p1_natural_r'), 'happy')
    .jump('vl14_after_p1')
    .scene('vl14_p1_formal', 'vl14_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl14.p1_formal_r'), 'laugh')
    .jump('vl14_after_p1')
    .scene('vl14_p1_mistake', 'vl14_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.p1_mistake_r'), 'neutral')
    .jump('vl14_p1_mistake2')
    .scene('vl14_p1_mistake2', 'vl14_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p1_mis_relief'), 'happy')
    .jump('vl14_after_p1')
    .scene('vl14_p1_own', 'vl14_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl14.p1_own_r'), 'happy')
    .jump('vl14_after_p1')
    .scene('vl14_p1_min', 'vl14_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl14.p1_min_r'), 'gentle')
    .jump('vl14_after_p1')
    .scene('vl14_after_p1', 'vl14_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('ken', 'left', 'concerned')
    .ken(tr('vl14.k_nervous'), 'concerned')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl14.w2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl14.w2_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl14.w2_a'), 'speaking')
    .n(tr('vl14.lost'))
    .tanaka(tr('vl14.w3'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl14.w3_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl14.w3_a'), 'speaking')
    .tanaka(tr('vl14.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl14.c2_natural'), 'vl14_p2_natural')
    .choice(tr('vl14.c2_formal'), 'vl14_p2_formal')
    .choice(tr('vl14.c2_mistake'), 'vl14_p2_mistake')
    .choice(tr('vl14.c2_own'), 'vl14_p2_own')
    .choice(tr('vl14.c2_min'), 'vl14_p2_min')
    .endMenu()
    .scene('vl14_p2_natural', 'vl14_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p2_natural_r'), 'happy')
    .jump('vl14_after_p2')
    .scene('vl14_p2_formal', 'vl14_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl14.p2_formal_r'), 'laugh')
    .jump('vl14_after_p2')
    .scene('vl14_p2_mistake', 'vl14_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.p2_mistake_r'), 'neutral')
    .jump('vl14_p2_mistake2')
    .scene('vl14_p2_mistake2', 'vl14_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p2_mis_relief'), 'happy')
    .jump('vl14_after_p2')
    .scene('vl14_p2_own', 'vl14_p2_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c2_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p2_own_r'), 'happy')
    .jump('vl14_after_p2')
    .scene('vl14_p2_min', 'vl14_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl14.p2_min_r'), 'gentle')
    .jump('vl14_after_p2')
    .scene('vl14_after_p2', 'vl14_after_p2')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.t_advice'), 'neutral')
    .show('ken', 'left', 'concerned')
    .ken(tr('vl14.k_shy'), 'concerned')
    .hide('ken')
    .tanaka(tr('vl14.w4'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl14.w4_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl14.w4_a'), 'speaking')
    .tanaka(tr('vl14.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl14.c3_natural'), 'vl14_p3_natural')
    .choice(tr('vl14.c3_formal'), 'vl14_p3_formal')
    .choice(tr('vl14.c3_mistake'), 'vl14_p3_mistake')
    .choice(tr('vl14.c3_own'), 'vl14_p3_own')
    .choice(tr('vl14.c3_min'), 'vl14_p3_min')
    .endMenu()
    .scene('vl14_p3_natural', 'vl14_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c3_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl14.p3_natural_r'), 'happy')
    .jump('vl14_after_p3')
    .scene('vl14_p3_formal', 'vl14_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl14.p3_formal_r'), 'laugh')
    .jump('vl14_after_p3')
    .scene('vl14_p3_mistake', 'vl14_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.p3_mistake_r'), 'neutral')
    .jump('vl14_p3_mistake2')
    .scene('vl14_p3_mistake2', 'vl14_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p3_mis_relief'), 'happy')
    .jump('vl14_after_p3')
    .scene('vl14_p3_own', 'vl14_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl14.p3_own_r'), 'happy')
    .jump('vl14_after_p3')
    .scene('vl14_p3_min', 'vl14_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl14.p3_min_r'), 'gentle')
    .jump('vl14_after_p3')
    .scene('vl14_after_p3', 'vl14_after_p3')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl14.w5'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl14.w5_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl14.w5_a'), 'speaking')
    .tanaka(tr('vl14.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl14.c4_natural'), 'vl14_p4_natural')
    .choice(tr('vl14.c4_formal'), 'vl14_p4_formal')
    .choice(tr('vl14.c4_mistake'), 'vl14_p4_mistake')
    .choice(tr('vl14.c4_own'), 'vl14_p4_own')
    .choice(tr('vl14.c4_min'), 'vl14_p4_min')
    .endMenu()
    .scene('vl14_p4_natural', 'vl14_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p4_natural_r'), 'happy')
    .jump('vl14_after_p4')
    .scene('vl14_p4_formal', 'vl14_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl14.p4_formal_r'), 'laugh')
    .jump('vl14_after_p4')
    .scene('vl14_p4_mistake', 'vl14_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.p4_mistake_r'), 'neutral')
    .jump('vl14_p4_mistake2')
    .scene('vl14_p4_mistake2', 'vl14_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p4_mis_relief'), 'happy')
    .jump('vl14_after_p4')
    .scene('vl14_p4_own', 'vl14_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c4_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl14.p4_own_r'), 'happy')
    .jump('vl14_after_p4')
    .scene('vl14_p4_min', 'vl14_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl14.p4_min_r'), 'happy')
    .jump('vl14_after_p4')
    .scene('vl14_after_p4', 'vl14_after_p4')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl14.pharmacy'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl14.w6'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl14.w6_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl14.w6_a'), 'speaking')
    .tanaka(tr('vl14.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl14.c5_natural'), 'vl14_p5_natural')
    .choice(tr('vl14.c5_formal'), 'vl14_p5_formal')
    .choice(tr('vl14.c5_mistake'), 'vl14_p5_mistake')
    .choice(tr('vl14.c5_own'), 'vl14_p5_own')
    .choice(tr('vl14.c5_min'), 'vl14_p5_min')
    .endMenu()
    .scene('vl14_p5_natural', 'vl14_p5_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c5_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p5_natural_r'), 'happy')
    .jump('vl14_after_p5')
    .scene('vl14_p5_formal', 'vl14_p5_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c5_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl14.p5_formal_r'), 'laugh')
    .jump('vl14_after_p5')
    .scene('vl14_p5_mistake', 'vl14_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.p5_mistake_r'), 'neutral')
    .jump('vl14_p5_mistake2')
    .scene('vl14_p5_mistake2', 'vl14_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p5_mis_relief'), 'happy')
    .jump('vl14_after_p5')
    .scene('vl14_p5_own', 'vl14_p5_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c5_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl14.p5_own_r'), 'happy')
    .jump('vl14_after_p5')
    .scene('vl14_p5_min', 'vl14_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl14.p5_min_r'), 'gentle')
    .jump('vl14_after_p5')
    .scene('vl14_after_p5', 'vl14_after_p5')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl14.sample'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl14.w7'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl14.w7_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl14.w7_a'), 'speaking')
    .tanaka(tr('vl14.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl14.c6_natural'), 'vl14_p6_natural')
    .choice(tr('vl14.c6_formal'), 'vl14_p6_formal')
    .choice(tr('vl14.c6_mistake'), 'vl14_p6_mistake')
    .choice(tr('vl14.c6_own'), 'vl14_p6_own')
    .choice(tr('vl14.c6_min'), 'vl14_p6_min')
    .endMenu()
    .scene('vl14_p6_natural', 'vl14_p6_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c6_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p6_natural_r'), 'happy')
    .jump('vl14_after_p6')
    .scene('vl14_p6_formal', 'vl14_p6_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c6_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl14.p6_formal_r'), 'laugh')
    .jump('vl14_after_p6')
    .scene('vl14_p6_mistake', 'vl14_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.p6_mistake_r'), 'neutral')
    .jump('vl14_p6_mistake2')
    .scene('vl14_p6_mistake2', 'vl14_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p6_mis_relief'), 'happy')
    .jump('vl14_after_p6')
    .scene('vl14_p6_own', 'vl14_p6_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c6_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p6_own_r'), 'happy')
    .jump('vl14_after_p6')
    .scene('vl14_p6_min', 'vl14_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl14.p6_min_r'), 'gentle')
    .jump('vl14_after_p6')
    .scene('vl14_after_p6', 'vl14_after_p6')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl14.found'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.t_welcome'), 'happy')
    .tanaka(tr('vl14.w8'), 'speaking')
    .tanaka(tr('vl14.w9'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl14.w9_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl14.w9_a'), 'speaking')
    .tanaka(tr('vl14.p7_prompt'), 'happy')
    .menu()
    .choice(tr('vl14.c7_natural'), 'vl14_p7_natural')
    .choice(tr('vl14.c7_formal'), 'vl14_p7_formal')
    .choice(tr('vl14.c7_mistake'), 'vl14_p7_mistake')
    .choice(tr('vl14.c7_own'), 'vl14_p7_own')
    .choice(tr('vl14.c7_min'), 'vl14_p7_min')
    .endMenu()
    .scene('vl14_p7_natural', 'vl14_p7_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c7_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl14.p7_natural_r'), 'happy')
    .jump('vl14_talk')
    .scene('vl14_p7_formal', 'vl14_p7_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c7_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl14.p7_formal_r'), 'laugh')
    .jump('vl14_talk')
    .scene('vl14_p7_mistake', 'vl14_p7_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c7_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl14.p7_mistake_r'), 'neutral')
    .jump('vl14_p7_mistake2')
    .scene('vl14_p7_mistake2', 'vl14_p7_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.p7_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.p7_mis_relief'), 'happy')
    .jump('vl14_talk')
    .scene('vl14_p7_own', 'vl14_p7_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c7_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl14.p7_own_r'), 'happy')
    .jump('vl14_talk')
    .scene('vl14_p7_min', 'vl14_p7_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl14.c7_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl14.p7_min_r'), 'gentle')
    .jump('vl14_talk')
    .scene('vl14_talk', 'vl14_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl14.w10'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl14.w10_q'), 'neutral')
    .tanaka(tr('vl14.w10_a'), 'speaking')
    .tanaka(tr('vl14.talk_open'), 'happy')
    .hide('tanaka')
    .ken(tr('vl14.talk_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('vl14.talk_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl14.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl14.talk_tanaka'), 'happy')
    .player(tr('vl14.talk_player'), 'happy')
    .tanaka(tr('vl14.talk_close'), 'happy')
    .n(tr('vl14.complete'))
    .end()
    .build();
