import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson04 = VocabularyLessonDefinition(
  id: 'vocab_lesson_04',
  number: 4,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl4.title',
  subtitleKey: 'vl4.subtitle',
  descriptionKey: 'vl4.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_5148_751f',
    'vocab_n5_5b66_751f',
    'vocab_n5_6559_5ba4',
    'vocab_n5_65e5_672c_8a9e',
    'vocab_n5_52c9_5f37',
    'vocab_n5_6559_3048_3066_304f_3060_3055_3044',
    'vocab_n5_3082_3046_4e00_5ea6',
    'vocab_n5_3086_3063_304f_308a',
    'vocab_n5_4e0a_624b',
    'vocab_n5_9811_5f35_308b',
  ],
  storyFactory: getVocabularyLesson04,
);

StoryData getVocabularyLesson04() => dialogue()
    .story(4, tr('vl4.title'), tr('vl4.subtitle'))
    .description(tr('vl4.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('vl4_class', 'vl4_class')
    .hide('grandma')
    .classroom('morning')
    .titleCard(tr('vl4.title'), tr('vl4.subtitle'), 2500)
    .n(tr('vl4.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.t_intro'), 'happy')
    .tanaka(tr('vl4.w1'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl4.w1_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl4.w1_a'), 'speaking')
    .tanaka(tr('vl4.w2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl4.w2_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl4.w2_a'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl4.w2_ken'), 'happy')
    .tanaka(tr('vl4.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl4.c1_natural'), 'vl4_p1_natural')
    .choice(tr('vl4.c1_formal'), 'vl4_p1_formal')
    .choice(tr('vl4.c1_mistake'), 'vl4_p1_mistake')
    .choice(tr('vl4.c1_own'), 'vl4_p1_own')
    .choice(tr('vl4.c1_min'), 'vl4_p1_min')
    .endMenu()
    .scene('vl4_p1_natural', 'vl4_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c1_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl4.p1_nat_mei'), 'happy')
    .jump('vl4_after_p1')
    .scene('vl4_p1_formal', 'vl4_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl4.c1_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl4.p1_form_yuki'), 'laugh')
    .jump('vl4_after_p1')
    .scene('vl4_p1_mistake', 'vl4_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c1_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl4.p1_mis_mei'), 'laugh')
    .jump('vl4_p1_mistake2')
    .scene('vl4_p1_mistake2', 'vl4_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.p1_mis_relief'), 'happy')
    .jump('vl4_after_p1')
    .scene('vl4_p1_own', 'vl4_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl4.p1_own_ken'), 'happy')
    .jump('vl4_after_p1')
    .scene('vl4_p1_min', 'vl4_p1_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c1_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.p1_min_tanaka'), 'happy')
    .jump('vl4_after_p1')
    .scene('vl4_after_p1', 'vl4_after_p1')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .n(tr('vl4.fast'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl4.fast_line'), 'speaking')
    .tanaka(tr('vl4.w3'), 'speaking')
    .tanaka(tr('vl4.w4'), 'speaking')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl4.w4_q'), 'surprised')
    .hide('ken')
    .tanaka(tr('vl4.w4_a'), 'speaking')
    .tanaka(tr('vl4.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl4.c2_natural'), 'vl4_p2_natural')
    .choice(tr('vl4.c2_formal'), 'vl4_p2_formal')
    .choice(tr('vl4.c2_mistake'), 'vl4_p2_mistake')
    .choice(tr('vl4.c2_own'), 'vl4_p2_own')
    .choice(tr('vl4.c2_min'), 'vl4_p2_min')
    .endMenu()
    .scene('vl4_p2_natural', 'vl4_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.p2_nat_tanaka'), 'happy')
    .jump('vl4_after_p2')
    .scene('vl4_p2_formal', 'vl4_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl4.p2_form_ken'), 'laugh')
    .jump('vl4_after_p2')
    .scene('vl4_p2_mistake', 'vl4_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c2_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl4.p2_mis_mei'), 'surprised')
    .jump('vl4_p2_mistake2')
    .scene('vl4_p2_mistake2', 'vl4_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.p2_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl4.p2_mis_relief'), 'happy')
    .jump('vl4_after_p2')
    .scene('vl4_p2_own', 'vl4_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl4.c2_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl4.p2_own_yuki'), 'happy')
    .jump('vl4_after_p2')
    .scene('vl4_p2_min', 'vl4_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.p2_min_tanaka'), 'happy')
    .jump('vl4_after_p2')
    .scene('vl4_after_p2', 'vl4_after_p2')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl4.w5'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl4.w5_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl4.w5_a'), 'speaking')
    .tanaka(tr('vl4.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl4.c3_natural'), 'vl4_p3_natural')
    .choice(tr('vl4.c3_formal'), 'vl4_p3_formal')
    .choice(tr('vl4.c3_mistake'), 'vl4_p3_mistake')
    .choice(tr('vl4.c3_own'), 'vl4_p3_own')
    .choice(tr('vl4.c3_min'), 'vl4_p3_min')
    .endMenu()
    .scene('vl4_p3_natural', 'vl4_p3_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c3_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.p3_nat_tanaka'), 'happy')
    .jump('vl4_after_p3')
    .scene('vl4_p3_formal', 'vl4_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl4.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl4.p3_form_yuki'), 'laugh')
    .jump('vl4_after_p3')
    .scene('vl4_p3_mistake', 'vl4_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c3_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl4.p3_mis_ken'), 'surprised')
    .jump('vl4_p3_mistake2')
    .scene('vl4_p3_mistake2', 'vl4_p3_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.p3_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl4.p3_mis_relief'), 'happy')
    .jump('vl4_after_p3')
    .scene('vl4_p3_own', 'vl4_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.p3_own_tanaka'), 'happy')
    .jump('vl4_after_p3')
    .scene('vl4_p3_min', 'vl4_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl4.p3_min_mei'), 'happy')
    .jump('vl4_after_p3')
    .scene('vl4_after_p3', 'vl4_after_p3')
    .hide('mei')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl4.w6'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl4.w6_yuki'), 'happy')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl4.w6_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl4.w6_a'), 'speaking')
    .yuki(tr('vl4.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl4.c4_natural'), 'vl4_p4_natural')
    .choice(tr('vl4.c4_formal'), 'vl4_p4_formal')
    .choice(tr('vl4.c4_mistake'), 'vl4_p4_mistake')
    .choice(tr('vl4.c4_own'), 'vl4_p4_own')
    .choice(tr('vl4.c4_min'), 'vl4_p4_min')
    .endMenu()
    .scene('vl4_p4_natural', 'vl4_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl4.c4_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl4.p4_nat_yuki'), 'happy')
    .jump('vl4_hall')
    .scene('vl4_p4_formal', 'vl4_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl4.p4_form_mei'), 'laugh')
    .jump('vl4_hall')
    .scene('vl4_p4_mistake', 'vl4_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c4_mistake'), 'concerned')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl4.p4_mis_ken'), 'laugh')
    .jump('vl4_p4_mistake2')
    .scene('vl4_p4_mistake2', 'vl4_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl4.p4_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl4.p4_mis_relief'), 'happy')
    .jump('vl4_hall')
    .scene('vl4_p4_own', 'vl4_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.p4_own_tanaka'), 'happy')
    .jump('vl4_hall')
    .scene('vl4_p4_min', 'vl4_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl4.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl4.p4_min_yuki'), 'gentle')
    .jump('vl4_hall')
    .scene('vl4_hall', 'vl4_hall')
    .hide('yuki')
    .hide('grandma')
    .bg('university_building', 'afternoon')
    .n(tr('vl4.hall'))
    .show('ken', 'left', 'concerned')
    .ken(tr('vl4.h_ken'), 'concerned')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl4.w7'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl4.w7_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl4.w7_a'), 'happy')
    .tanaka(tr('vl4.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl4.c5_natural'), 'vl4_p5_natural')
    .choice(tr('vl4.c5_formal'), 'vl4_p5_formal')
    .choice(tr('vl4.c5_mistake'), 'vl4_p5_mistake')
    .choice(tr('vl4.c5_own'), 'vl4_p5_own')
    .choice(tr('vl4.c5_min'), 'vl4_p5_min')
    .endMenu()
    .scene('vl4_p5_natural', 'vl4_p5_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c5_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl4.p5_nat_ken'), 'happy')
    .jump('vl4_talk')
    .scene('vl4_p5_formal', 'vl4_p5_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c5_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl4.p5_form_ken'), 'laugh')
    .jump('vl4_talk')
    .scene('vl4_p5_mistake', 'vl4_p5_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c5_mistake'), 'concerned')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl4.p5_mis_ken'), 'laugh')
    .jump('vl4_p5_mistake2')
    .scene('vl4_p5_mistake2', 'vl4_p5_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.p5_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl4.p5_mis_relief'), 'happy')
    .jump('vl4_talk')
    .scene('vl4_p5_own', 'vl4_p5_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c5_own'), 'happy')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl4.p5_own_ken'), 'surprised')
    .jump('vl4_talk')
    .scene('vl4_p5_min', 'vl4_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl4.c5_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl4.p5_min_mei'), 'happy')
    .jump('vl4_talk')
    .scene('vl4_talk', 'vl4_talk')
    .hide('grandma')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl4.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl4.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl4.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl4.talk_tanaka'), 'happy')
    .player(tr('vl4.talk_player'), 'neutral')
    .tanaka(tr('vl4.talk_close'), 'happy')
    .n(tr('vl4.complete'))
    .end()
    .build();
