import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson08 = VocabularyLessonDefinition(
  id: 'vocab_lesson_08',
  number: 8,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl8.title',
  subtitleKey: 'vl8.subtitle',
  descriptionKey: 'vl8.description',
  estimatedTime: '25–30 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_99c5',
    'vocab_n5_6559_3048_308b',
    'vocab_n5_75c5_9662',
    'vocab_n5_540d_524d',
    'vocab_n5_5931_793c_3057_307e_3059',
    'vocab_n5_958b_3051_308b',
    'vocab_n5_98df_5f8c',
    'vocab_n5_5c4a_304f',
    'vocab_n5_53d6_308b',
    'vocab_n5_3061_3087_3063_3068_5f85_3063_3066',
  ],
  storyFactory: getVocabularyLesson08,
);

StoryData getVocabularyLesson08() => dialogue()
    .story(8, tr('vl8.title'), tr('vl8.subtitle'))
    .description(tr('vl8.description'))
    .estimatedTime('25–30 min')
    .jlptFocus('N5')
    .scene('vl8_station', 'vl8_station')
    .hide('mei')
    .hide('grandpa')
    .station('afternoon')
    .titleCard(tr('vl8.title'), tr('vl8.subtitle'), 2500)
    .n(tr('vl8.setup'))
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl8.t_intro'), 'neutral')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.g_sorry'), 'neutral')
    .hide('grandma')
    .tanaka(tr('vl8.w1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl8.w1_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl8.w1_a'), 'speaking')
    .tanaka(tr('vl8.w2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl8.w2_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl8.w2_a'), 'speaking')
    .tanaka(tr('vl8.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl8.c1_natural'), 'vl8_p1_natural')
    .choice(tr('vl8.c1_formal'), 'vl8_p1_formal')
    .choice(tr('vl8.c1_mistake'), 'vl8_p1_mistake')
    .choice(tr('vl8.c1_own'), 'vl8_p1_own')
    .choice(tr('vl8.c1_min'), 'vl8_p1_min')
    .endMenu()
    .scene('vl8_p1_natural', 'vl8_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl8.p1_nat_yuki'), 'happy')
    .jump('vl8_hospital')
    .scene('vl8_p1_formal', 'vl8_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl8.p1_form_ken'), 'laugh')
    .jump('vl8_hospital')
    .scene('vl8_p1_mistake', 'vl8_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c1_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl8.p1_mis_mei'), 'surprised')
    .jump('vl8_p1_mistake2')
    .scene('vl8_p1_mistake2', 'vl8_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.p1_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p1_mis_relief'), 'happy')
    .jump('vl8_hospital')
    .scene('vl8_p1_own', 'vl8_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl8.p1_own_tanaka'), 'happy')
    .jump('vl8_hospital')
    .scene('vl8_p1_min', 'vl8_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl8.p1_min_yuki'), 'gentle')
    .jump('vl8_hospital')
    .scene('vl8_hospital', 'vl8_hospital')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hallway('afternoon')
    .n(tr('vl8.hospital'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl8.w3'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl8.w3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl8.w3_a'), 'speaking')
    .n(tr('vl8.reception'))
    .tanaka(tr('vl8.w4'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl8.w4_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl8.w4_a'), 'speaking')
    .tanaka(tr('vl8.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl8.c2_natural'), 'vl8_p2_natural')
    .choice(tr('vl8.c2_formal'), 'vl8_p2_formal')
    .choice(tr('vl8.c2_mistake'), 'vl8_p2_mistake')
    .choice(tr('vl8.c2_own'), 'vl8_p2_own')
    .choice(tr('vl8.c2_min'), 'vl8_p2_min')
    .endMenu()
    .scene('vl8_p2_natural', 'vl8_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p2_nat_mei'), 'happy')
    .jump('vl8_after_p2')
    .scene('vl8_p2_formal', 'vl8_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl8.p2_form_ken'), 'laugh')
    .jump('vl8_after_p2')
    .scene('vl8_p2_mistake', 'vl8_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl8.p2_mis_tanaka'), 'neutral')
    .jump('vl8_p2_mistake2')
    .scene('vl8_p2_mistake2', 'vl8_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.p2_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p2_mis_relief'), 'happy')
    .jump('vl8_after_p2')
    .scene('vl8_p2_own', 'vl8_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p2_own_mei'), 'happy')
    .jump('vl8_after_p2')
    .scene('vl8_p2_min', 'vl8_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl8.p2_min_yuki'), 'gentle')
    .jump('vl8_after_p2')
    .scene('vl8_after_p2', 'vl8_after_p2')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .n(tr('vl8.wait'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl8.w5'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl8.w5_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl8.w5_a'), 'speaking')
    .tanaka(tr('vl8.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl8.c3_natural'), 'vl8_p3_natural')
    .choice(tr('vl8.c3_formal'), 'vl8_p3_formal')
    .choice(tr('vl8.c3_mistake'), 'vl8_p3_mistake')
    .choice(tr('vl8.c3_own'), 'vl8_p3_own')
    .choice(tr('vl8.c3_min'), 'vl8_p3_min')
    .endMenu()
    .scene('vl8_p3_natural', 'vl8_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p3_nat_mei'), 'happy')
    .jump('vl8_after_p3')
    .scene('vl8_p3_formal', 'vl8_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl8.p3_form_yuki'), 'laugh')
    .jump('vl8_after_p3')
    .scene('vl8_p3_mistake', 'vl8_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c3_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl8.p3_mis_ken'), 'surprised')
    .jump('vl8_p3_mistake2')
    .scene('vl8_p3_mistake2', 'vl8_p3_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.p3_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl8.p3_mis_relief'), 'happy')
    .jump('vl8_after_p3')
    .scene('vl8_p3_own', 'vl8_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl8.p3_own_tanaka'), 'happy')
    .jump('vl8_after_p3')
    .scene('vl8_p3_min', 'vl8_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p3_min_mei'), 'happy')
    .jump('vl8_after_p3')
    .scene('vl8_after_p3', 'vl8_after_p3')
    .hide('ken')
    .hide('grandpa')
    .n(tr('vl8.doctor'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl8.w6'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl8.w6_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl8.w6_a'), 'speaking')
    .n(tr('vl8.medicine'))
    .tanaka(tr('vl8.w7'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl8.w7_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl8.w7_a'), 'speaking')
    .n(tr('vl8.pharmacy'))
    .tanaka(tr('vl8.w8'), 'speaking')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.g_reach'), 'neutral')
    .hide('grandma')
    .tanaka(tr('vl8.w9'), 'speaking')
    .tanaka(tr('vl8.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl8.c4_natural'), 'vl8_p4_natural')
    .choice(tr('vl8.c4_formal'), 'vl8_p4_formal')
    .choice(tr('vl8.c4_mistake'), 'vl8_p4_mistake')
    .choice(tr('vl8.c4_own'), 'vl8_p4_own')
    .choice(tr('vl8.c4_min'), 'vl8_p4_min')
    .endMenu()
    .scene('vl8_p4_natural', 'vl8_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl8.c4_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.p4_nat_grandma'), 'neutral')
    .jump('vl8_after_p4')
    .scene('vl8_p4_formal', 'vl8_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl8.c4_formal'), 'neutral')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.p4_form_grandma'), 'neutral')
    .jump('vl8_after_p4')
    .scene('vl8_p4_mistake', 'vl8_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c4_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl8.p4_mis_ken'), 'surprised')
    .jump('vl8_p4_mistake2')
    .scene('vl8_p4_mistake2', 'vl8_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl8.p4_mis_retry'), 'concerned')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.p4_mis_relief'), 'neutral')
    .jump('vl8_after_p4')
    .scene('vl8_p4_own', 'vl8_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl8.c4_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.p4_own_grandma'), 'neutral')
    .jump('vl8_after_p4')
    .scene('vl8_p4_min', 'vl8_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p4_min_mei'), 'happy')
    .jump('vl8_after_p4')
    .scene('vl8_after_p4', 'vl8_after_p4')
    .hide('ken')
    .hide('mei')
    .hide('grandpa')
    .n(tr('vl8.slow'))
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.g_wait'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl8.w10'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl8.w10_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl8.w10_a'), 'speaking')
    .tanaka(tr('vl8.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl8.c5_natural'), 'vl8_p5_natural')
    .choice(tr('vl8.c5_formal'), 'vl8_p5_formal')
    .choice(tr('vl8.c5_mistake'), 'vl8_p5_mistake')
    .choice(tr('vl8.c5_own'), 'vl8_p5_own')
    .choice(tr('vl8.c5_min'), 'vl8_p5_min')
    .endMenu()
    .scene('vl8_p5_natural', 'vl8_p5_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl8.c5_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.p5_nat_grandma'), 'neutral')
    .jump('vl8_talk')
    .scene('vl8_p5_formal', 'vl8_p5_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c5_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl8.p5_form_ken'), 'laugh')
    .jump('vl8_talk')
    .scene('vl8_p5_mistake', 'vl8_p5_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c5_mistake'), 'concerned')
    .show('yuki', 'far-right', 'surprised')
    .yuki(tr('vl8.p5_mis_yuki'), 'surprised')
    .jump('vl8_p5_mistake2')
    .scene('vl8_p5_mistake2', 'vl8_p5_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl8.p5_mis_retry'), 'concerned')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.p5_mis_relief'), 'neutral')
    .jump('vl8_talk')
    .scene('vl8_p5_own', 'vl8_p5_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl8.c5_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.p5_own_grandma'), 'neutral')
    .jump('vl8_talk')
    .scene('vl8_p5_min', 'vl8_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl8.c5_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.p5_min_mei'), 'happy')
    .jump('vl8_talk')
    .scene('vl8_talk', 'vl8_talk')
    .hide('grandpa')
    .apartment('evening')
    .n(tr('vl8.home'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl8.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl8.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl8.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl8.talk_yuki'), 'happy')
    .hide('yuki')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl8.talk_grandma'), 'neutral')
    .player(tr('vl8.talk_player'), 'neutral')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl8.talk_close'), 'happy')
    .n(tr('vl8.complete'))
    .end()
    .build();
