import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson06 = VocabularyLessonDefinition(
  id: 'vocab_lesson_06',
  number: 6,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl6.title',
  subtitleKey: 'vl6.subtitle',
  descriptionKey: 'vl6.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_4e45_3057_3076_308a',
    'vocab_n5_53cb_9054',
    'vocab_n5_6691_3044',
    'vocab_n5_672c_5f53_306b',
    'vocab_n5_75b2_308c_3066_3044_308b',
    'vocab_n5_5fc3_914d',
    'vocab_n5_7dca_5f35_3057_3066_308b',
    'vocab_n5_4e00_7dd2_306b',
    'vocab_n5_6c17_6301_3061',
    'vocab_n5_5b09_3057_3044',
  ],
  storyFactory: getVocabularyLesson06,
);

StoryData getVocabularyLesson06() => dialogue()
    .story(6, tr('vl6.title'), tr('vl6.subtitle'))
    .description(tr('vl6.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('vl6_station', 'vl6_station')
    .hide('grandma')
    .hide('grandpa')
    .station('afternoon')
    .titleCard(tr('vl6.title'), tr('vl6.subtitle'), 2500)
    .n(tr('vl6.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl6.t_intro'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.y_arrive'), 'happy')
    .hide('yuki')
    .show('mei', 'right', 'happy')
    .mei(tr('vl6.y_mei'), 'happy')
    .hide('mei')
    .tanaka(tr('vl6.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl6.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl6.w1_a'), 'speaking')
    .tanaka(tr('vl6.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl6.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl6.w2_a'), 'speaking')
    .tanaka(tr('vl6.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl6.c1_natural'), 'vl6_p1_natural')
    .choice(tr('vl6.c1_formal'), 'vl6_p1_formal')
    .choice(tr('vl6.c1_mistake'), 'vl6_p1_mistake')
    .choice(tr('vl6.c1_own'), 'vl6_p1_own')
    .choice(tr('vl6.c1_min'), 'vl6_p1_min')
    .endMenu()
    .scene('vl6_p1_natural', 'vl6_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p1_nat_yuki'), 'happy')
    .jump('vl6_after_p1')
    .scene('vl6_p1_formal', 'vl6_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c1_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl6.p1_form_yuki'), 'laugh')
    .jump('vl6_after_p1')
    .scene('vl6_p1_mistake', 'vl6_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c1_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl6.p1_mis_mei'), 'laugh')
    .jump('vl6_p1_mistake2')
    .scene('vl6_p1_mistake2', 'vl6_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.p1_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p1_mis_relief'), 'happy')
    .jump('vl6_after_p1')
    .scene('vl6_p1_own', 'vl6_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p1_own_yuki'), 'happy')
    .jump('vl6_after_p1')
    .scene('vl6_p1_min', 'vl6_p1_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c1_min'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl6.p1_min_ken'), 'happy')
    .jump('vl6_after_p1')
    .scene('vl6_after_p1', 'vl6_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl6.y_hot'), 'neutral')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl6.w3'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl6.w3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl6.w3_a'), 'speaking')
    .tanaka(tr('vl6.w4'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl6.w4_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl6.w4_a'), 'speaking')
    .tanaka(tr('vl6.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl6.c2_natural'), 'vl6_p2_natural')
    .choice(tr('vl6.c2_formal'), 'vl6_p2_formal')
    .choice(tr('vl6.c2_mistake'), 'vl6_p2_mistake')
    .choice(tr('vl6.c2_own'), 'vl6_p2_own')
    .choice(tr('vl6.c2_min'), 'vl6_p2_min')
    .endMenu()
    .scene('vl6_p2_natural', 'vl6_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p2_nat_yuki'), 'happy')
    .jump('vl6_cafe')
    .scene('vl6_p2_formal', 'vl6_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl6.p2_form_ken'), 'laugh')
    .jump('vl6_cafe')
    .scene('vl6_p2_mistake', 'vl6_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c2_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl6.p2_mis_mei'), 'laugh')
    .jump('vl6_p2_mistake2')
    .scene('vl6_p2_mistake2', 'vl6_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.p2_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p2_mis_relief'), 'happy')
    .jump('vl6_cafe')
    .scene('vl6_p2_own', 'vl6_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c2_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p2_own_yuki'), 'happy')
    .jump('vl6_cafe')
    .scene('vl6_p2_min', 'vl6_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl6.p2_min_tanaka'), 'happy')
    .jump('vl6_cafe')
    .scene('vl6_cafe', 'vl6_cafe')
    .hide('grandma')
    .hide('grandpa')
    .cafe('afternoon')
    .n(tr('vl6.cafe'))
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl6.y_tired'), 'neutral')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl6.w5'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl6.w5_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl6.w5_a'), 'speaking')
    .show('mei', 'right', 'concerned')
    .mei(tr('vl6.w5_mei'), 'concerned')
    .hide('mei')
    .tanaka(tr('vl6.w6'), 'speaking')
    .tanaka(tr('vl6.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl6.c3_natural'), 'vl6_p3_natural')
    .choice(tr('vl6.c3_formal'), 'vl6_p3_formal')
    .choice(tr('vl6.c3_mistake'), 'vl6_p3_mistake')
    .choice(tr('vl6.c3_own'), 'vl6_p3_own')
    .choice(tr('vl6.c3_min'), 'vl6_p3_min')
    .endMenu()
    .scene('vl6_p3_natural', 'vl6_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p3_nat_yuki'), 'happy')
    .jump('vl6_after_p3')
    .scene('vl6_p3_formal', 'vl6_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl6.p3_form_yuki'), 'laugh')
    .jump('vl6_after_p3')
    .scene('vl6_p3_mistake', 'vl6_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c3_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl6.p3_mis_ken'), 'neutral')
    .jump('vl6_p3_mistake2')
    .scene('vl6_p3_mistake2', 'vl6_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.p3_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p3_mis_relief'), 'happy')
    .jump('vl6_after_p3')
    .scene('vl6_p3_own', 'vl6_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c3_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p3_own_yuki'), 'happy')
    .jump('vl6_after_p3')
    .scene('vl6_p3_min', 'vl6_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl6.p3_min_mei'), 'happy')
    .jump('vl6_after_p3')
    .scene('vl6_after_p3', 'vl6_after_p3')
    .hide('ken')
    .hide('grandma')
    .hide('grandpa')
    .show('mei', 'right', 'concerned')
    .mei(tr('vl6.m_nervous'), 'concerned')
    .hide('mei')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl6.w7'), 'speaking')
    .tanaka(tr('vl6.w8'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl6.w8_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl6.w8_a'), 'speaking')
    .tanaka(tr('vl6.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl6.c4_natural'), 'vl6_p4_natural')
    .choice(tr('vl6.c4_formal'), 'vl6_p4_formal')
    .choice(tr('vl6.c4_mistake'), 'vl6_p4_mistake')
    .choice(tr('vl6.c4_own'), 'vl6_p4_own')
    .choice(tr('vl6.c4_min'), 'vl6_p4_min')
    .endMenu()
    .scene('vl6_p4_natural', 'vl6_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c4_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl6.p4_nat_mei'), 'happy')
    .jump('vl6_after_p4')
    .scene('vl6_p4_formal', 'vl6_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl6.p4_form_ken'), 'laugh')
    .jump('vl6_after_p4')
    .scene('vl6_p4_mistake', 'vl6_p4_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c4_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl6.p4_mis_mei'), 'laugh')
    .jump('vl6_p4_mistake2')
    .scene('vl6_p4_mistake2', 'vl6_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.p4_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl6.p4_mis_relief'), 'happy')
    .jump('vl6_after_p4')
    .scene('vl6_p4_own', 'vl6_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c4_own'), 'happy')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl6.p4_own_mei'), 'surprised')
    .jump('vl6_after_p4')
    .scene('vl6_p4_min', 'vl6_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl6.p4_min_yuki'), 'gentle')
    .jump('vl6_after_p4')
    .scene('vl6_after_p4', 'vl6_after_p4')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl6.w9'), 'speaking')
    .tanaka(tr('vl6.w10'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.y_thanks'), 'happy')
    .tanaka(tr('vl6.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl6.c5_natural'), 'vl6_p5_natural')
    .choice(tr('vl6.c5_formal'), 'vl6_p5_formal')
    .choice(tr('vl6.c5_mistake'), 'vl6_p5_mistake')
    .choice(tr('vl6.c5_own'), 'vl6_p5_own')
    .choice(tr('vl6.c5_min'), 'vl6_p5_min')
    .endMenu()
    .scene('vl6_p5_natural', 'vl6_p5_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c5_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p5_nat_yuki'), 'happy')
    .jump('vl6_talk')
    .scene('vl6_p5_formal', 'vl6_p5_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c5_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl6.p5_form_mei'), 'laugh')
    .jump('vl6_talk')
    .scene('vl6_p5_mistake', 'vl6_p5_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c5_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl6.p5_mis_ken'), 'surprised')
    .jump('vl6_p5_mistake2')
    .scene('vl6_p5_mistake2', 'vl6_p5_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.p5_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl6.p5_mis_relief'), 'laugh')
    .jump('vl6_talk')
    .scene('vl6_p5_own', 'vl6_p5_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c5_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.p5_own_yuki'), 'happy')
    .jump('vl6_talk')
    .scene('vl6_p5_min', 'vl6_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl6.c5_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl6.p5_min_mei'), 'happy')
    .jump('vl6_talk')
    .scene('vl6_talk', 'vl6_talk')
    .hide('grandma')
    .hide('grandpa')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl6.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl6.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'happy')
    .ken(tr('vl6.talk_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl6.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl6.talk_tanaka'), 'happy')
    .player(tr('vl6.talk_player'), 'neutral')
    .tanaka(tr('vl6.talk_close'), 'happy')
    .n(tr('vl6.complete'))
    .end()
    .build();
