import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson17 = VocabularyLessonDefinition(
  id: 'vocab_lesson_17',
  number: 17,
  level: VocabularyLessonLevel.advanced,
  titleKey: 'vl17.title',
  subtitleKey: 'vl17.subtitle',
  descriptionKey: 'vl17.description',
  estimatedTime: '35–40 min',
  cefrFocus: 'B1',
  wordIds: <String>[
    'vocab_n3_516c_6c11_9928',
    'vocab_n3_5730_57df',
    'vocab_n3_7fd2_3044_4e8b',
    'vocab_n3_624b_82b8',
    'vocab_n3_4ef2_9593',
    'vocab_n3_6311_6226',
    'vocab_n3_8ae6_3081_308b',
    'vocab_n3_7d99_7d9a_306f_529b_306a_308a',
    'vocab_n3_81ea_4fe1',
    'vocab_n3_4e16_8a71_306b_306a_308b',
  ],
  storyFactory: getVocabularyLesson17,
);

StoryData getVocabularyLesson17() => dialogue()
    .story(17, tr('vl17.title'), tr('vl17.subtitle'))
    .description(tr('vl17.description'))
    .estimatedTime('35–40 min')
    .jlptFocus('N3')
    .scene('vl17_home', 'vl17_home')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .bg('tatami_room', 'afternoon')
    .titleCard(tr('vl17.title'), tr('vl17.subtitle'), 2500)
    .n(tr('vl17.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.t_intro'), 'happy')
    .tanaka(tr('vl17.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl17.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl17.w1_a'), 'speaking')
    .tanaka(tr('vl17.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl17.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl17.w2_a'), 'speaking')
    .tanaka(tr('vl17.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c1_natural'), 'vl17_p1_natural')
    .choice(tr('vl17.c1_formal'), 'vl17_p1_formal')
    .choice(tr('vl17.c1_mistake'), 'vl17_p1_mistake')
    .choice(tr('vl17.c1_own'), 'vl17_p1_own')
    .choice(tr('vl17.c1_min'), 'vl17_p1_min')
    .endMenu()
    .scene('vl17_p1_natural', 'vl17_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p1_natural_r'), 'happy')
    .jump('vl17_after_p1')
    .scene('vl17_p1_formal', 'vl17_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl17.p1_formal_r'), 'laugh')
    .jump('vl17_after_p1')
    .scene('vl17_p1_mistake', 'vl17_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p1_mistake_r'), 'neutral')
    .jump('vl17_p1_mistake2')
    .scene('vl17_p1_mistake2', 'vl17_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p1_mis_relief'), 'happy')
    .jump('vl17_after_p1')
    .scene('vl17_p1_own', 'vl17_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p1_own_r'), 'happy')
    .jump('vl17_after_p1')
    .scene('vl17_p1_min', 'vl17_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl17.p1_min_r'), 'gentle')
    .jump('vl17_after_p1')
    .scene('vl17_after_p1', 'vl17_after_p1')
    .hide('ken')
    .hide('mei')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl17.room'))
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.gm_hello'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl17.w3'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl17.w3_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl17.w3_a'), 'speaking')
    .tanaka(tr('vl17.w4'), 'speaking')
    .tanaka(tr('vl17.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c2_natural'), 'vl17_p2_natural')
    .choice(tr('vl17.c2_formal'), 'vl17_p2_formal')
    .choice(tr('vl17.c2_mistake'), 'vl17_p2_mistake')
    .choice(tr('vl17.c2_own'), 'vl17_p2_own')
    .choice(tr('vl17.c2_min'), 'vl17_p2_min')
    .endMenu()
    .scene('vl17_p2_natural', 'vl17_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c2_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p2_natural_r'), 'neutral')
    .jump('vl17_after_p2')
    .scene('vl17_p2_formal', 'vl17_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl17.p2_formal_r'), 'laugh')
    .jump('vl17_after_p2')
    .scene('vl17_p2_mistake', 'vl17_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p2_mistake_r'), 'neutral')
    .jump('vl17_p2_mistake2')
    .scene('vl17_p2_mistake2', 'vl17_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p2_mis_relief'), 'happy')
    .jump('vl17_after_p2')
    .scene('vl17_p2_own', 'vl17_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c2_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p2_own_r'), 'neutral')
    .jump('vl17_after_p2')
    .scene('vl17_p2_min', 'vl17_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl17.p2_min_r'), 'happy')
    .jump('vl17_after_p2')
    .scene('vl17_after_p2', 'vl17_after_p2')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl17.sew'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl17.w5'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl17.w5_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl17.w5_a'), 'speaking')
    .tanaka(tr('vl17.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c3_natural'), 'vl17_p3_natural')
    .choice(tr('vl17.c3_formal'), 'vl17_p3_formal')
    .choice(tr('vl17.c3_mistake'), 'vl17_p3_mistake')
    .choice(tr('vl17.c3_own'), 'vl17_p3_own')
    .choice(tr('vl17.c3_min'), 'vl17_p3_min')
    .endMenu()
    .scene('vl17_p3_natural', 'vl17_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c3_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p3_natural_r'), 'neutral')
    .jump('vl17_after_p3')
    .scene('vl17_p3_formal', 'vl17_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl17.p3_formal_r'), 'laugh')
    .jump('vl17_after_p3')
    .scene('vl17_p3_mistake', 'vl17_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p3_mistake_r'), 'neutral')
    .jump('vl17_p3_mistake2')
    .scene('vl17_p3_mistake2', 'vl17_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p3_mis_relief'), 'happy')
    .jump('vl17_after_p3')
    .scene('vl17_p3_own', 'vl17_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c3_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p3_own_r'), 'neutral')
    .jump('vl17_after_p3')
    .scene('vl17_p3_min', 'vl17_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl17.p3_min_r'), 'gentle')
    .jump('vl17_after_p3')
    .scene('vl17_after_p3', 'vl17_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.gm_hard'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl17.w6'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl17.w6_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl17.w6_a'), 'speaking')
    .tanaka(tr('vl17.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c4_natural'), 'vl17_p4_natural')
    .choice(tr('vl17.c4_formal'), 'vl17_p4_formal')
    .choice(tr('vl17.c4_mistake'), 'vl17_p4_mistake')
    .choice(tr('vl17.c4_own'), 'vl17_p4_own')
    .choice(tr('vl17.c4_min'), 'vl17_p4_min')
    .endMenu()
    .scene('vl17_p4_natural', 'vl17_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c4_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p4_natural_r'), 'neutral')
    .jump('vl17_after_p4')
    .scene('vl17_p4_formal', 'vl17_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl17.p4_formal_r'), 'laugh')
    .jump('vl17_after_p4')
    .scene('vl17_p4_mistake', 'vl17_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p4_mistake_r'), 'neutral')
    .jump('vl17_p4_mistake2')
    .scene('vl17_p4_mistake2', 'vl17_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p4_mis_relief'), 'happy')
    .jump('vl17_after_p4')
    .scene('vl17_p4_own', 'vl17_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c4_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p4_own_r'), 'neutral')
    .jump('vl17_after_p4')
    .scene('vl17_p4_min', 'vl17_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl17.p4_min_r'), 'gentle')
    .jump('vl17_after_p4')
    .scene('vl17_after_p4', 'vl17_after_p4')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl17.fail'))
    .show('ken', 'left', 'concerned')
    .ken(tr('vl17.k_giveup'), 'concerned')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl17.w7'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl17.w7_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl17.w7_a'), 'speaking')
    .tanaka(tr('vl17.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c5_natural'), 'vl17_p5_natural')
    .choice(tr('vl17.c5_formal'), 'vl17_p5_formal')
    .choice(tr('vl17.c5_mistake'), 'vl17_p5_mistake')
    .choice(tr('vl17.c5_own'), 'vl17_p5_own')
    .choice(tr('vl17.c5_min'), 'vl17_p5_min')
    .endMenu()
    .scene('vl17_p5_natural', 'vl17_p5_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c5_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl17.p5_natural_r'), 'happy')
    .jump('vl17_after_p5')
    .scene('vl17_p5_formal', 'vl17_p5_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c5_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl17.p5_formal_r'), 'laugh')
    .jump('vl17_after_p5')
    .scene('vl17_p5_mistake', 'vl17_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p5_mistake_r'), 'neutral')
    .jump('vl17_p5_mistake2')
    .scene('vl17_p5_mistake2', 'vl17_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p5_mis_relief'), 'happy')
    .jump('vl17_after_p5')
    .scene('vl17_p5_own', 'vl17_p5_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c5_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl17.p5_own_r'), 'happy')
    .jump('vl17_after_p5')
    .scene('vl17_p5_min', 'vl17_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl17.p5_min_r'), 'gentle')
    .jump('vl17_after_p5')
    .scene('vl17_after_p5', 'vl17_after_p5')
    .hide('ken')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.gm_proverb'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl17.w8'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl17.w8_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl17.w8_a'), 'speaking')
    .tanaka(tr('vl17.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c6_natural'), 'vl17_p6_natural')
    .choice(tr('vl17.c6_formal'), 'vl17_p6_formal')
    .choice(tr('vl17.c6_mistake'), 'vl17_p6_mistake')
    .choice(tr('vl17.c6_own'), 'vl17_p6_own')
    .choice(tr('vl17.c6_min'), 'vl17_p6_min')
    .endMenu()
    .scene('vl17_p6_natural', 'vl17_p6_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c6_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl17.p6_natural_r'), 'happy')
    .jump('vl17_after_p6')
    .scene('vl17_p6_formal', 'vl17_p6_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c6_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl17.p6_formal_r'), 'laugh')
    .jump('vl17_after_p6')
    .scene('vl17_p6_mistake', 'vl17_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p6_mistake_r'), 'neutral')
    .jump('vl17_p6_mistake2')
    .scene('vl17_p6_mistake2', 'vl17_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p6_mis_relief'), 'happy')
    .jump('vl17_after_p6')
    .scene('vl17_p6_own', 'vl17_p6_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c6_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p6_own_r'), 'neutral')
    .jump('vl17_after_p6')
    .scene('vl17_p6_min', 'vl17_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl17.p6_min_r'), 'gentle')
    .jump('vl17_after_p6')
    .scene('vl17_after_p6', 'vl17_after_p6')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl17.finish'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl17.w9'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl17.w9_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl17.w9_a'), 'speaking')
    .tanaka(tr('vl17.p7_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c7_natural'), 'vl17_p7_natural')
    .choice(tr('vl17.c7_formal'), 'vl17_p7_formal')
    .choice(tr('vl17.c7_mistake'), 'vl17_p7_mistake')
    .choice(tr('vl17.c7_own'), 'vl17_p7_own')
    .choice(tr('vl17.c7_min'), 'vl17_p7_min')
    .endMenu()
    .scene('vl17_p7_natural', 'vl17_p7_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c7_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p7_natural_r'), 'happy')
    .jump('vl17_after_p7')
    .scene('vl17_p7_formal', 'vl17_p7_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c7_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl17.p7_formal_r'), 'laugh')
    .jump('vl17_after_p7')
    .scene('vl17_p7_mistake', 'vl17_p7_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c7_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p7_mistake_r'), 'neutral')
    .jump('vl17_p7_mistake2')
    .scene('vl17_p7_mistake2', 'vl17_p7_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p7_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p7_mis_relief'), 'happy')
    .jump('vl17_after_p7')
    .scene('vl17_p7_own', 'vl17_p7_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c7_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p7_own_r'), 'happy')
    .jump('vl17_after_p7')
    .scene('vl17_p7_min', 'vl17_p7_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c7_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl17.p7_min_r'), 'gentle')
    .jump('vl17_after_p7')
    .scene('vl17_after_p7', 'vl17_after_p7')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl17.leave'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl17.w10'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl17.w10_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl17.w10_a'), 'speaking')
    .tanaka(tr('vl17.p8_prompt'), 'happy')
    .menu()
    .choice(tr('vl17.c8_natural'), 'vl17_p8_natural')
    .choice(tr('vl17.c8_formal'), 'vl17_p8_formal')
    .choice(tr('vl17.c8_mistake'), 'vl17_p8_mistake')
    .choice(tr('vl17.c8_own'), 'vl17_p8_own')
    .choice(tr('vl17.c8_min'), 'vl17_p8_min')
    .endMenu()
    .scene('vl17_p8_natural', 'vl17_p8_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c8_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p8_natural_r'), 'neutral')
    .jump('vl17_talk')
    .scene('vl17_p8_formal', 'vl17_p8_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c8_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl17.p8_formal_r'), 'laugh')
    .jump('vl17_talk')
    .scene('vl17_p8_mistake', 'vl17_p8_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c8_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl17.p8_mistake_r'), 'neutral')
    .jump('vl17_p8_mistake2')
    .scene('vl17_p8_mistake2', 'vl17_p8_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.p8_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p8_mis_relief'), 'happy')
    .jump('vl17_talk')
    .scene('vl17_p8_own', 'vl17_p8_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c8_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl17.p8_own_r'), 'neutral')
    .jump('vl17_talk')
    .scene('vl17_p8_min', 'vl17_p8_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl17.c8_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.p8_min_r'), 'happy')
    .jump('vl17_talk')
    .scene('vl17_talk', 'vl17_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.talk_open'), 'happy')
    .hide('tanaka')
    .show('ken', 'left', 'happy')
    .ken(tr('vl17.talk_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('vl17.talk_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl17.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl17.talk_tanaka'), 'happy')
    .player(tr('vl17.talk_player'), 'happy')
    .tanaka(tr('vl17.talk_close'), 'happy')
    .n(tr('vl17.complete'))
    .end()
    .build();
