import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson16 = VocabularyLessonDefinition(
  id: 'vocab_lesson_16',
  number: 16,
  level: VocabularyLessonLevel.advanced,
  titleKey: 'vl16.title',
  subtitleKey: 'vl16.subtitle',
  descriptionKey: 'vl16.description',
  estimatedTime: '35–40 min',
  cefrFocus: 'B1',
  wordIds: <String>[
    'vocab_n3_5e38_9023',
    'vocab_n3_958b_696d',
    'vocab_n3_5bb6_8cc3',
    'vocab_n3_9589_5e97',
    'vocab_n3_5272_308a_52d8',
    'vocab_n3_6c17_3092_9063_3046',
    'vocab_n3_611a_75f4',
    'vocab_n3_76f8_69cc',
    'vocab_n3_7a7a_6c17_3092_8aad_3080',
    'vocab_n3_5f8c_6094',
  ],
  storyFactory: getVocabularyLesson16,
);

StoryData getVocabularyLesson16() => dialogue()
    .story(16, tr('vl16.title'), tr('vl16.subtitle'))
    .description(tr('vl16.description'))
    .estimatedTime('35–40 min')
    .jlptFocus('N3')
    .scene('vl16_home', 'vl16_home')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('evening')
    .titleCard(tr('vl16.title'), tr('vl16.subtitle'), 2500)
    .n(tr('vl16.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.t_intro'), 'happy')
    .tanaka(tr('vl16.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl16.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl16.w1_a'), 'speaking')
    .tanaka(tr('vl16.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl16.c1_natural'), 'vl16_p1_natural')
    .choice(tr('vl16.c1_formal'), 'vl16_p1_formal')
    .choice(tr('vl16.c1_mistake'), 'vl16_p1_mistake')
    .choice(tr('vl16.c1_own'), 'vl16_p1_own')
    .choice(tr('vl16.c1_min'), 'vl16_p1_min')
    .endMenu()
    .scene('vl16_p1_natural', 'vl16_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p1_natural_r'), 'happy')
    .jump('vl16_after_p1')
    .scene('vl16_p1_formal', 'vl16_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl16.p1_formal_r'), 'laugh')
    .jump('vl16_after_p1')
    .scene('vl16_p1_mistake', 'vl16_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl16.p1_mistake_r'), 'neutral')
    .jump('vl16_p1_mistake2')
    .scene('vl16_p1_mistake2', 'vl16_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p1_mis_relief'), 'happy')
    .jump('vl16_after_p1')
    .scene('vl16_p1_own', 'vl16_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p1_own_r'), 'happy')
    .jump('vl16_after_p1')
    .scene('vl16_p1_min', 'vl16_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl16.p1_min_r'), 'gentle')
    .jump('vl16_after_p1')
    .scene('vl16_after_p1', 'vl16_after_p1')
    .hide('ken')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl16.master'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl16.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl16.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl16.w2_a'), 'speaking')
    .n(tr('vl16.news'))
    .tanaka(tr('vl16.w3'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl16.w3_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl16.w3_a'), 'speaking')
    .tanaka(tr('vl16.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl16.c2_natural'), 'vl16_p2_natural')
    .choice(tr('vl16.c2_formal'), 'vl16_p2_formal')
    .choice(tr('vl16.c2_mistake'), 'vl16_p2_mistake')
    .choice(tr('vl16.c2_own'), 'vl16_p2_own')
    .choice(tr('vl16.c2_min'), 'vl16_p2_min')
    .endMenu()
    .scene('vl16_p2_natural', 'vl16_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p2_natural_r'), 'happy')
    .jump('vl16_after_p2')
    .scene('vl16_p2_formal', 'vl16_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl16.p2_formal_r'), 'laugh')
    .jump('vl16_after_p2')
    .scene('vl16_p2_mistake', 'vl16_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl16.p2_mistake_r'), 'neutral')
    .jump('vl16_p2_mistake2')
    .scene('vl16_p2_mistake2', 'vl16_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p2_mis_relief'), 'happy')
    .jump('vl16_after_p2')
    .scene('vl16_p2_own', 'vl16_p2_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c2_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p2_own_r'), 'happy')
    .jump('vl16_after_p2')
    .scene('vl16_p2_min', 'vl16_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl16.p2_min_r'), 'happy')
    .jump('vl16_after_p2')
    .scene('vl16_after_p2', 'vl16_after_p2')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl16.bill'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl16.w4'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl16.w4_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl16.w4_a'), 'speaking')
    .tanaka(tr('vl16.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl16.c3_natural'), 'vl16_p3_natural')
    .choice(tr('vl16.c3_formal'), 'vl16_p3_formal')
    .choice(tr('vl16.c3_mistake'), 'vl16_p3_mistake')
    .choice(tr('vl16.c3_own'), 'vl16_p3_own')
    .choice(tr('vl16.c3_min'), 'vl16_p3_min')
    .endMenu()
    .scene('vl16_p3_natural', 'vl16_p3_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c3_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p3_natural_r'), 'happy')
    .jump('vl16_after_p3')
    .scene('vl16_p3_formal', 'vl16_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl16.p3_formal_r'), 'laugh')
    .jump('vl16_after_p3')
    .scene('vl16_p3_mistake', 'vl16_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl16.p3_mistake_r'), 'neutral')
    .jump('vl16_p3_mistake2')
    .scene('vl16_p3_mistake2', 'vl16_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p3_mis_relief'), 'happy')
    .jump('vl16_after_p3')
    .scene('vl16_p3_own', 'vl16_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p3_own_r'), 'happy')
    .jump('vl16_after_p3')
    .scene('vl16_p3_min', 'vl16_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl16.p3_min_r'), 'gentle')
    .jump('vl16_after_p3')
    .scene('vl16_after_p3', 'vl16_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl16.dessert'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl16.w5'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl16.w5_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl16.w5_a'), 'speaking')
    .tanaka(tr('vl16.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl16.c4_natural'), 'vl16_p4_natural')
    .choice(tr('vl16.c4_formal'), 'vl16_p4_formal')
    .choice(tr('vl16.c4_mistake'), 'vl16_p4_mistake')
    .choice(tr('vl16.c4_own'), 'vl16_p4_own')
    .choice(tr('vl16.c4_min'), 'vl16_p4_min')
    .endMenu()
    .scene('vl16_p4_natural', 'vl16_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p4_natural_r'), 'happy')
    .jump('vl16_after_p4')
    .scene('vl16_p4_formal', 'vl16_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl16.p4_formal_r'), 'laugh')
    .jump('vl16_after_p4')
    .scene('vl16_p4_mistake', 'vl16_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl16.p4_mistake_r'), 'neutral')
    .jump('vl16_p4_mistake2')
    .scene('vl16_p4_mistake2', 'vl16_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p4_mis_relief'), 'happy')
    .jump('vl16_after_p4')
    .scene('vl16_p4_own', 'vl16_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p4_own_r'), 'happy')
    .jump('vl16_after_p4')
    .scene('vl16_p4_min', 'vl16_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl16.p4_min_r'), 'gentle')
    .jump('vl16_after_p4')
    .scene('vl16_after_p4', 'vl16_after_p4')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl16.tears'))
    .n(tr('vl16.vent'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl16.w6'), 'speaking')
    .tanaka(tr('vl16.w7'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl16.w7_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl16.w7_a'), 'speaking')
    .tanaka(tr('vl16.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl16.c5_natural'), 'vl16_p5_natural')
    .choice(tr('vl16.c5_formal'), 'vl16_p5_formal')
    .choice(tr('vl16.c5_mistake'), 'vl16_p5_mistake')
    .choice(tr('vl16.c5_own'), 'vl16_p5_own')
    .choice(tr('vl16.c5_min'), 'vl16_p5_min')
    .endMenu()
    .scene('vl16_p5_natural', 'vl16_p5_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c5_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p5_natural_r'), 'happy')
    .jump('vl16_after_p5')
    .scene('vl16_p5_formal', 'vl16_p5_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c5_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl16.p5_formal_r'), 'laugh')
    .jump('vl16_after_p5')
    .scene('vl16_p5_mistake', 'vl16_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'concerned')
    .tanaka(tr('vl16.p5_mistake_r'), 'concerned')
    .jump('vl16_p5_mistake2')
    .scene('vl16_p5_mistake2', 'vl16_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p5_mis_relief'), 'happy')
    .jump('vl16_after_p5')
    .scene('vl16_p5_own', 'vl16_p5_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c5_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p5_own_r'), 'happy')
    .jump('vl16_after_p5')
    .scene('vl16_p5_min', 'vl16_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl16.p5_min_r'), 'gentle')
    .jump('vl16_after_p5')
    .scene('vl16_after_p5', 'vl16_after_p5')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl16.quiet'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl16.w8'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl16.w8_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl16.w8_a'), 'speaking')
    .tanaka(tr('vl16.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl16.c6_natural'), 'vl16_p6_natural')
    .choice(tr('vl16.c6_formal'), 'vl16_p6_formal')
    .choice(tr('vl16.c6_mistake'), 'vl16_p6_mistake')
    .choice(tr('vl16.c6_own'), 'vl16_p6_own')
    .choice(tr('vl16.c6_min'), 'vl16_p6_min')
    .endMenu()
    .scene('vl16_p6_natural', 'vl16_p6_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c6_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl16.p6_natural_r'), 'happy')
    .jump('vl16_after_p6')
    .scene('vl16_p6_formal', 'vl16_p6_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c6_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl16.p6_formal_r'), 'laugh')
    .jump('vl16_after_p6')
    .scene('vl16_p6_mistake', 'vl16_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl16.p6_mistake_r'), 'neutral')
    .jump('vl16_p6_mistake2')
    .scene('vl16_p6_mistake2', 'vl16_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p6_mis_relief'), 'happy')
    .jump('vl16_after_p6')
    .scene('vl16_p6_own', 'vl16_p6_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c6_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl16.p6_own_r'), 'happy')
    .jump('vl16_after_p6')
    .scene('vl16_p6_min', 'vl16_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl16.p6_min_r'), 'gentle')
    .jump('vl16_after_p6')
    .scene('vl16_after_p6', 'vl16_after_p6')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl16.quiet2'))
    .n(tr('vl16.master_line'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl16.w9'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl16.w9_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl16.w9_a'), 'speaking')
    .tanaka(tr('vl16.p7_prompt'), 'happy')
    .menu()
    .choice(tr('vl16.c7_natural'), 'vl16_p7_natural')
    .choice(tr('vl16.c7_formal'), 'vl16_p7_formal')
    .choice(tr('vl16.c7_mistake'), 'vl16_p7_mistake')
    .choice(tr('vl16.c7_own'), 'vl16_p7_own')
    .choice(tr('vl16.c7_min'), 'vl16_p7_min')
    .endMenu()
    .scene('vl16_p7_natural', 'vl16_p7_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c7_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p7_natural_r'), 'happy')
    .jump('vl16_talk')
    .scene('vl16_p7_formal', 'vl16_p7_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c7_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl16.p7_formal_r'), 'laugh')
    .jump('vl16_talk')
    .scene('vl16_p7_mistake', 'vl16_p7_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c7_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl16.p7_mistake_r'), 'neutral')
    .jump('vl16_p7_mistake2')
    .scene('vl16_p7_mistake2', 'vl16_p7_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.p7_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p7_mis_relief'), 'happy')
    .jump('vl16_talk')
    .scene('vl16_p7_own', 'vl16_p7_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c7_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.p7_own_r'), 'happy')
    .jump('vl16_talk')
    .scene('vl16_p7_min', 'vl16_p7_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl16.c7_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl16.p7_min_r'), 'gentle')
    .jump('vl16_talk')
    .scene('vl16_talk', 'vl16_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.talk_open'), 'happy')
    .hide('tanaka')
    .show('ken', 'left', 'happy')
    .ken(tr('vl16.talk_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('vl16.talk_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl16.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl16.talk_tanaka'), 'happy')
    .player(tr('vl16.talk_player'), 'happy')
    .tanaka(tr('vl16.talk_close'), 'happy')
    .n(tr('vl16.complete'))
    .end()
    .build();
