import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson10 = VocabularyLessonDefinition(
  id: 'vocab_lesson_10',
  number: 10,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl10.title',
  subtitleKey: 'vl10.subtitle',
  descriptionKey: 'vl10.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_65e5_672c_8a9e_5b66_6821',
    'vocab_n5_521d_3081_307e_3057_3066',
    'vocab_n5_6765_308b',
    'vocab_n5_30ab_30d5_30a7',
    'vocab_n5_3042_308a_304c_3068_3046_3054_3056_3044_307e_3059',
    'vocab_n5_7956_7236',
    'vocab_n5_7956_6bcd',
    'vocab_n4_5b6b',
    'vocab_n4_7530_820e',
    'vocab_n5_571f',
  ],
  storyFactory: getVocabularyLesson10,
);

StoryData getVocabularyLesson10() => dialogue()
    .story(10, tr('vl10.title'), tr('vl10.subtitle'))
    .description(tr('vl10.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N5')
    .scene('vl10_school', 'vl10_school')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .classroom('morning')
    .titleCard(tr('vl10.title'), tr('vl10.subtitle'), 2500)
    .n(tr('vl10.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl10.t_intro'), 'happy')
    .tanaka(tr('vl10.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl10.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl10.w1_a'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.y_visit'), 'happy')
    .hide('yuki')
    .tanaka(tr('vl10.w3'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl10.w3_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl10.w3_a'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl10.p2_prompt'), 'neutral')
    .tanaka(tr('vl10.p2_tanaka'), 'happy')
    .menu()
    .choice(tr('vl10.c2_natural'), 'vl10_p2_natural')
    .choice(tr('vl10.c2_formal'), 'vl10_p2_formal')
    .choice(tr('vl10.c2_mistake'), 'vl10_p2_mistake')
    .choice(tr('vl10.c2_own'), 'vl10_p2_own')
    .choice(tr('vl10.c2_min'), 'vl10_p2_min')
    .endMenu()
    .scene('vl10_p2_natural', 'vl10_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p2_nat_yuki'), 'happy')
    .jump('vl10_meet')
    .scene('vl10_p2_formal', 'vl10_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl10.p2_form_ken'), 'laugh')
    .jump('vl10_meet')
    .scene('vl10_p2_mistake', 'vl10_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c2_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl10.p2_mis_yuki'), 'neutral')
    .jump('vl10_p2_mistake2')
    .scene('vl10_p2_mistake2', 'vl10_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.p2_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p2_mis_relief'), 'happy')
    .jump('vl10_meet')
    .scene('vl10_p2_own', 'vl10_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c2_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p2_own_yuki'), 'happy')
    .jump('vl10_meet')
    .scene('vl10_p2_min', 'vl10_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl10.p2_min_tanaka'), 'happy')
    .jump('vl10_meet')
    .scene('vl10_meet', 'vl10_meet')
    .hide('ken')
    .hide('mei')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl10.meet'))
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl10.gm_enter'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl10.w2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl10.w2_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl10.w2_a'), 'speaking')
    .tanaka(tr('vl10.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl10.c1_natural'), 'vl10_p1_natural')
    .choice(tr('vl10.c1_formal'), 'vl10_p1_formal')
    .choice(tr('vl10.c1_mistake'), 'vl10_p1_mistake')
    .choice(tr('vl10.c1_own'), 'vl10_p1_own')
    .choice(tr('vl10.c1_min'), 'vl10_p1_min')
    .endMenu()
    .scene('vl10_p1_natural', 'vl10_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c1_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl10.p1_nat_grandma'), 'neutral')
    .jump('vl10_cafe')
    .scene('vl10_p1_formal', 'vl10_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c1_formal'), 'neutral')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl10.p1_form_grandma'), 'neutral')
    .jump('vl10_cafe')
    .scene('vl10_p1_mistake', 'vl10_p1_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c1_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl10.p1_mis_ken'), 'surprised')
    .jump('vl10_p1_mistake2')
    .scene('vl10_p1_mistake2', 'vl10_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.p1_mis_retry'), 'concerned')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl10.p1_mis_relief'), 'neutral')
    .jump('vl10_cafe')
    .scene('vl10_p1_own', 'vl10_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c1_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl10.p1_own_grandma'), 'neutral')
    .jump('vl10_cafe')
    .scene('vl10_p1_min', 'vl10_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl10.p1_min_mei'), 'happy')
    .jump('vl10_cafe')
    .scene('vl10_cafe', 'vl10_cafe')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('afternoon')
    .n(tr('vl10.cafe'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl10.w4'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl10.w4_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl10.w4_a'), 'speaking')
    .tanaka(tr('vl10.g_gift'), 'happy')
    .tanaka(tr('vl10.w5'), 'speaking')
    .tanaka(tr('vl10.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl10.c3_natural'), 'vl10_p3_natural')
    .choice(tr('vl10.c3_formal'), 'vl10_p3_formal')
    .choice(tr('vl10.c3_mistake'), 'vl10_p3_mistake')
    .choice(tr('vl10.c3_own'), 'vl10_p3_own')
    .choice(tr('vl10.c3_min'), 'vl10_p3_min')
    .endMenu()
    .scene('vl10_p3_natural', 'vl10_p3_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c3_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl10.p3_nat_tanaka'), 'happy')
    .jump('vl10_after_p3')
    .scene('vl10_p3_formal', 'vl10_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl10.p3_form_mei'), 'laugh')
    .jump('vl10_after_p3')
    .scene('vl10_p3_mistake', 'vl10_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c3_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl10.p3_mis_ken'), 'surprised')
    .jump('vl10_p3_mistake2')
    .scene('vl10_p3_mistake2', 'vl10_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl10.p3_mis_relief'), 'happy')
    .jump('vl10_after_p3')
    .scene('vl10_p3_own', 'vl10_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl10.p3_own_tanaka'), 'happy')
    .jump('vl10_after_p3')
    .scene('vl10_p3_min', 'vl10_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl10.p3_min_yuki'), 'gentle')
    .jump('vl10_after_p3')
    .scene('vl10_after_p3', 'vl10_after_p3')
    .hide('ken')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.a_photo'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl10.w6'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl10.w6_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl10.w6_a'), 'speaking')
    .tanaka(tr('vl10.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl10.c4_natural'), 'vl10_p4_natural')
    .choice(tr('vl10.c4_formal'), 'vl10_p4_formal')
    .choice(tr('vl10.c4_mistake'), 'vl10_p4_mistake')
    .choice(tr('vl10.c4_own'), 'vl10_p4_own')
    .choice(tr('vl10.c4_min'), 'vl10_p4_min')
    .endMenu()
    .scene('vl10_p4_natural', 'vl10_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c4_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p4_nat_yuki'), 'happy')
    .jump('vl10_after_p4')
    .scene('vl10_p4_formal', 'vl10_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c4_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl10.p4_form_yuki'), 'laugh')
    .jump('vl10_after_p4')
    .scene('vl10_p4_mistake', 'vl10_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl10.p4_mis_tanaka'), 'neutral')
    .jump('vl10_p4_mistake2')
    .scene('vl10_p4_mistake2', 'vl10_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.p4_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p4_mis_relief'), 'happy')
    .jump('vl10_after_p4')
    .scene('vl10_p4_own', 'vl10_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c4_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p4_own_yuki'), 'happy')
    .jump('vl10_after_p4')
    .scene('vl10_p4_min', 'vl10_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl10.p4_min_mei'), 'happy')
    .jump('vl10_after_p4')
    .scene('vl10_after_p4', 'vl10_after_p4')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl10.a_mago'), 'neutral')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl10.w7'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl10.w7_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl10.w7_a'), 'happy')
    .tanaka(tr('vl10.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl10.c5_natural'), 'vl10_p5_natural')
    .choice(tr('vl10.c5_formal'), 'vl10_p5_formal')
    .choice(tr('vl10.c5_mistake'), 'vl10_p5_mistake')
    .choice(tr('vl10.c5_own'), 'vl10_p5_own')
    .choice(tr('vl10.c5_min'), 'vl10_p5_min')
    .endMenu()
    .scene('vl10_p5_natural', 'vl10_p5_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c5_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p5_nat_yuki'), 'happy')
    .jump('vl10_after_p5')
    .scene('vl10_p5_formal', 'vl10_p5_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c5_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl10.p5_form_ken'), 'laugh')
    .jump('vl10_after_p5')
    .scene('vl10_p5_mistake', 'vl10_p5_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c5_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl10.p5_mis_mei'), 'laugh')
    .jump('vl10_p5_mistake2')
    .scene('vl10_p5_mistake2', 'vl10_p5_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.p5_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl10.p5_mis_relief'), 'happy')
    .jump('vl10_after_p5')
    .scene('vl10_p5_own', 'vl10_p5_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c5_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.p5_own_yuki'), 'happy')
    .jump('vl10_after_p5')
    .scene('vl10_p5_min', 'vl10_p5_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl10.c5_min'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl10.p5_min_ken'), 'happy')
    .jump('vl10_after_p5')
    .scene('vl10_after_p5', 'vl10_after_p5')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl10.a_inaka'), 'neutral')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl10.w8_q'), 'neutral')
    .hide('mei')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl10.w8'), 'speaking')
    .say('grandma', tr('vl10.a_soil'), 'neutral')
    .hide('grandma')
    .tanaka(tr('vl10.w9'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl10.w9_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl10.w9_a'), 'speaking')
    .tanaka(tr('vl10.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl10.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'happy')
    .ken(tr('vl10.talk_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl10.talk_yuki'), 'happy')
    .hide('yuki')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl10.talk_grandma'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl10.talk_tanaka'), 'happy')
    .player(tr('vl10.talk_player'), 'neutral')
    .tanaka(tr('vl10.talk_close'), 'happy')
    .n(tr('vl10.complete'))
    .end()
    .build();
