import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson02 = VocabularyLessonDefinition(
  id: 'vocab_lesson_02',
  number: 2,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl2.title',
  subtitleKey: 'vl2.subtitle',
  descriptionKey: 'vl2.description',
  estimatedTime: '15–20 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_3044_3089_3063_3057_3083_3044_307e_305b',
    'vocab_n5_30b3_30fc_30d2_30fc',
    'vocab_n5_304a_9858_3044_3057_307e_3059',
    'vocab_n5_3069_3046_305e',
    'vocab_n5_3044_305f_3060_304d_307e_3059',
    'vocab_n5_7f8e_5473_3057_3044',
    'vocab_n5_3054_3081_3093_306a_3055_3044',
    'vocab_n5_5927_4e08_592b',
  ],
  storyFactory: getVocabularyLesson02,
);

StoryData getVocabularyLesson02() => dialogue()
    .story(2, tr('vl2.title'), tr('vl2.subtitle'))
    .description(tr('vl2.description'))
    .estimatedTime('15–20 min')
    .jlptFocus('N5')
    .scene('vl2_cafe', 'vl2_cafe')
    .cafe('afternoon')
    .titleCard(tr('vl2.title'), tr('vl2.subtitle'), 2500)
    .n(tr('vl2.setup'))
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.y_welcome'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl2.t_intro'), 'happy')
    .tanaka(tr('vl2.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl2.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl2.w1_a'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.w1_yuki'), 'happy')
    .hide('yuki')
    .tanaka(tr('vl2.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl2.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl2.w2_a'), 'speaking')
    .tanaka(tr('vl2.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl2.c1_natural'), 'vl2_p1_natural')
    .choice(tr('vl2.c1_formal'), 'vl2_p1_formal')
    .choice(tr('vl2.c1_mistake'), 'vl2_p1_mistake')
    .choice(tr('vl2.c1_own'), 'vl2_p1_own')
    .choice(tr('vl2.c1_min'), 'vl2_p1_min')
    .endMenu()
    .scene('vl2_p1_natural', 'vl2_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl2.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.p1_nat_yuki'), 'happy')
    .jump('vl2_after_p1')
    .scene('vl2_p1_formal', 'vl2_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl2.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl2.p1_form_ken'), 'laugh')
    .jump('vl2_after_p1')
    .scene('vl2_p1_mistake', 'vl2_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl2.c1_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl2.p1_mis_mei'), 'surprised')
    .jump('vl2_p1_mistake2')
    .scene('vl2_p1_mistake2', 'vl2_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl2.p1_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl2.p1_mis_relief'), 'happy')
    .jump('vl2_after_p1')
    .scene('vl2_p1_own', 'vl2_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl2.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.p1_own_yuki'), 'happy')
    .jump('vl2_after_p1')
    .scene('vl2_p1_min', 'vl2_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl2.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.p1_min_yuki'), 'happy')
    .jump('vl2_after_p1')
    .scene('vl2_after_p1', 'vl2_after_p1')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.w3_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl2.w3'), 'speaking')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl2.w3_q'), 'surprised')
    .hide('ken')
    .tanaka(tr('vl2.w3_a'), 'happy')
    .tanaka(tr('vl2.w4'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl2.w4_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl2.w4_a'), 'speaking')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl2.w4_yuki'), 'gentle')
    .hide('yuki')
    .tanaka(tr('vl2.w5'), 'speaking')
    .tanaka(tr('vl2.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl2.c2_natural'), 'vl2_p2_natural')
    .choice(tr('vl2.c2_formal'), 'vl2_p2_formal')
    .choice(tr('vl2.c2_mistake'), 'vl2_p2_mistake')
    .choice(tr('vl2.c2_own'), 'vl2_p2_own')
    .choice(tr('vl2.c2_min'), 'vl2_p2_min')
    .endMenu()
    .scene('vl2_p2_natural', 'vl2_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl2.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.p2_nat_yuki'), 'happy')
    .jump('vl2_after_p2')
    .scene('vl2_p2_formal', 'vl2_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl2.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl2.p2_form_mei'), 'laugh')
    .jump('vl2_after_p2')
    .scene('vl2_p2_mistake', 'vl2_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl2.c2_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl2.p2_mis_ken'), 'surprised')
    .jump('vl2_p2_mistake2')
    .scene('vl2_p2_mistake2', 'vl2_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl2.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl2.p2_mis_relief'), 'happy')
    .jump('vl2_after_p2')
    .scene('vl2_p2_own', 'vl2_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl2.c2_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.p2_own_yuki'), 'happy')
    .jump('vl2_after_p2')
    .scene('vl2_p2_min', 'vl2_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl2.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl2.p2_min_tanaka'), 'happy')
    .jump('vl2_after_p2')
    .scene('vl2_after_p2', 'vl2_after_p2')
    .n(tr('vl2.spill'))
    .show('ken', 'left', 'surprised')
    .ken(tr('vl2.w6_ken'), 'surprised')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl2.w6'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl2.w6_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl2.w6_a'), 'speaking')
    .hide('tanaka')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.w6_yuki'), 'happy')
    .yuki(tr('vl2.w7_yuki'), 'neutral')
    .hide('yuki')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl2.w7_ken'), 'neutral')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl2.w7'), 'speaking')
    .tanaka(tr('vl2.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl2.c3_natural'), 'vl2_p3_natural')
    .choice(tr('vl2.c3_formal'), 'vl2_p3_formal')
    .choice(tr('vl2.c3_mistake'), 'vl2_p3_mistake')
    .choice(tr('vl2.c3_own'), 'vl2_p3_own')
    .choice(tr('vl2.c3_min'), 'vl2_p3_min')
    .endMenu()
    .scene('vl2_p3_natural', 'vl2_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl2.c3_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.p3_nat_yuki'), 'happy')
    .jump('vl2_talk')
    .scene('vl2_p3_formal', 'vl2_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl2.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl2.p3_form_ken'), 'laugh')
    .jump('vl2_talk')
    .scene('vl2_p3_mistake', 'vl2_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl2.c3_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl2.p3_mis_mei'), 'surprised')
    .jump('vl2_p3_mistake2')
    .scene('vl2_p3_mistake2', 'vl2_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl2.p3_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl2.p3_mis_relief'), 'happy')
    .jump('vl2_talk')
    .scene('vl2_p3_own', 'vl2_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl2.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl2.p3_own_tanaka'), 'happy')
    .jump('vl2_talk')
    .scene('vl2_p3_min', 'vl2_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl2.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl2.p3_min_yuki'), 'gentle')
    .jump('vl2_talk')
    .scene('vl2_talk', 'vl2_talk')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl2.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl2.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl2.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl2.talk_yuki'), 'happy')
    .player(tr('vl2.talk_player'), 'neutral')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl2.talk_close'), 'happy')
    .n(tr('vl2.complete'))
    .end()
    .build();
