import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson13 = VocabularyLessonDefinition(
  id: 'vocab_lesson_13',
  number: 13,
  level: VocabularyLessonLevel.intermediate,
  titleKey: 'vl13.title',
  subtitleKey: 'vl13.subtitle',
  descriptionKey: 'vl13.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  wordIds: <String>[
    'vocab_n4_7a2e',
    'vocab_n4_82d7',
    'vocab_n4_80b2_3066_308b',
    'vocab_n4_8da3_5473',
    'vocab_n4_7d9a_3051_308b',
    'vocab_n4_5909_308f_308b',
    'vocab_n4_5909_3048_308b',
    'vocab_n4_81ea_5206',
    'vocab_n4_611f_3058_308b',
    'vocab_n4_7279_5225',
  ],
  storyFactory: getVocabularyLesson13,
);

StoryData getVocabularyLesson13() => dialogue()
    .story(13, tr('vl13.title'), tr('vl13.subtitle'))
    .description(tr('vl13.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N4')
    .scene('vl13_home', 'vl13_home')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .park('afternoon')
    .titleCard(tr('vl13.title'), tr('vl13.subtitle'), 2500)
    .n(tr('vl13.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.t_intro'), 'happy')
    .tanaka(tr('vl13.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl13.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl13.w1_a'), 'speaking')
    .tanaka(tr('vl13.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl13.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl13.w2_a'), 'speaking')
    .tanaka(tr('vl13.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl13.c1_natural'), 'vl13_p1_natural')
    .choice(tr('vl13.c1_formal'), 'vl13_p1_formal')
    .choice(tr('vl13.c1_mistake'), 'vl13_p1_mistake')
    .choice(tr('vl13.c1_own'), 'vl13_p1_own')
    .choice(tr('vl13.c1_min'), 'vl13_p1_min')
    .endMenu()
    .scene('vl13_p1_natural', 'vl13_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p1_natural_r'), 'happy')
    .jump('vl13_after_p1')
    .scene('vl13_p1_formal', 'vl13_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl13.p1_formal_r'), 'laugh')
    .jump('vl13_after_p1')
    .scene('vl13_p1_mistake', 'vl13_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl13.p1_mistake_r'), 'neutral')
    .jump('vl13_p1_mistake2')
    .scene('vl13_p1_mistake2', 'vl13_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p1_mis_relief'), 'happy')
    .jump('vl13_after_p1')
    .scene('vl13_p1_own', 'vl13_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p1_own_r'), 'happy')
    .jump('vl13_after_p1')
    .scene('vl13_p1_min', 'vl13_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl13.p1_min_r'), 'gentle')
    .jump('vl13_after_p1')
    .scene('vl13_after_p1', 'vl13_after_p1')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl13.w3'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl13.w3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl13.w3_a'), 'speaking')
    .tanaka(tr('vl13.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl13.c2_natural'), 'vl13_p2_natural')
    .choice(tr('vl13.c2_formal'), 'vl13_p2_formal')
    .choice(tr('vl13.c2_mistake'), 'vl13_p2_mistake')
    .choice(tr('vl13.c2_own'), 'vl13_p2_own')
    .choice(tr('vl13.c2_min'), 'vl13_p2_min')
    .endMenu()
    .scene('vl13_p2_natural', 'vl13_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl13.p2_natural_r'), 'happy')
    .jump('vl13_after_p2')
    .scene('vl13_p2_formal', 'vl13_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl13.p2_formal_r'), 'laugh')
    .jump('vl13_after_p2')
    .scene('vl13_p2_mistake', 'vl13_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl13.p2_mistake_r'), 'neutral')
    .jump('vl13_p2_mistake2')
    .scene('vl13_p2_mistake2', 'vl13_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p2_mis_relief'), 'happy')
    .jump('vl13_after_p2')
    .scene('vl13_p2_own', 'vl13_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c2_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl13.p2_own_r'), 'happy')
    .jump('vl13_after_p2')
    .scene('vl13_p2_min', 'vl13_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c2_min'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl13.p2_min_r'), 'neutral')
    .jump('vl13_after_p2')
    .scene('vl13_after_p2', 'vl13_after_p2')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl13.w4'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl13.w4_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl13.w4_a'), 'speaking')
    .tanaka(tr('vl13.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl13.c3_natural'), 'vl13_p3_natural')
    .choice(tr('vl13.c3_formal'), 'vl13_p3_formal')
    .choice(tr('vl13.c3_mistake'), 'vl13_p3_mistake')
    .choice(tr('vl13.c3_own'), 'vl13_p3_own')
    .choice(tr('vl13.c3_min'), 'vl13_p3_min')
    .endMenu()
    .scene('vl13_p3_natural', 'vl13_p3_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c3_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl13.p3_natural_r'), 'happy')
    .jump('vl13_after_p3')
    .scene('vl13_p3_formal', 'vl13_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl13.p3_formal_r'), 'laugh')
    .jump('vl13_after_p3')
    .scene('vl13_p3_mistake', 'vl13_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl13.p3_mistake_r'), 'neutral')
    .jump('vl13_p3_mistake2')
    .scene('vl13_p3_mistake2', 'vl13_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p3_mis_relief'), 'happy')
    .jump('vl13_after_p3')
    .scene('vl13_p3_own', 'vl13_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl13.p3_own_r'), 'happy')
    .jump('vl13_after_p3')
    .scene('vl13_p3_min', 'vl13_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl13.p3_min_r'), 'gentle')
    .jump('vl13_after_p3')
    .scene('vl13_after_p3', 'vl13_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl13.w5'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl13.w5_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl13.w5_a'), 'speaking')
    .tanaka(tr('vl13.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl13.c4_natural'), 'vl13_p4_natural')
    .choice(tr('vl13.c4_formal'), 'vl13_p4_formal')
    .choice(tr('vl13.c4_mistake'), 'vl13_p4_mistake')
    .choice(tr('vl13.c4_own'), 'vl13_p4_own')
    .choice(tr('vl13.c4_min'), 'vl13_p4_min')
    .endMenu()
    .scene('vl13_p4_natural', 'vl13_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p4_natural_r'), 'happy')
    .jump('vl13_after_p4')
    .scene('vl13_p4_formal', 'vl13_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl13.p4_formal_r'), 'laugh')
    .jump('vl13_after_p4')
    .scene('vl13_p4_mistake', 'vl13_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl13.p4_mistake_r'), 'neutral')
    .jump('vl13_p4_mistake2')
    .scene('vl13_p4_mistake2', 'vl13_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p4_mis_relief'), 'happy')
    .jump('vl13_after_p4')
    .scene('vl13_p4_own', 'vl13_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p4_own_r'), 'happy')
    .jump('vl13_after_p4')
    .scene('vl13_p4_min', 'vl13_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl13.p4_min_r'), 'gentle')
    .jump('vl13_after_p4')
    .scene('vl13_after_p4', 'vl13_after_p4')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl13.time_pass'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl13.w6'), 'speaking')
    .tanaka(tr('vl13.w7'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl13.w7_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl13.w7_a'), 'speaking')
    .tanaka(tr('vl13.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl13.c5_natural'), 'vl13_p5_natural')
    .choice(tr('vl13.c5_formal'), 'vl13_p5_formal')
    .choice(tr('vl13.c5_mistake'), 'vl13_p5_mistake')
    .choice(tr('vl13.c5_own'), 'vl13_p5_own')
    .choice(tr('vl13.c5_min'), 'vl13_p5_min')
    .endMenu()
    .scene('vl13_p5_natural', 'vl13_p5_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c5_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p5_natural_r'), 'happy')
    .jump('vl13_after_p5')
    .scene('vl13_p5_formal', 'vl13_p5_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c5_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl13.p5_formal_r'), 'laugh')
    .jump('vl13_after_p5')
    .scene('vl13_p5_mistake', 'vl13_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl13.p5_mistake_r'), 'neutral')
    .jump('vl13_p5_mistake2')
    .scene('vl13_p5_mistake2', 'vl13_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p5_mis_relief'), 'happy')
    .jump('vl13_after_p5')
    .scene('vl13_p5_own', 'vl13_p5_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c5_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p5_own_r'), 'happy')
    .jump('vl13_after_p5')
    .scene('vl13_p5_min', 'vl13_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl13.p5_min_r'), 'gentle')
    .jump('vl13_after_p5')
    .scene('vl13_after_p5', 'vl13_after_p5')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl13.harvest'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl13.w8'), 'speaking')
    .tanaka(tr('vl13.w9'), 'speaking')
    .tanaka(tr('vl13.w10'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl13.w10_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl13.w10_a'), 'speaking')
    .tanaka(tr('vl13.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl13.c6_natural'), 'vl13_p6_natural')
    .choice(tr('vl13.c6_formal'), 'vl13_p6_formal')
    .choice(tr('vl13.c6_mistake'), 'vl13_p6_mistake')
    .choice(tr('vl13.c6_own'), 'vl13_p6_own')
    .choice(tr('vl13.c6_min'), 'vl13_p6_min')
    .endMenu()
    .scene('vl13_p6_natural', 'vl13_p6_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c6_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p6_natural_r'), 'happy')
    .jump('vl13_talk')
    .scene('vl13_p6_formal', 'vl13_p6_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c6_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl13.p6_formal_r'), 'laugh')
    .jump('vl13_talk')
    .scene('vl13_p6_mistake', 'vl13_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl13.p6_mistake_r'), 'neutral')
    .jump('vl13_p6_mistake2')
    .scene('vl13_p6_mistake2', 'vl13_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.p6_mis_relief'), 'happy')
    .jump('vl13_talk')
    .scene('vl13_p6_own', 'vl13_p6_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c6_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl13.p6_own_r'), 'happy')
    .jump('vl13_talk')
    .scene('vl13_p6_min', 'vl13_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl13.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl13.p6_min_r'), 'gentle')
    .jump('vl13_talk')
    .scene('vl13_talk', 'vl13_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.talk_open'), 'happy')
    .hide('tanaka')
    .show('ken', 'left', 'happy')
    .ken(tr('vl13.talk_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('vl13.talk_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl13.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl13.talk_tanaka'), 'happy')
    .player(tr('vl13.talk_player'), 'happy')
    .tanaka(tr('vl13.talk_close'), 'happy')
    .n(tr('vl13.complete'))
    .end()
    .build();
