import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson12 = VocabularyLessonDefinition(
  id: 'vocab_lesson_12',
  number: 12,
  level: VocabularyLessonLevel.intermediate,
  titleKey: 'vl12.title',
  subtitleKey: 'vl12.subtitle',
  descriptionKey: 'vl12.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  wordIds: <String>[
    'vocab_n4_30ab_30a6_30f3_30bf_30fc',
    'vocab_n4_6ce8_6587',
    'vocab_n4_62b9_8336_30e9_30c6',
    'vocab_n4_52a9_6570_8a5e',
    'vocab_n4_4e01_5be7',
    'vocab_n4_30b9_30ca_30c3_30af',
    'vocab_n4_888b',
    'vocab_n4_304a_304b_308f_308a',
    'vocab_n4_304a_5f85_305f_305b_3057_307e_3057_305f',
    'vocab_n4_30c9_30ad_30c9_30ad',
  ],
  storyFactory: getVocabularyLesson12,
);

StoryData getVocabularyLesson12() => dialogue()
    .story(12, tr('vl12.title'), tr('vl12.subtitle'))
    .description(tr('vl12.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N4')
    .scene('vl12_home', 'vl12_home')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .cafe('afternoon')
    .titleCard(tr('vl12.title'), tr('vl12.subtitle'), 2500)
    .n(tr('vl12.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.t_intro'), 'happy')
    .tanaka(tr('vl12.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl12.w1_q'), 'neutral')
    .tanaka(tr('vl12.w1_a'), 'speaking')
    .ken(tr('vl12.k_nervous'), 'concerned')
    .hide('ken')
    .tanaka(tr('vl12.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl12.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl12.w3'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl12.w3_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl12.w3_a'), 'speaking')
    .tanaka(tr('vl12.w4'), 'speaking')
    .tanaka(tr('vl12.p1_intro'), 'happy')
    .tanaka(tr('vl12.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl12.c1_natural'), 'vl12_p1_natural')
    .choice(tr('vl12.c1_formal'), 'vl12_p1_formal')
    .choice(tr('vl12.c1_mistake'), 'vl12_p1_mistake')
    .choice(tr('vl12.c1_own'), 'vl12_p1_own')
    .choice(tr('vl12.c1_min'), 'vl12_p1_min')
    .endMenu()
    .scene('vl12_p1_natural', 'vl12_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p1_natural_r'), 'happy')
    .jump('vl12_after_p1')
    .scene('vl12_p1_formal', 'vl12_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl12.p1_formal_r'), 'laugh')
    .jump('vl12_after_p1')
    .scene('vl12_p1_mistake', 'vl12_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl12.p1_mistake_r'), 'neutral')
    .jump('vl12_p1_mistake2')
    .scene('vl12_p1_mistake2', 'vl12_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p1_mis_relief'), 'happy')
    .jump('vl12_after_p1')
    .scene('vl12_p1_own', 'vl12_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p1_own_r'), 'happy')
    .jump('vl12_after_p1')
    .scene('vl12_p1_min', 'vl12_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl12.p1_min_r'), 'gentle')
    .jump('vl12_after_p1')
    .scene('vl12_after_p1', 'vl12_after_p1')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl12.w5'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl12.w5_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl12.w5_a'), 'speaking')
    .tanaka(tr('vl12.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl12.c2_natural'), 'vl12_p2_natural')
    .choice(tr('vl12.c2_formal'), 'vl12_p2_formal')
    .choice(tr('vl12.c2_mistake'), 'vl12_p2_mistake')
    .choice(tr('vl12.c2_own'), 'vl12_p2_own')
    .choice(tr('vl12.c2_min'), 'vl12_p2_min')
    .endMenu()
    .scene('vl12_p2_natural', 'vl12_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p2_natural_r'), 'happy')
    .jump('vl12_after_p2')
    .scene('vl12_p2_formal', 'vl12_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl12.p2_formal_r'), 'laugh')
    .jump('vl12_after_p2')
    .scene('vl12_p2_mistake', 'vl12_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl12.p2_mistake_r'), 'neutral')
    .jump('vl12_p2_mistake2')
    .scene('vl12_p2_mistake2', 'vl12_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p2_mis_relief'), 'happy')
    .jump('vl12_after_p2')
    .scene('vl12_p2_own', 'vl12_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl12.p2_own_r'), 'happy')
    .jump('vl12_after_p2')
    .scene('vl12_p2_min', 'vl12_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl12.p2_min_r'), 'gentle')
    .jump('vl12_after_p2')
    .scene('vl12_after_p2', 'vl12_after_p2')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl12.w6'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl12.w6_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl12.w6_a'), 'speaking')
    .tanaka(tr('vl12.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl12.c3_natural'), 'vl12_p3_natural')
    .choice(tr('vl12.c3_formal'), 'vl12_p3_formal')
    .choice(tr('vl12.c3_mistake'), 'vl12_p3_mistake')
    .choice(tr('vl12.c3_own'), 'vl12_p3_own')
    .choice(tr('vl12.c3_min'), 'vl12_p3_min')
    .endMenu()
    .scene('vl12_p3_natural', 'vl12_p3_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c3_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p3_natural_r'), 'happy')
    .jump('vl12_after_p3')
    .scene('vl12_p3_formal', 'vl12_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl12.p3_formal_r'), 'laugh')
    .jump('vl12_after_p3')
    .scene('vl12_p3_mistake', 'vl12_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl12.p3_mistake_r'), 'neutral')
    .jump('vl12_p3_mistake2')
    .scene('vl12_p3_mistake2', 'vl12_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p3_mis_relief'), 'happy')
    .jump('vl12_after_p3')
    .scene('vl12_p3_own', 'vl12_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p3_own_r'), 'happy')
    .jump('vl12_after_p3')
    .scene('vl12_p3_min', 'vl12_p3_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c3_min'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl12.p3_min_r'), 'neutral')
    .jump('vl12_after_p3')
    .scene('vl12_after_p3', 'vl12_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl12.w7'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl12.w7_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl12.w7_a'), 'speaking')
    .tanaka(tr('vl12.w8'), 'speaking')
    .tanaka(tr('vl12.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl12.c4_natural'), 'vl12_p4_natural')
    .choice(tr('vl12.c4_formal'), 'vl12_p4_formal')
    .choice(tr('vl12.c4_mistake'), 'vl12_p4_mistake')
    .choice(tr('vl12.c4_own'), 'vl12_p4_own')
    .choice(tr('vl12.c4_min'), 'vl12_p4_min')
    .endMenu()
    .scene('vl12_p4_natural', 'vl12_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p4_natural_r'), 'happy')
    .jump('vl12_after_p4')
    .scene('vl12_p4_formal', 'vl12_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c4_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl12.p4_formal_r'), 'laugh')
    .jump('vl12_after_p4')
    .scene('vl12_p4_mistake', 'vl12_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl12.p4_mistake_r'), 'neutral')
    .jump('vl12_p4_mistake2')
    .scene('vl12_p4_mistake2', 'vl12_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p4_mis_relief'), 'happy')
    .jump('vl12_after_p4')
    .scene('vl12_p4_own', 'vl12_p4_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c4_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl12.p4_own_r'), 'happy')
    .jump('vl12_after_p4')
    .scene('vl12_p4_min', 'vl12_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl12.p4_min_r'), 'happy')
    .jump('vl12_after_p4')
    .scene('vl12_after_p4', 'vl12_after_p4')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl12.t_time'), 'neutral')
    .tanaka(tr('vl12.w9'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl12.w9_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl12.w9_a'), 'speaking')
    .tanaka(tr('vl12.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl12.c5_natural'), 'vl12_p5_natural')
    .choice(tr('vl12.c5_formal'), 'vl12_p5_formal')
    .choice(tr('vl12.c5_mistake'), 'vl12_p5_mistake')
    .choice(tr('vl12.c5_own'), 'vl12_p5_own')
    .choice(tr('vl12.c5_min'), 'vl12_p5_min')
    .endMenu()
    .scene('vl12_p5_natural', 'vl12_p5_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c5_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p5_natural_r'), 'happy')
    .jump('vl12_after_p5')
    .scene('vl12_p5_formal', 'vl12_p5_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c5_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl12.p5_formal_r'), 'laugh')
    .jump('vl12_after_p5')
    .scene('vl12_p5_mistake', 'vl12_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl12.p5_mistake_r'), 'neutral')
    .jump('vl12_p5_mistake2')
    .scene('vl12_p5_mistake2', 'vl12_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p5_mis_relief'), 'happy')
    .jump('vl12_after_p5')
    .scene('vl12_p5_own', 'vl12_p5_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c5_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl12.p5_own_r'), 'happy')
    .jump('vl12_after_p5')
    .scene('vl12_p5_min', 'vl12_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl12.p5_min_r'), 'gentle')
    .jump('vl12_after_p5')
    .scene('vl12_after_p5', 'vl12_after_p5')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl12.arrive'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl12.w10'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl12.w10_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl12.w10_a'), 'speaking')
    .tanaka(tr('vl12.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl12.c6_natural'), 'vl12_p6_natural')
    .choice(tr('vl12.c6_formal'), 'vl12_p6_formal')
    .choice(tr('vl12.c6_mistake'), 'vl12_p6_mistake')
    .choice(tr('vl12.c6_own'), 'vl12_p6_own')
    .choice(tr('vl12.c6_min'), 'vl12_p6_min')
    .endMenu()
    .scene('vl12_p6_natural', 'vl12_p6_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c6_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p6_natural_r'), 'happy')
    .jump('vl12_talk')
    .scene('vl12_p6_formal', 'vl12_p6_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c6_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl12.p6_formal_r'), 'laugh')
    .jump('vl12_talk')
    .scene('vl12_p6_mistake', 'vl12_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'concerned')
    .tanaka(tr('vl12.p6_mistake_r'), 'concerned')
    .jump('vl12_p6_mistake2')
    .scene('vl12_p6_mistake2', 'vl12_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.p6_mis_relief'), 'happy')
    .jump('vl12_talk')
    .scene('vl12_p6_own', 'vl12_p6_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c6_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl12.p6_own_r'), 'happy')
    .jump('vl12_talk')
    .scene('vl12_p6_min', 'vl12_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl12.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl12.p6_min_r'), 'gentle')
    .jump('vl12_talk')
    .scene('vl12_talk', 'vl12_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.talk_open'), 'happy')
    .hide('tanaka')
    .show('ken', 'left', 'happy')
    .ken(tr('vl12.talk_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('vl12.talk_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl12.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl12.talk_tanaka'), 'happy')
    .n(tr('vl12.pl_setup'))
    .player(tr('vl12.talk_player'), 'happy')
    .tanaka(tr('vl12.talk_close'), 'happy')
    .n(tr('vl12.complete'))
    .end()
    .build();
