import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson15 = VocabularyLessonDefinition(
  id: 'vocab_lesson_15',
  number: 15,
  level: VocabularyLessonLevel.advanced,
  titleKey: 'vl15.title',
  subtitleKey: 'vl15.subtitle',
  descriptionKey: 'vl15.description',
  estimatedTime: '35–40 min',
  cefrFocus: 'B1',
  wordIds: <String>[
    'vocab_n3_5e30_56fd',
    'vocab_n3_518d_8a2a',
    'vocab_n3_5f53_6642',
    'vocab_n3_61d0_304b_3057_3044',
    'vocab_n3_53d6_308a_58ca_3059',
    'vocab_n3_8de1_5730',
    'vocab_n3_9762_5f71',
    'vocab_n3_6b8b_308b',
    'vocab_n3_5207_306a_3044',
    'vocab_n3_611f_6168_6df1_3044',
  ],
  storyFactory: getVocabularyLesson15,
);

StoryData getVocabularyLesson15() => dialogue()
    .story(15, tr('vl15.title'), tr('vl15.subtitle'))
    .description(tr('vl15.description'))
    .estimatedTime('35–40 min')
    .jlptFocus('N3')
    .scene('vl15_home', 'vl15_home')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .street('evening')
    .titleCard(tr('vl15.title'), tr('vl15.subtitle'), 2500)
    .n(tr('vl15.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.t_intro'), 'happy')
    .tanaka(tr('vl15.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl15.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl15.w1_a'), 'speaking')
    .tanaka(tr('vl15.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl15.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl15.w2_a'), 'speaking')
    .tanaka(tr('vl15.w3'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl15.w3_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl15.w3_a'), 'speaking')
    .tanaka(tr('vl15.w4'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl15.w4_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl15.w4_a'), 'speaking')
    .tanaka(tr('vl15.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl15.c1_natural'), 'vl15_p1_natural')
    .choice(tr('vl15.c1_formal'), 'vl15_p1_formal')
    .choice(tr('vl15.c1_mistake'), 'vl15_p1_mistake')
    .choice(tr('vl15.c1_own'), 'vl15_p1_own')
    .choice(tr('vl15.c1_min'), 'vl15_p1_min')
    .endMenu()
    .scene('vl15_p1_natural', 'vl15_p1_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c1_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p1_natural_r'), 'happy')
    .jump('vl15_after_p1')
    .scene('vl15_p1_formal', 'vl15_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl15.p1_formal_r'), 'laugh')
    .jump('vl15_after_p1')
    .scene('vl15_p1_mistake', 'vl15_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl15.p1_mistake_r'), 'neutral')
    .jump('vl15_p1_mistake2')
    .scene('vl15_p1_mistake2', 'vl15_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p1_mis_relief'), 'happy')
    .jump('vl15_after_p1')
    .scene('vl15_p1_own', 'vl15_p1_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c1_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p1_own_r'), 'happy')
    .jump('vl15_after_p1')
    .scene('vl15_p1_min', 'vl15_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl15.p1_min_r'), 'gentle')
    .jump('vl15_after_p1')
    .scene('vl15_after_p1', 'vl15_after_p1')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl15.k_touji'), 'neutral')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl15.c2_natural'), 'vl15_p2_natural')
    .choice(tr('vl15.c2_formal'), 'vl15_p2_formal')
    .choice(tr('vl15.c2_mistake'), 'vl15_p2_mistake')
    .choice(tr('vl15.c2_own'), 'vl15_p2_own')
    .choice(tr('vl15.c2_min'), 'vl15_p2_min')
    .endMenu()
    .scene('vl15_p2_natural', 'vl15_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p2_natural_r'), 'happy')
    .jump('vl15_after_p2')
    .scene('vl15_p2_formal', 'vl15_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl15.p2_formal_r'), 'laugh')
    .jump('vl15_after_p2')
    .scene('vl15_p2_mistake', 'vl15_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl15.p2_mistake_r'), 'neutral')
    .jump('vl15_p2_mistake2')
    .scene('vl15_p2_mistake2', 'vl15_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p2_mis_relief'), 'happy')
    .jump('vl15_after_p2')
    .scene('vl15_p2_own', 'vl15_p2_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c2_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p2_own_r'), 'happy')
    .jump('vl15_after_p2')
    .scene('vl15_p2_min', 'vl15_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl15.p2_min_r'), 'gentle')
    .jump('vl15_after_p2')
    .scene('vl15_after_p2', 'vl15_after_p2')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl15.walk'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl15.w5'), 'speaking')
    .tanaka(tr('vl15.w6'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl15.w6_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl15.w6_a'), 'speaking')
    .tanaka(tr('vl15.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl15.c3_natural'), 'vl15_p3_natural')
    .choice(tr('vl15.c3_formal'), 'vl15_p3_formal')
    .choice(tr('vl15.c3_mistake'), 'vl15_p3_mistake')
    .choice(tr('vl15.c3_own'), 'vl15_p3_own')
    .choice(tr('vl15.c3_min'), 'vl15_p3_min')
    .endMenu()
    .scene('vl15_p3_natural', 'vl15_p3_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c3_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p3_natural_r'), 'happy')
    .jump('vl15_after_p3')
    .scene('vl15_p3_formal', 'vl15_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl15.p3_formal_r'), 'laugh')
    .jump('vl15_after_p3')
    .scene('vl15_p3_mistake', 'vl15_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl15.p3_mistake_r'), 'neutral')
    .jump('vl15_p3_mistake2')
    .scene('vl15_p3_mistake2', 'vl15_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p3_mis_relief'), 'happy')
    .jump('vl15_after_p3')
    .scene('vl15_p3_own', 'vl15_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p3_own_r'), 'happy')
    .jump('vl15_after_p3')
    .scene('vl15_p3_min', 'vl15_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl15.p3_min_r'), 'gentle')
    .jump('vl15_after_p3')
    .scene('vl15_after_p3', 'vl15_after_p3')
    .hide('ken')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl15.signboard'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl15.w7'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl15.w7_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl15.w7_a'), 'speaking')
    .tanaka(tr('vl15.w8'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl15.w8_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl15.w8_a'), 'speaking')
    .tanaka(tr('vl15.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl15.c4_natural'), 'vl15_p4_natural')
    .choice(tr('vl15.c4_formal'), 'vl15_p4_formal')
    .choice(tr('vl15.c4_mistake'), 'vl15_p4_mistake')
    .choice(tr('vl15.c4_own'), 'vl15_p4_own')
    .choice(tr('vl15.c4_min'), 'vl15_p4_min')
    .endMenu()
    .scene('vl15_p4_natural', 'vl15_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p4_natural_r'), 'happy')
    .jump('vl15_after_p4')
    .scene('vl15_p4_formal', 'vl15_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl15.p4_formal_r'), 'laugh')
    .jump('vl15_after_p4')
    .scene('vl15_p4_mistake', 'vl15_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl15.p4_mistake_r'), 'neutral')
    .jump('vl15_p4_mistake2')
    .scene('vl15_p4_mistake2', 'vl15_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p4_mis_relief'), 'happy')
    .jump('vl15_after_p4')
    .scene('vl15_p4_own', 'vl15_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p4_own_r'), 'happy')
    .jump('vl15_after_p4')
    .scene('vl15_p4_min', 'vl15_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl15.p4_min_r'), 'gentle')
    .jump('vl15_after_p4')
    .scene('vl15_after_p4', 'vl15_after_p4')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl15.t_quiet'), 'neutral')
    .tanaka(tr('vl15.w9'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl15.w9_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl15.w9_a'), 'speaking')
    .tanaka(tr('vl15.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl15.c5_natural'), 'vl15_p5_natural')
    .choice(tr('vl15.c5_formal'), 'vl15_p5_formal')
    .choice(tr('vl15.c5_mistake'), 'vl15_p5_mistake')
    .choice(tr('vl15.c5_own'), 'vl15_p5_own')
    .choice(tr('vl15.c5_min'), 'vl15_p5_min')
    .endMenu()
    .scene('vl15_p5_natural', 'vl15_p5_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c5_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p5_natural_r'), 'happy')
    .jump('vl15_after_p5')
    .scene('vl15_p5_formal', 'vl15_p5_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c5_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl15.p5_formal_r'), 'laugh')
    .jump('vl15_after_p5')
    .scene('vl15_p5_mistake', 'vl15_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl15.p5_mistake_r'), 'neutral')
    .jump('vl15_p5_mistake2')
    .scene('vl15_p5_mistake2', 'vl15_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p5_mis_relief'), 'happy')
    .jump('vl15_after_p5')
    .scene('vl15_p5_own', 'vl15_p5_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c5_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p5_own_r'), 'happy')
    .jump('vl15_after_p5')
    .scene('vl15_p5_min', 'vl15_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl15.p5_min_r'), 'gentle')
    .jump('vl15_after_p5')
    .scene('vl15_after_p5', 'vl15_after_p5')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl15.w10'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl15.w10_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl15.w10_a'), 'speaking')
    .tanaka(tr('vl15.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl15.c6_natural'), 'vl15_p6_natural')
    .choice(tr('vl15.c6_formal'), 'vl15_p6_formal')
    .choice(tr('vl15.c6_mistake'), 'vl15_p6_mistake')
    .choice(tr('vl15.c6_own'), 'vl15_p6_own')
    .choice(tr('vl15.c6_min'), 'vl15_p6_min')
    .endMenu()
    .scene('vl15_p6_natural', 'vl15_p6_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c6_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p6_natural_r'), 'happy')
    .jump('vl15_talk')
    .scene('vl15_p6_formal', 'vl15_p6_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c6_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl15.p6_formal_r'), 'laugh')
    .jump('vl15_talk')
    .scene('vl15_p6_mistake', 'vl15_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl15.p6_mistake_r'), 'neutral')
    .jump('vl15_p6_mistake2')
    .scene('vl15_p6_mistake2', 'vl15_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p6_mis_relief'), 'happy')
    .jump('vl15_talk')
    .scene('vl15_p6_own', 'vl15_p6_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c6_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.p6_own_r'), 'happy')
    .jump('vl15_talk')
    .scene('vl15_p6_min', 'vl15_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl15.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl15.p6_min_r'), 'gentle')
    .jump('vl15_talk')
    .scene('vl15_talk', 'vl15_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.talk_open'), 'happy')
    .hide('tanaka')
    .show('ken', 'left', 'happy')
    .ken(tr('vl15.talk_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('vl15.talk_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl15.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl15.talk_tanaka'), 'happy')
    .player(tr('vl15.talk_player'), 'happy')
    .tanaka(tr('vl15.talk_close'), 'happy')
    .n(tr('vl15.complete'))
    .end()
    .build();
