import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson07 = VocabularyLessonDefinition(
  id: 'vocab_lesson_07',
  number: 7,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl7.title',
  subtitleKey: 'vl7.subtitle',
  descriptionKey: 'vl7.description',
  estimatedTime: '25–30 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_30a2_30cb_30e1',
    'vocab_n5_9762_767d_3044',
    'vocab_n5_8aad_3080',
    'vocab_n5_6bce_65e5',
    'vocab_n5_4eca_65e5',
    'vocab_n5_4ed5_4e8b',
    'vocab_n5_5c06_6765',
    'vocab_n5_3084_3063_3066_307f_308b',
    'vocab_n5_4e00_4eba_3067',
    'vocab_n5_5927_5207',
  ],
  storyFactory: getVocabularyLesson07,
);

StoryData getVocabularyLesson07() => dialogue()
    .story(7, tr('vl7.title'), tr('vl7.subtitle'))
    .description(tr('vl7.description'))
    .estimatedTime('25–30 min')
    .jlptFocus('N5')
    .scene('vl7_class', 'vl7_class')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .classroom('afternoon')
    .titleCard(tr('vl7.title'), tr('vl7.subtitle'), 2500)
    .n(tr('vl7.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.t_intro'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.k_anime'), 'happy')
    .tanaka(tr('vl7.w1'), 'speaking')
    .ken(tr('vl7.w1_ken'), 'happy')
    .hide('ken')
    .tanaka(tr('vl7.w2'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl7.w2_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl7.w2_a'), 'speaking')
    .tanaka(tr('vl7.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl7.c1_natural'), 'vl7_p1_natural')
    .choice(tr('vl7.c1_formal'), 'vl7_p1_formal')
    .choice(tr('vl7.c1_mistake'), 'vl7_p1_mistake')
    .choice(tr('vl7.c1_own'), 'vl7_p1_own')
    .choice(tr('vl7.c1_min'), 'vl7_p1_min')
    .endMenu()
    .scene('vl7_p1_natural', 'vl7_p1_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c1_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.p1_nat_ken'), 'happy')
    .jump('vl7_after_p1')
    .scene('vl7_p1_formal', 'vl7_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl7.p1_form_ken'), 'laugh')
    .jump('vl7_after_p1')
    .scene('vl7_p1_mistake', 'vl7_p1_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c1_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl7.p1_mis_ken'), 'surprised')
    .jump('vl7_p1_mistake2')
    .scene('vl7_p1_mistake2', 'vl7_p1_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.p1_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.p1_mis_relief'), 'happy')
    .jump('vl7_after_p1')
    .scene('vl7_p1_own', 'vl7_p1_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c1_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.p1_own_ken'), 'happy')
    .jump('vl7_after_p1')
    .scene('vl7_p1_min', 'vl7_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl7.p1_min_mei'), 'happy')
    .jump('vl7_after_p1')
    .scene('vl7_after_p1', 'vl7_after_p1')
    .hide('grandma')
    .hide('grandpa')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl7.y_read'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl7.w3'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl7.w3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl7.w3_a'), 'happy')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl7.y_daily'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl7.w4'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl7.w4_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl7.w4_a'), 'speaking')
    .tanaka(tr('vl7.w5'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl7.w5_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl7.w5_a'), 'speaking')
    .tanaka(tr('vl7.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl7.c2_natural'), 'vl7_p2_natural')
    .choice(tr('vl7.c2_formal'), 'vl7_p2_formal')
    .choice(tr('vl7.c2_mistake'), 'vl7_p2_mistake')
    .choice(tr('vl7.c2_own'), 'vl7_p2_own')
    .choice(tr('vl7.c2_min'), 'vl7_p2_min')
    .endMenu()
    .scene('vl7_p2_natural', 'vl7_p2_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c2_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.p2_nat_tanaka'), 'happy')
    .jump('vl7_hall')
    .scene('vl7_p2_formal', 'vl7_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl7.p2_form_yuki'), 'laugh')
    .jump('vl7_hall')
    .scene('vl7_p2_mistake', 'vl7_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c2_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl7.p2_mis_yuki'), 'neutral')
    .jump('vl7_p2_mistake2')
    .scene('vl7_p2_mistake2', 'vl7_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.p2_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl7.p2_mis_relief'), 'happy')
    .jump('vl7_hall')
    .scene('vl7_p2_own', 'vl7_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.p2_own_ken'), 'happy')
    .jump('vl7_hall')
    .scene('vl7_p2_min', 'vl7_p2_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c2_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.p2_min_tanaka'), 'happy')
    .jump('vl7_hall')
    .scene('vl7_hall', 'vl7_hall')
    .hide('grandma')
    .hide('grandpa')
    .hallway('afternoon')
    .n(tr('vl7.hall'))
    .show('mei', 'right', 'neutral')
    .mei(tr('vl7.m_future'), 'neutral')
    .hide('mei')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl7.w6'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl7.w6_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl7.w6_a'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl7.y_work'), 'happy')
    .hide('yuki')
    .tanaka(tr('vl7.w7'), 'speaking')
    .tanaka(tr('vl7.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl7.c3_natural'), 'vl7_p3_natural')
    .choice(tr('vl7.c3_formal'), 'vl7_p3_formal')
    .choice(tr('vl7.c3_mistake'), 'vl7_p3_mistake')
    .choice(tr('vl7.c3_own'), 'vl7_p3_own')
    .choice(tr('vl7.c3_min'), 'vl7_p3_min')
    .endMenu()
    .scene('vl7_p3_natural', 'vl7_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl7.p3_nat_mei'), 'happy')
    .jump('vl7_park')
    .scene('vl7_p3_formal', 'vl7_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl7.p3_form_ken'), 'laugh')
    .jump('vl7_park')
    .scene('vl7_p3_mistake', 'vl7_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c3_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl7.p3_mis_ken'), 'surprised')
    .jump('vl7_p3_mistake2')
    .scene('vl7_p3_mistake2', 'vl7_p3_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.p3_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.p3_mis_relief'), 'happy')
    .jump('vl7_park')
    .scene('vl7_p3_own', 'vl7_p3_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c3_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.p3_own_ken'), 'happy')
    .jump('vl7_park')
    .scene('vl7_p3_min', 'vl7_p3_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c3_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.p3_min_tanaka'), 'happy')
    .jump('vl7_park')
    .scene('vl7_park', 'vl7_park')
    .hide('grandma')
    .hide('grandpa')
    .park('evening')
    .n(tr('vl7.park'))
    .show('mei', 'right', 'concerned')
    .mei(tr('vl7.m_alone'), 'concerned')
    .hide('mei')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.k_try'), 'happy')
    .hide('ken')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl7.w8'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl7.w8_q'), 'neutral')
    .tanaka(tr('vl7.w8_a'), 'speaking')
    .yuki(tr('vl7.y_club'), 'happy')
    .tanaka(tr('vl7.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl7.c4_natural'), 'vl7_p4_natural')
    .choice(tr('vl7.c4_formal'), 'vl7_p4_formal')
    .choice(tr('vl7.c4_mistake'), 'vl7_p4_mistake')
    .choice(tr('vl7.c4_own'), 'vl7_p4_own')
    .choice(tr('vl7.c4_min'), 'vl7_p4_min')
    .endMenu()
    .scene('vl7_p4_natural', 'vl7_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c4_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl7.p4_nat_yuki'), 'happy')
    .jump('vl7_after_p4')
    .scene('vl7_p4_formal', 'vl7_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c4_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl7.p4_form_mei'), 'laugh')
    .jump('vl7_after_p4')
    .scene('vl7_p4_mistake', 'vl7_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c4_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl7.p4_mis_ken'), 'surprised')
    .jump('vl7_p4_mistake2')
    .scene('vl7_p4_mistake2', 'vl7_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.p4_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl7.p4_mis_relief'), 'happy')
    .jump('vl7_after_p4')
    .scene('vl7_p4_own', 'vl7_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c4_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl7.p4_own_mei'), 'happy')
    .jump('vl7_after_p4')
    .scene('vl7_p4_min', 'vl7_p4_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c4_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.p4_min_tanaka'), 'happy')
    .jump('vl7_after_p4')
    .scene('vl7_after_p4', 'vl7_after_p4')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl7.w9'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl7.w9_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl7.w9_a'), 'speaking')
    .tanaka(tr('vl7.w10'), 'speaking')
    .tanaka(tr('vl7.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl7.c5_natural'), 'vl7_p5_natural')
    .choice(tr('vl7.c5_formal'), 'vl7_p5_formal')
    .choice(tr('vl7.c5_mistake'), 'vl7_p5_mistake')
    .choice(tr('vl7.c5_own'), 'vl7_p5_own')
    .choice(tr('vl7.c5_min'), 'vl7_p5_min')
    .endMenu()
    .scene('vl7_p5_natural', 'vl7_p5_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c5_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl7.p5_nat_mei'), 'happy')
    .jump('vl7_talk')
    .scene('vl7_p5_formal', 'vl7_p5_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c5_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl7.p5_form_ken'), 'laugh')
    .jump('vl7_talk')
    .scene('vl7_p5_mistake', 'vl7_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl7.p5_mis_tanaka'), 'neutral')
    .jump('vl7_p5_mistake2')
    .scene('vl7_p5_mistake2', 'vl7_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.p5_mis_relief'), 'happy')
    .jump('vl7_talk')
    .scene('vl7_p5_own', 'vl7_p5_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c5_own'), 'happy')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl7.p5_own_mei'), 'surprised')
    .jump('vl7_talk')
    .scene('vl7_p5_min', 'vl7_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl7.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl7.p5_min_yuki'), 'gentle')
    .jump('vl7_talk')
    .scene('vl7_talk', 'vl7_talk')
    .hide('grandma')
    .hide('grandpa')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl7.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'happy')
    .ken(tr('vl7.talk_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl7.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl7.talk_tanaka'), 'happy')
    .player(tr('vl7.talk_player'), 'neutral')
    .tanaka(tr('vl7.talk_close'), 'happy')
    .n(tr('vl7.complete'))
    .end()
    .build();
