import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson11 = VocabularyLessonDefinition(
  id: 'vocab_lesson_11',
  number: 11,
  level: VocabularyLessonLevel.intermediate,
  titleKey: 'vl11.title',
  subtitleKey: 'vl11.subtitle',
  descriptionKey: 'vl11.description',
  estimatedTime: '30–35 min',
  cefrFocus: 'A2',
  wordIds: <String>[
    'vocab_n4_30e1_30c3_30bb_30fc_30b8',
    'vocab_n4_30d3_30c7_30aa_901a_8a71',
    'vocab_n4_3084_3063_3068_4f1a_3048_305f',
    'vocab_n4_5bc2_3057_3044',
    'vocab_n4_5b89_5fc3',
    'vocab_n4_5b9f_306f',
    'vocab_n4_6614',
    'vocab_n4_601d_3044_51fa',
    'vocab_n4_601d_3044_51fa_3059',
    'vocab_n4_4f1d_3048_308b',
  ],
  storyFactory: getVocabularyLesson11,
);

StoryData getVocabularyLesson11() => dialogue()
    .story(11, tr('vl11.title'), tr('vl11.subtitle'))
    .description(tr('vl11.description'))
    .estimatedTime('30–35 min')
    .jlptFocus('N4')
    .scene('vl11_home', 'vl11_home')
    .hide('tanaka')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .apartment('evening')
    .titleCard(tr('vl11.title'), tr('vl11.subtitle'), 2500)
    .n(tr('vl11.setup'))
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl11.v_intro'), 'happy')
    .yuki(tr('vl11.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl11.w1_q'), 'neutral')
    .hide('ken')
    .yuki(tr('vl11.w1_a'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('vl11.w1_mei'), 'happy')
    .yuki(tr('vl11.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl11.c1_natural'), 'vl11_p1_natural')
    .choice(tr('vl11.c1_formal'), 'vl11_p1_formal')
    .choice(tr('vl11.c1_mistake'), 'vl11_p1_mistake')
    .choice(tr('vl11.c1_own'), 'vl11_p1_own')
    .choice(tr('vl11.c1_min'), 'vl11_p1_min')
    .endMenu()
    .scene('vl11_p1_natural', 'vl11_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c1_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl11.p1_nat_yuki'), 'happy')
    .jump('vl11_after_p1')
    .scene('vl11_p1_formal', 'vl11_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl11.p1_form_ken'), 'laugh')
    .jump('vl11_after_p1')
    .scene('vl11_p1_mistake', 'vl11_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c1_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl11.p1_mis_yuki'), 'neutral')
    .jump('vl11_p1_mistake2')
    .scene('vl11_p1_mistake2', 'vl11_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.p1_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl11.p1_mis_relief'), 'happy')
    .jump('vl11_after_p1')
    .scene('vl11_p1_own', 'vl11_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c1_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl11.p1_own_mei'), 'happy')
    .jump('vl11_after_p1')
    .scene('vl11_p1_min', 'vl11_p1_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c1_min'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl11.p1_min_ken'), 'neutral')
    .jump('vl11_after_p1')
    .scene('vl11_after_p1', 'vl11_after_p1')
    .hide('tanaka')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('yuki', 'far-right', 'speaking')
    .yuki(tr('vl11.w2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl11.w2_q'), 'neutral')
    .hide('ken')
    .yuki(tr('vl11.w2_a'), 'speaking')
    .yuki(tr('vl11.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl11.c2_natural'), 'vl11_p2_natural')
    .choice(tr('vl11.c2_formal'), 'vl11_p2_formal')
    .choice(tr('vl11.c2_mistake'), 'vl11_p2_mistake')
    .choice(tr('vl11.c2_own'), 'vl11_p2_own')
    .choice(tr('vl11.c2_min'), 'vl11_p2_min')
    .endMenu()
    .scene('vl11_p2_natural', 'vl11_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl11.p2_nat_yuki'), 'happy')
    .jump('vl11_call')
    .scene('vl11_p2_formal', 'vl11_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl11.p2_form_mei'), 'laugh')
    .jump('vl11_call')
    .scene('vl11_p2_mistake', 'vl11_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c2_mistake'), 'concerned')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl11.p2_mis_yuki'), 'neutral')
    .jump('vl11_p2_mistake2')
    .scene('vl11_p2_mistake2', 'vl11_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.p2_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl11.p2_mis_relief'), 'happy')
    .jump('vl11_call')
    .scene('vl11_p2_own', 'vl11_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl11.p2_own_ken'), 'happy')
    .jump('vl11_call')
    .scene('vl11_p2_min', 'vl11_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl11.p2_min_mei'), 'happy')
    .jump('vl11_call')
    .scene('vl11_call', 'vl11_call')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl11.connect'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.t_hello'), 'happy')
    .tanaka(tr('vl11.w3'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl11.w3_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl11.w3_a'), 'speaking')
    .show('ken', 'left', 'concerned')
    .ken(tr('vl11.k_sabishii'), 'concerned')
    .hide('ken')
    .tanaka(tr('vl11.w4'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl11.w4_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl11.w4_a'), 'speaking')
    .tanaka(tr('vl11.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl11.c3_natural'), 'vl11_p3_natural')
    .choice(tr('vl11.c3_formal'), 'vl11_p3_formal')
    .choice(tr('vl11.c3_mistake'), 'vl11_p3_mistake')
    .choice(tr('vl11.c3_own'), 'vl11_p3_own')
    .choice(tr('vl11.c3_min'), 'vl11_p3_min')
    .endMenu()
    .scene('vl11_p3_natural', 'vl11_p3_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c3_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p3_nat_tanaka'), 'happy')
    .jump('vl11_after_p3')
    .scene('vl11_p3_formal', 'vl11_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl11.p3_form_ken'), 'laugh')
    .jump('vl11_after_p3')
    .scene('vl11_p3_mistake', 'vl11_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl11.p3_mis_tanaka'), 'neutral')
    .jump('vl11_p3_mistake2')
    .scene('vl11_p3_mistake2', 'vl11_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p3_mis_relief'), 'happy')
    .jump('vl11_after_p3')
    .scene('vl11_p3_own', 'vl11_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p3_own_tanaka'), 'happy')
    .jump('vl11_after_p3')
    .scene('vl11_p3_min', 'vl11_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl11.p3_min_mei'), 'happy')
    .jump('vl11_after_p3')
    .scene('vl11_after_p3', 'vl11_after_p3')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl11.w5'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl11.w5_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl11.w5_a'), 'speaking')
    .tanaka(tr('vl11.t_ill'), 'neutral')
    .tanaka(tr('vl11.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl11.c4_natural'), 'vl11_p4_natural')
    .choice(tr('vl11.c4_formal'), 'vl11_p4_formal')
    .choice(tr('vl11.c4_mistake'), 'vl11_p4_mistake')
    .choice(tr('vl11.c4_own'), 'vl11_p4_own')
    .choice(tr('vl11.c4_min'), 'vl11_p4_min')
    .endMenu()
    .scene('vl11_p4_natural', 'vl11_p4_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c4_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p4_nat_tanaka'), 'happy')
    .jump('vl11_after_p4')
    .scene('vl11_p4_formal', 'vl11_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c4_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl11.p4_form_yuki'), 'laugh')
    .jump('vl11_after_p4')
    .scene('vl11_p4_mistake', 'vl11_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl11.p4_mis_tanaka'), 'neutral')
    .jump('vl11_p4_mistake2')
    .scene('vl11_p4_mistake2', 'vl11_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p4_mis_relief'), 'happy')
    .jump('vl11_after_p4')
    .scene('vl11_p4_own', 'vl11_p4_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c4_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p4_own_tanaka'), 'happy')
    .jump('vl11_after_p4')
    .scene('vl11_p4_min', 'vl11_p4_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c4_min'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl11.p4_min_ken'), 'neutral')
    .jump('vl11_after_p4')
    .scene('vl11_after_p4', 'vl11_after_p4')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl11.w6'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl11.w6_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl11.w6_a'), 'speaking')
    .tanaka(tr('vl11.t_news'), 'happy')
    .tanaka(tr('vl11.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl11.c5_natural'), 'vl11_p5_natural')
    .choice(tr('vl11.c5_formal'), 'vl11_p5_formal')
    .choice(tr('vl11.c5_mistake'), 'vl11_p5_mistake')
    .choice(tr('vl11.c5_own'), 'vl11_p5_own')
    .choice(tr('vl11.c5_min'), 'vl11_p5_min')
    .endMenu()
    .scene('vl11_p5_natural', 'vl11_p5_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c5_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p5_nat_tanaka'), 'happy')
    .jump('vl11_after_p5')
    .scene('vl11_p5_formal', 'vl11_p5_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c5_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl11.p5_form_mei'), 'laugh')
    .jump('vl11_after_p5')
    .scene('vl11_p5_mistake', 'vl11_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl11.p5_mis_tanaka'), 'neutral')
    .jump('vl11_p5_mistake2')
    .scene('vl11_p5_mistake2', 'vl11_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p5_mis_relief'), 'happy')
    .jump('vl11_after_p5')
    .scene('vl11_p5_own', 'vl11_p5_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c5_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p5_own_tanaka'), 'happy')
    .jump('vl11_after_p5')
    .scene('vl11_p5_min', 'vl11_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl11.p5_min_yuki'), 'gentle')
    .jump('vl11_after_p5')
    .scene('vl11_after_p5', 'vl11_after_p5')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl11.t_photo'), 'neutral')
    .tanaka(tr('vl11.w7'), 'speaking')
    .tanaka(tr('vl11.w8'), 'speaking')
    .tanaka(tr('vl11.w9'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl11.w9_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl11.w9_a'), 'speaking')
    .tanaka(tr('vl11.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl11.c6_natural'), 'vl11_p6_natural')
    .choice(tr('vl11.c6_formal'), 'vl11_p6_formal')
    .choice(tr('vl11.c6_mistake'), 'vl11_p6_mistake')
    .choice(tr('vl11.c6_own'), 'vl11_p6_own')
    .choice(tr('vl11.c6_min'), 'vl11_p6_min')
    .endMenu()
    .scene('vl11_p6_natural', 'vl11_p6_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c6_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p6_nat_tanaka'), 'happy')
    .jump('vl11_talk')
    .scene('vl11_p6_formal', 'vl11_p6_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c6_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl11.p6_form_ken'), 'laugh')
    .jump('vl11_talk')
    .scene('vl11_p6_mistake', 'vl11_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl11.p6_mis_tanaka'), 'neutral')
    .jump('vl11_p6_mistake2')
    .scene('vl11_p6_mistake2', 'vl11_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p6_mis_relief'), 'happy')
    .jump('vl11_talk')
    .scene('vl11_p6_own', 'vl11_p6_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c6_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.p6_own_tanaka'), 'happy')
    .jump('vl11_talk')
    .scene('vl11_p6_min', 'vl11_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl11.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl11.p6_min_yuki'), 'gentle')
    .jump('vl11_talk')
    .scene('vl11_talk', 'vl11_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl11.w10'), 'speaking')
    .tanaka(tr('vl11.t_grandma'), 'happy')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl11.w10_q'), 'neutral')
    .tanaka(tr('vl11.w10_a'), 'speaking')
    .tanaka(tr('vl11.talk_open'), 'happy')
    .hide('tanaka')
    .mei(tr('vl11.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl11.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl11.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl11.talk_tanaka'), 'happy')
    .player(tr('vl11.talk_player'), 'neutral')
    .tanaka(tr('vl11.talk_close'), 'happy')
    .n(tr('vl11.complete'))
    .end()
    .build();
