import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson09 = VocabularyLessonDefinition(
  id: 'vocab_lesson_09',
  number: 9,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl9.title',
  subtitleKey: 'vl9.subtitle',
  descriptionKey: 'vl9.description',
  estimatedTime: '25–30 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_307f_3093_306a',
    'vocab_n5_307e_305a',
    'vocab_n5_305b_3093_3079_3044',
    'vocab_n5_305d_3046_305d_3046',
    'vocab_n5_5a18',
    'vocab_n5_606f_5b50',
    'vocab_n5_7a74',
    'vocab_n5_7dba_9e97',
    'vocab_n5_75b2_308c_308b',
    'vocab_n5_5fc3',
  ],
  storyFactory: getVocabularyLesson09,
);

StoryData getVocabularyLesson09() => dialogue()
    .story(9, tr('vl9.title'), tr('vl9.subtitle'))
    .description(tr('vl9.description'))
    .estimatedTime('25–30 min')
    .jlptFocus('N5')
    .scene('vl9_home', 'vl9_home')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .apartment('evening')
    .titleCard(tr('vl9.title'), tr('vl9.subtitle'), 2500)
    .n(tr('vl9.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl9.t_intro'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.g_welcome'), 'neutral')
    .hide('grandma')
    .tanaka(tr('vl9.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl9.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl9.w1_a'), 'speaking')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.g_first'), 'neutral')
    .hide('grandma')
    .tanaka(tr('vl9.w2'), 'speaking')
    .tanaka(tr('vl9.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl9.c1_natural'), 'vl9_p1_natural')
    .choice(tr('vl9.c1_formal'), 'vl9_p1_formal')
    .choice(tr('vl9.c1_mistake'), 'vl9_p1_mistake')
    .choice(tr('vl9.c1_own'), 'vl9_p1_own')
    .choice(tr('vl9.c1_min'), 'vl9_p1_min')
    .endMenu()
    .scene('vl9_p1_natural', 'vl9_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c1_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p1_nat_grandma'), 'neutral')
    .jump('vl9_after_p1')
    .scene('vl9_p1_formal', 'vl9_p1_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c1_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl9.p1_form_ken'), 'laugh')
    .jump('vl9_after_p1')
    .scene('vl9_p1_mistake', 'vl9_p1_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c1_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl9.p1_mis_mei'), 'laugh')
    .jump('vl9_p1_mistake2')
    .scene('vl9_p1_mistake2', 'vl9_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.p1_mis_retry'), 'concerned')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p1_mis_relief'), 'neutral')
    .jump('vl9_after_p1')
    .scene('vl9_p1_own', 'vl9_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c1_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p1_own_grandma'), 'neutral')
    .jump('vl9_after_p1')
    .scene('vl9_p1_min', 'vl9_p1_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c1_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl9.p1_min_tanaka'), 'happy')
    .jump('vl9_after_p1')
    .scene('vl9_after_p1', 'vl9_after_p1')
    .hide('mei')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.g_senbei'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl9.w3'), 'speaking')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl9.w3_q'), 'happy')
    .hide('yuki')
    .tanaka(tr('vl9.w4'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl9.w4_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl9.w4_a'), 'speaking')
    .tanaka(tr('vl9.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl9.c2_natural'), 'vl9_p2_natural')
    .choice(tr('vl9.c2_formal'), 'vl9_p2_formal')
    .choice(tr('vl9.c2_mistake'), 'vl9_p2_mistake')
    .choice(tr('vl9.c2_own'), 'vl9_p2_own')
    .choice(tr('vl9.c2_min'), 'vl9_p2_min')
    .endMenu()
    .scene('vl9_p2_natural', 'vl9_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c2_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl9.p2_nat_yuki'), 'happy')
    .jump('vl9_kids')
    .scene('vl9_p2_formal', 'vl9_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl9.p2_form_yuki'), 'laugh')
    .jump('vl9_kids')
    .scene('vl9_p2_mistake', 'vl9_p2_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c2_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl9.p2_mis_ken'), 'surprised')
    .jump('vl9_p2_mistake2')
    .scene('vl9_p2_mistake2', 'vl9_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.p2_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl9.p2_mis_relief'), 'happy')
    .jump('vl9_kids')
    .scene('vl9_p2_own', 'vl9_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c2_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p2_own_grandma'), 'neutral')
    .jump('vl9_kids')
    .scene('vl9_p2_min', 'vl9_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c2_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl9.p2_min_mei'), 'happy')
    .jump('vl9_kids')
    .scene('vl9_kids', 'vl9_kids')
    .hide('ken')
    .hide('yuki')
    .hide('grandpa')
    .n(tr('vl9.kids'))
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.g_intro'), 'neutral')
    .hide('grandma')
    .show('little_girl', 'far-left', 'neutral')
    .say('little_girl', tr('vl9.k_yuri'), 'neutral')
    .hide('little_girl')
    .show('little_boy', 'left', 'neutral')
    .say('little_boy', tr('vl9.k_takumi'), 'neutral')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl9.w5'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl9.w5_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl9.w5_a'), 'speaking')
    .tanaka(tr('vl9.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl9.c3_natural'), 'vl9_p3_natural')
    .choice(tr('vl9.c3_formal'), 'vl9_p3_formal')
    .choice(tr('vl9.c3_mistake'), 'vl9_p3_mistake')
    .choice(tr('vl9.c3_own'), 'vl9_p3_own')
    .choice(tr('vl9.c3_min'), 'vl9_p3_min')
    .endMenu()
    .scene('vl9_p3_natural', 'vl9_p3_natural')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c3_natural'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl9.p3_nat_tanaka'), 'happy')
    .jump('vl9_sock')
    .scene('vl9_p3_formal', 'vl9_p3_formal')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c3_formal'), 'neutral')
    .show('tanaka', 'center', 'laugh')
    .tanaka(tr('vl9.p3_form_tanaka'), 'laugh')
    .jump('vl9_sock')
    .scene('vl9_p3_mistake', 'vl9_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c3_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl9.p3_mis_mei'), 'surprised')
    .jump('vl9_p3_mistake2')
    .scene('vl9_p3_mistake2', 'vl9_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl9.p3_mis_relief'), 'happy')
    .jump('vl9_sock')
    .scene('vl9_p3_own', 'vl9_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl9.p3_own_tanaka'), 'happy')
    .jump('vl9_sock')
    .scene('vl9_p3_min', 'vl9_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl9.p3_min_yuki'), 'gentle')
    .jump('vl9_sock')
    .scene('vl9_sock', 'vl9_sock')
    .hide('ken')
    .hide('mei')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl9.sock'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl9.w6'), 'speaking')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.g_mend'), 'neutral')
    .hide('grandma')
    .tanaka(tr('vl9.w7'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl9.w7_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl9.w7_a'), 'speaking')
    .n(tr('vl9.mended'))
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p4_prompt'), 'neutral')
    .tanaka(tr('vl9.p4_tanaka'), 'happy')
    .menu()
    .choice(tr('vl9.c4_natural'), 'vl9_p4_natural')
    .choice(tr('vl9.c4_formal'), 'vl9_p4_formal')
    .choice(tr('vl9.c4_mistake'), 'vl9_p4_mistake')
    .choice(tr('vl9.c4_own'), 'vl9_p4_own')
    .choice(tr('vl9.c4_min'), 'vl9_p4_min')
    .endMenu()
    .scene('vl9_p4_natural', 'vl9_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c4_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p4_nat_grandma'), 'neutral')
    .jump('vl9_moon')
    .scene('vl9_p4_formal', 'vl9_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c4_formal'), 'neutral')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p4_form_grandma'), 'neutral')
    .jump('vl9_moon')
    .scene('vl9_p4_mistake', 'vl9_p4_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c4_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl9.p4_mis_ken'), 'surprised')
    .jump('vl9_p4_mistake2')
    .scene('vl9_p4_mistake2', 'vl9_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.p4_mis_retry'), 'concerned')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p4_mis_relief'), 'neutral')
    .jump('vl9_moon')
    .scene('vl9_p4_own', 'vl9_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c4_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p4_own_grandma'), 'neutral')
    .jump('vl9_moon')
    .scene('vl9_p4_min', 'vl9_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl9.p4_min_mei'), 'happy')
    .jump('vl9_moon')
    .scene('vl9_moon', 'vl9_moon')
    .hide('ken')
    .hide('mei')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .park('evening')
    .n(tr('vl9.moon'))
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.g_tired'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl9.w8'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl9.w8_q'), 'neutral')
    .tanaka(tr('vl9.w8_a'), 'speaking')
    .tanaka(tr('vl9.w9'), 'speaking')
    .yuki(tr('vl9.w9_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl9.w9_a'), 'speaking')
    .tanaka(tr('vl9.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl9.c5_natural'), 'vl9_p5_natural')
    .choice(tr('vl9.c5_formal'), 'vl9_p5_formal')
    .choice(tr('vl9.c5_mistake'), 'vl9_p5_mistake')
    .choice(tr('vl9.c5_own'), 'vl9_p5_own')
    .choice(tr('vl9.c5_min'), 'vl9_p5_min')
    .endMenu()
    .scene('vl9_p5_natural', 'vl9_p5_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c5_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p5_nat_grandma'), 'neutral')
    .jump('vl9_talk')
    .scene('vl9_p5_formal', 'vl9_p5_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c5_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl9.p5_form_ken'), 'laugh')
    .jump('vl9_talk')
    .scene('vl9_p5_mistake', 'vl9_p5_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c5_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl9.p5_mis_mei'), 'surprised')
    .jump('vl9_p5_mistake2')
    .scene('vl9_p5_mistake2', 'vl9_p5_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.p5_mis_retry'), 'concerned')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p5_mis_relief'), 'neutral')
    .jump('vl9_talk')
    .scene('vl9_p5_own', 'vl9_p5_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c5_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl9.p5_own_grandma'), 'neutral')
    .jump('vl9_talk')
    .scene('vl9_p5_min', 'vl9_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl9.c5_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl9.p5_min_yuki'), 'gentle')
    .jump('vl9_talk')
    .scene('vl9_talk', 'vl9_talk')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl9.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl9.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'happy')
    .ken(tr('vl9.talk_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl9.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl9.talk_tanaka'), 'happy')
    .player(tr('vl9.talk_player'), 'neutral')
    .tanaka(tr('vl9.talk_close'), 'happy')
    .n(tr('vl9.complete'))
    .end()
    .build();
