import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson03 = VocabularyLessonDefinition(
  id: 'vocab_lesson_03',
  number: 3,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl3.title',
  subtitleKey: 'vl3.subtitle',
  descriptionKey: 'vl3.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_5bb6_65cf',
    'vocab_n5_79c1',
    'vocab_n5_7236',
    'vocab_n5_6bcd',
    'vocab_n5_304a_7236_3055_3093',
    'vocab_n5_304a_6bcd_3055_3093',
    'vocab_n5_304a_3058_3044_3061_3083_3093',
    'vocab_n5_304a_3070_3042_3061_3083_3093',
    'vocab_n5_305f_3060_3044_307e',
    'vocab_n5_304a_304b_3048_308a',
  ],
  storyFactory: getVocabularyLesson03,
);

StoryData getVocabularyLesson03() => dialogue()
    .story(3, tr('vl3.title'), tr('vl3.subtitle'))
    .description(tr('vl3.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('vl3_class', 'vl3_class')
    .hide('grandma')
    .classroom('afternoon')
    .titleCard(tr('vl3.title'), tr('vl3.subtitle'), 2500)
    .n(tr('vl3.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl3.t_intro'), 'happy')
    .tanaka(tr('vl3.w1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl3.w1_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl3.w1_a'), 'happy')
    .tanaka(tr('vl3.w2'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl3.w2_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl3.w2_a'), 'speaking')
    .tanaka(tr('vl3.w3'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl3.w3_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl3.w3_a'), 'speaking')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl3.w3_ken'), 'surprised')
    .tanaka(tr('vl3.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl3.c1_natural'), 'vl3_p1_natural')
    .choice(tr('vl3.c1_formal'), 'vl3_p1_formal')
    .choice(tr('vl3.c1_mistake'), 'vl3_p1_mistake')
    .choice(tr('vl3.c1_own'), 'vl3_p1_own')
    .choice(tr('vl3.c1_min'), 'vl3_p1_min')
    .endMenu()
    .scene('vl3_p1_natural', 'vl3_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c1_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl3.p1_nat_mei'), 'happy')
    .jump('vl3_after_p1')
    .scene('vl3_p1_formal', 'vl3_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl3.c1_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl3.p1_form_yuki'), 'laugh')
    .jump('vl3_after_p1')
    .scene('vl3_p1_mistake', 'vl3_p1_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c1_mistake'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl3.p1_mis_ken'), 'neutral')
    .jump('vl3_p1_mistake2')
    .scene('vl3_p1_mistake2', 'vl3_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.p1_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl3.p1_mis_relief'), 'happy')
    .jump('vl3_after_p1')
    .scene('vl3_p1_own', 'vl3_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl3.c1_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl3.p1_own_yuki'), 'happy')
    .jump('vl3_after_p1')
    .scene('vl3_p1_min', 'vl3_p1_min')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c1_min'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl3.p1_min_tanaka'), 'happy')
    .jump('vl3_after_p1')
    .scene('vl3_after_p1', 'vl3_after_p1')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl3.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl3.c2_natural'), 'vl3_p2_natural')
    .choice(tr('vl3.c2_formal'), 'vl3_p2_formal')
    .choice(tr('vl3.c2_mistake'), 'vl3_p2_mistake')
    .choice(tr('vl3.c2_own'), 'vl3_p2_own')
    .choice(tr('vl3.c2_min'), 'vl3_p2_min')
    .endMenu()
    .scene('vl3_p2_natural', 'vl3_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c2_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl3.p2_nat_mei'), 'happy')
    .jump('vl3_after_p2')
    .scene('vl3_p2_formal', 'vl3_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c2_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl3.p2_form_mei'), 'laugh')
    .jump('vl3_after_p2')
    .scene('vl3_p2_mistake', 'vl3_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c2_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl3.p2_mis_mei'), 'laugh')
    .jump('vl3_p2_mistake2')
    .scene('vl3_p2_mistake2', 'vl3_p2_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.p2_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl3.p2_mis_relief'), 'happy')
    .jump('vl3_after_p2')
    .scene('vl3_p2_own', 'vl3_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c2_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl3.p2_own_mei'), 'happy')
    .jump('vl3_after_p2')
    .scene('vl3_p2_min', 'vl3_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl3.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl3.p2_min_yuki'), 'gentle')
    .jump('vl3_after_p2')
    .scene('vl3_after_p2', 'vl3_after_p2')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl3.w5'), 'speaking')
    .hide('tanaka')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl3.w5_yuki'), 'happy')
    .hide('yuki')
    .show('ken', 'left', 'happy')
    .ken(tr('vl3.w5_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl3.w5_mei'), 'surprised')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl3.w5_tanaka'), 'happy')
    .jump('vl3_home')
    .scene('vl3_home', 'vl3_home')
    .apartment('evening')
    .n(tr('vl3.arrive'))
    .show('ken', 'left', 'happy')
    .ken(tr('vl3.h_tadaima'), 'happy')
    .hide('ken')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl3.h_okaeri'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl3.w9'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl3.w9_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl3.w9_a'), 'speaking')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl3.h_grand'), 'neutral')
    .hide('grandma')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl3.w9_yuki'), 'happy')
    .tanaka(tr('vl3.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl3.c3_natural'), 'vl3_p3_natural')
    .choice(tr('vl3.c3_formal'), 'vl3_p3_formal')
    .choice(tr('vl3.c3_mistake'), 'vl3_p3_mistake')
    .choice(tr('vl3.c3_own'), 'vl3_p3_own')
    .choice(tr('vl3.c3_min'), 'vl3_p3_min')
    .endMenu()
    .scene('vl3_p3_natural', 'vl3_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl3.c3_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl3.p3_nat_grand'), 'neutral')
    .jump('vl3_after_p3')
    .scene('vl3_p3_formal', 'vl3_p3_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c3_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl3.p3_form_ken'), 'laugh')
    .jump('vl3_after_p3')
    .scene('vl3_p3_mistake', 'vl3_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c3_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl3.p3_mis_mei'), 'surprised')
    .jump('vl3_p3_mistake2')
    .scene('vl3_p3_mistake2', 'vl3_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.p3_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl3.p3_mis_relief'), 'happy')
    .jump('vl3_after_p3')
    .scene('vl3_p3_own', 'vl3_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl3.c3_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl3.p3_own_grand'), 'neutral')
    .jump('vl3_after_p3')
    .scene('vl3_p3_min', 'vl3_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl3.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl3.p3_min_yuki'), 'gentle')
    .jump('vl3_after_p3')
    .scene('vl3_after_p3', 'vl3_after_p3')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl3.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl3.c4_natural'), 'vl3_p4_natural')
    .choice(tr('vl3.c4_formal'), 'vl3_p4_formal')
    .choice(tr('vl3.c4_mistake'), 'vl3_p4_mistake')
    .choice(tr('vl3.c4_own'), 'vl3_p4_own')
    .choice(tr('vl3.c4_min'), 'vl3_p4_min')
    .endMenu()
    .scene('vl3_p4_natural', 'vl3_p4_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c4_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl3.p4_nat_ken'), 'happy')
    .jump('vl3_talk')
    .scene('vl3_p4_formal', 'vl3_p4_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl3.c4_formal'), 'neutral')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl3.p4_form_grand'), 'neutral')
    .jump('vl3_talk')
    .scene('vl3_p4_mistake', 'vl3_p4_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl3.c4_mistake'), 'concerned')
    .show('yuki', 'far-right', 'surprised')
    .yuki(tr('vl3.p4_mis_yuki'), 'surprised')
    .jump('vl3_p4_mistake2')
    .scene('vl3_p4_mistake2', 'vl3_p4_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .player(tr('vl3.p4_mis_retry'), 'concerned')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl3.p4_mis_relief'), 'happy')
    .jump('vl3_talk')
    .scene('vl3_p4_own', 'vl3_p4_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c4_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl3.p4_own_ken'), 'happy')
    .jump('vl3_talk')
    .scene('vl3_p4_min', 'vl3_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl3.c4_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl3.p4_min_mei'), 'happy')
    .jump('vl3_talk')
    .scene('vl3_talk', 'vl3_talk')
    .hide('grandma')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl3.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl3.talk_mei'), 'happy')
    .hide('mei')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl3.talk_ken'), 'neutral')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl3.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl3.talk_tanaka'), 'happy')
    .player(tr('vl3.talk_player'), 'neutral')
    .tanaka(tr('vl3.talk_close'), 'happy')
    .n(tr('vl3.complete'))
    .end()
    .build();
