import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson01 = VocabularyLessonDefinition(
  id: 'vocab_lesson_01',
  number: 1,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl1.title',
  subtitleKey: 'vl1.subtitle',
  descriptionKey: 'vl1.description',
  estimatedTime: '12–18 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_304a_306f_3088_3046_3054_3056_3044_307e_3059',
    'vocab_n5_3053_3093_306b_3061_306f',
    'vocab_n5_3042_308a_304c_3068_3046',
    'vocab_n5_3059_307f_307e_305b_3093',
    'vocab_n5_3088_308d_3057_304f_304a_9858_3044_3057_307e_3059',
  ],
  storyFactory: getVocabularyLesson01,
);

StoryData getVocabularyLesson01() => dialogue()
    .story(1, tr('vl1.title'), tr('vl1.subtitle'))
    .description(tr('vl1.description'))
    .estimatedTime('12–18 min')
    .jlptFocus('N5')
    .scene('vl1_classroom', 'vl1_classroom')
    .classroom('morning')
    .titleCard(tr('vl1.title'), tr('vl1.subtitle'), 2500)
    .n(tr('vl1.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl1.t_intro'), 'happy')
    .tanaka(tr('vl1.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl1.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl1.w1_a'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('vl1.w1_mei'), 'happy')
    .tanaka(tr('vl1.w2'), 'speaking')
    .mei(tr('vl1.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl1.w2_a'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('vl1.w2_ken'), 'happy')
    .hide('ken')
    .tanaka(tr('vl1.w3'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl1.w3_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl1.w3_a'), 'happy')
    .tanaka(tr('vl1.w3_gozaimasu'), 'speaking')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl1.w3_mei'), 'surprised')
    .tanaka(tr('vl1.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl1.c1_natural'), 'vl1_p1_natural')
    .choice(tr('vl1.c1_formal'), 'vl1_p1_formal')
    .choice(tr('vl1.c1_mistake'), 'vl1_p1_mistake')
    .choice(tr('vl1.c1_own'), 'vl1_p1_own')
    .choice(tr('vl1.c1_min'), 'vl1_p1_min')
    .endMenu()
    .scene('vl1_p1_natural', 'vl1_p1_natural')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl1.c1_natural'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl1.p1_nat_ken'), 'happy')
    .jump('vl1_after_p1')
    .scene('vl1_p1_formal', 'vl1_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl1.c1_formal'), 'neutral')
    .show('yuki', 'far-right', 'playful')
    .yuki(tr('vl1.p1_form_yuki'), 'playful')
    .jump('vl1_after_p1')
    .scene('vl1_p1_mistake', 'vl1_p1_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl1.c1_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl1.p1_mis_ken'), 'surprised')
    .jump('vl1_p1_mistake2')
    .scene('vl1_p1_mistake2', 'vl1_p1_mistake2')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl1.p1_mis_retry'), 'concerned')
    .show('ken', 'left', 'happy')
    .ken(tr('vl1.p1_mis_relief'), 'happy')
    .jump('vl1_after_p1')
    .scene('vl1_p1_own', 'vl1_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl1.c1_own'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl1.p1_own_mei'), 'happy')
    .jump('vl1_after_p1')
    .scene('vl1_p1_min', 'vl1_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl1.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl1.p1_min_yuki'), 'gentle')
    .jump('vl1_after_p1')
    .scene('vl1_after_p1', 'vl1_after_p1')
    .hide('yuki')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl1.w4'), 'speaking')
    .tanaka(tr('vl1.w4b'), 'speaking')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl1.w4_q'), 'surprised')
    .hide('ken')
    .tanaka(tr('vl1.w4_a'), 'speaking')
    .show('mei', 'right', 'happy')
    .mei(tr('vl1.w4_mei'), 'happy')
    .tanaka(tr('vl1.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl1.c2_correct'), 'vl1_p2_correct')
    .choice(tr('vl1.c2_own'), 'vl1_p2_own')
    .choice(tr('vl1.c2_mixed'), 'vl1_p2_mixed')
    .choice(tr('vl1.c2_min'), 'vl1_p2_min')
    .endMenu()
    .scene('vl1_p2_correct', 'vl1_p2_correct')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl1.c2_correct'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl1.p2_cor_ken'), 'happy')
    .jump('vl1_after_p2')
    .scene('vl1_p2_own', 'vl1_p2_own')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl1.c2_own'), 'happy')
    .show('ken', 'left', 'happy')
    .ken(tr('vl1.p2_own_ken'), 'happy')
    .jump('vl1_after_p2')
    .scene('vl1_p2_mixed', 'vl1_p2_mixed')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl1.c2_mixed'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl1.p2_mix_mei'), 'surprised')
    .jump('vl1_p2_mixed2')
    .scene('vl1_p2_mixed2', 'vl1_p2_mixed2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl1.p2_mix_retry'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl1.p2_mix_relief'), 'laugh')
    .jump('vl1_after_p2')
    .scene('vl1_p2_min', 'vl1_p2_min')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl1.c2_min'), 'concerned')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl1.p2_min_ken'), 'neutral')
    .jump('vl1_after_p2')
    .scene('vl1_after_p2', 'vl1_after_p2')
    .hide('mei')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl1.w5'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl1.w5_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl1.w5_a'), 'speaking')
    .show('ken', 'left', 'happy')
    .ken(tr('vl1.w5_ken'), 'happy')
    .hide('ken')
    .tanaka(tr('vl1.w5_ken_a'), 'happy')
    .tanaka(tr('vl1.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl1.c3_natural'), 'vl1_p3_natural')
    .choice(tr('vl1.c3_formal'), 'vl1_p3_formal')
    .choice(tr('vl1.c3_mistake'), 'vl1_p3_mistake')
    .choice(tr('vl1.c3_own'), 'vl1_p3_own')
    .choice(tr('vl1.c3_min'), 'vl1_p3_min')
    .endMenu()
    .scene('vl1_p3_natural', 'vl1_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl1.c3_natural'), 'happy')
    .show('mei', 'right', 'happy')
    .mei(tr('vl1.p3_nat_mei'), 'happy')
    .jump('vl1_talk')
    .scene('vl1_p3_formal', 'vl1_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .player(tr('vl1.c3_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl1.p3_form_yuki'), 'laugh')
    .jump('vl1_talk')
    .scene('vl1_p3_mistake', 'vl1_p3_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl1.c3_mistake'), 'concerned')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl1.p3_mis_mei'), 'surprised')
    .jump('vl1_p3_mistake2')
    .scene('vl1_p3_mistake2', 'vl1_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl1.p3_mis_retry'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl1.p3_mis_relief'), 'happy')
    .jump('vl1_talk')
    .scene('vl1_p3_own', 'vl1_p3_own')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .player(tr('vl1.c3_own'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl1.p3_own_tanaka'), 'happy')
    .jump('vl1_talk')
    .scene('vl1_p3_min', 'vl1_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .player(tr('vl1.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl1.p3_min_mei'), 'happy')
    .jump('vl1_talk')
    .scene('vl1_talk', 'vl1_talk')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl1.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl1.talk_mei'), 'neutral')
    .hide('mei')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl1.talk_yuki'), 'neutral')
    .hide('yuki')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl1.talk_ken'), 'neutral')
    .hide('ken')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl1.talk_tanaka'), 'happy')
    .player(tr('vl1.talk_player'), 'neutral')
    .tanaka(tr('vl1.talk_close'), 'happy')
    .n(tr('vl1.complete'))
    .end()
    .build();
