import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson05 = VocabularyLessonDefinition(
  id: 'vocab_lesson_05',
  number: 5,
  level: VocabularyLessonLevel.beginner,
  titleKey: 'vl5.title',
  subtitleKey: 'vl5.subtitle',
  descriptionKey: 'vl5.description',
  estimatedTime: '20–25 min',
  cefrFocus: 'A1',
  wordIds: <String>[
    'vocab_n5_5ead',
    'vocab_n5_82b1',
    'vocab_n5_54b2_304f',
    'vocab_n5_304d_308c_3044',
    'vocab_n5_690d_3048_308b',
    'vocab_n5_6c34',
    'vocab_n5_624b_4f1d_3046',
    'vocab_n5_91ce_83dc',
    'vocab_n5_6599_7406',
    'vocab_n5_4f5c_308b',
  ],
  storyFactory: getVocabularyLesson05,
);

StoryData getVocabularyLesson05() => dialogue()
    .story(5, tr('vl5.title'), tr('vl5.subtitle'))
    .description(tr('vl5.description'))
    .estimatedTime('20–25 min')
    .jlptFocus('N5')
    .scene('vl5_garden', 'vl5_garden')
    .hide('grandma')
    .park('afternoon')
    .titleCard(tr('vl5.title'), tr('vl5.subtitle'), 2500)
    .n(tr('vl5.setup'))
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.g_welcome'), 'neutral')
    .hide('grandpa')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl5.t_intro'), 'happy')
    .tanaka(tr('vl5.w1'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl5.w1_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl5.w1_a'), 'speaking')
    .tanaka(tr('vl5.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl5.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl5.w2_a'), 'speaking')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.g_hana'), 'neutral')
    .hide('grandpa')
    .tanaka(tr('vl5.w3'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl5.w3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl5.w3_a'), 'speaking')
    .tanaka(tr('vl5.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl5.c1_natural'), 'vl5_p1_natural')
    .choice(tr('vl5.c1_formal'), 'vl5_p1_formal')
    .choice(tr('vl5.c1_mistake'), 'vl5_p1_mistake')
    .choice(tr('vl5.c1_own'), 'vl5_p1_own')
    .choice(tr('vl5.c1_min'), 'vl5_p1_min')
    .endMenu()
    .scene('vl5_p1_natural', 'vl5_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl5.c1_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.p1_nat_grandpa'), 'neutral')
    .jump('vl5_after_p1')
    .scene('vl5_p1_formal', 'vl5_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl5.c1_formal'), 'neutral')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.p1_form_grandpa'), 'neutral')
    .jump('vl5_after_p1')
    .scene('vl5_p1_mistake', 'vl5_p1_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl5.c1_mistake'), 'concerned')
    .show('ken', 'left', 'surprised')
    .ken(tr('vl5.p1_mis_ken'), 'surprised')
    .jump('vl5_p1_mistake2')
    .scene('vl5_p1_mistake2', 'vl5_p1_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl5.p1_mis_retry'), 'concerned')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.p1_mis_relief'), 'neutral')
    .jump('vl5_after_p1')
    .scene('vl5_p1_own', 'vl5_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl5.c1_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.p1_own_grandpa'), 'neutral')
    .jump('vl5_after_p1')
    .scene('vl5_p1_min', 'vl5_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl5.c1_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl5.p1_min_mei'), 'happy')
    .jump('vl5_after_p1')
    .scene('vl5_after_p1', 'vl5_after_p1')
    .hide('ken')
    .hide('grandma')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.g_plant'), 'neutral')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl5.w4'), 'speaking')
    .say('grandpa', tr('vl5.g_water'), 'neutral')
    .hide('grandpa')
    .tanaka(tr('vl5.w5'), 'speaking')
    .show('mei', 'right', 'surprised')
    .mei(tr('vl5.w5_q'), 'surprised')
    .hide('mei')
    .tanaka(tr('vl5.w5_a'), 'happy')
    .n(tr('vl5.planted'))
    .tanaka(tr('vl5.w6'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl5.w6_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl5.w6_a'), 'speaking')
    .tanaka(tr('vl5.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl5.c2_natural'), 'vl5_p2_natural')
    .choice(tr('vl5.c2_formal'), 'vl5_p2_formal')
    .choice(tr('vl5.c2_mistake'), 'vl5_p2_mistake')
    .choice(tr('vl5.c2_own'), 'vl5_p2_own')
    .choice(tr('vl5.c2_min'), 'vl5_p2_min')
    .endMenu()
    .scene('vl5_p2_natural', 'vl5_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl5.c2_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.p2_nat_grandpa'), 'neutral')
    .jump('vl5_after_p2')
    .scene('vl5_p2_formal', 'vl5_p2_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl5.c2_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl5.p2_form_ken'), 'laugh')
    .jump('vl5_after_p2')
    .scene('vl5_p2_mistake', 'vl5_p2_mistake')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl5.c2_mistake'), 'concerned')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl5.p2_mis_mei'), 'laugh')
    .jump('vl5_p2_mistake2')
    .scene('vl5_p2_mistake2', 'vl5_p2_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl5.p2_mis_retry'), 'concerned')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.p2_mis_relief'), 'neutral')
    .jump('vl5_after_p2')
    .scene('vl5_p2_own', 'vl5_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .player(tr('vl5.c2_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.p2_own_grandpa'), 'neutral')
    .jump('vl5_after_p2')
    .scene('vl5_p2_min', 'vl5_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl5.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl5.p2_min_yuki'), 'gentle')
    .jump('vl5_after_p2')
    .scene('vl5_after_p2', 'vl5_after_p2')
    .hide('ken')
    .hide('mei')
    .hide('grandpa')
    .apartment('evening')
    .n(tr('vl5.kitchen'))
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl5.gm_welcome'), 'neutral')
    .hide('grandma')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl5.w7'), 'speaking')
    .tanaka(tr('vl5.w8'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl5.w8_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl5.w9'), 'speaking')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl5.gm_ask'), 'neutral')
    .tanaka(tr('vl5.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl5.c3_natural'), 'vl5_p3_natural')
    .choice(tr('vl5.c3_formal'), 'vl5_p3_formal')
    .choice(tr('vl5.c3_mistake'), 'vl5_p3_mistake')
    .choice(tr('vl5.c3_own'), 'vl5_p3_own')
    .choice(tr('vl5.c3_min'), 'vl5_p3_min')
    .endMenu()
    .scene('vl5_p3_natural', 'vl5_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl5.c3_natural'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl5.p3_nat_grandma'), 'neutral')
    .jump('vl5_talk')
    .scene('vl5_p3_formal', 'vl5_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl5.c3_formal'), 'neutral')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl5.p3_form_grandma'), 'neutral')
    .jump('vl5_talk')
    .scene('vl5_p3_mistake', 'vl5_p3_mistake')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl5.c3_mistake'), 'concerned')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl5.p3_mis_ken'), 'laugh')
    .jump('vl5_p3_mistake2')
    .scene('vl5_p3_mistake2', 'vl5_p3_mistake2')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl5.p3_mis_retry'), 'concerned')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl5.p3_mis_relief'), 'neutral')
    .jump('vl5_talk')
    .scene('vl5_p3_own', 'vl5_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandpa')
    .player(tr('vl5.c3_own'), 'happy')
    .show('grandma', 'far-left', 'neutral')
    .say('grandma', tr('vl5.p3_own_grandma'), 'neutral')
    .jump('vl5_talk')
    .scene('vl5_p3_min', 'vl5_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .player(tr('vl5.c3_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl5.p3_min_mei'), 'happy')
    .jump('vl5_talk')
    .scene('vl5_talk', 'vl5_talk')
    .hide('grandma')
    .n(tr('vl5.dinner'))
    .show('ken', 'left', 'happy')
    .ken(tr('vl5.talk_itadaki'), 'happy')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl5.talk_open'), 'happy')
    .hide('tanaka')
    .show('mei', 'right', 'happy')
    .mei(tr('vl5.talk_mei'), 'happy')
    .hide('mei')
    .ken(tr('vl5.talk_ken'), 'happy')
    .hide('ken')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl5.talk_yuki'), 'happy')
    .hide('yuki')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl5.talk_grandpa'), 'neutral')
    .player(tr('vl5.talk_player'), 'neutral')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl5.talk_close'), 'happy')
    .n(tr('vl5.complete'))
    .end()
    .build();
