import '../dialogue_builder.dart';
import 'vocabulary_lesson.dart';

const vocabularyLesson18 = VocabularyLessonDefinition(
  id: 'vocab_lesson_18',
  number: 18,
  level: VocabularyLessonLevel.advanced,
  titleKey: 'vl18.title',
  subtitleKey: 'vl18.subtitle',
  descriptionKey: 'vl18.description',
  estimatedTime: '35–40 min',
  cefrFocus: 'B1',
  wordIds: <String>[
    'vocab_n3_753a_5185_4f1a',
    'vocab_n3_5b9a_671f_691c_8a3a',
    'vocab_n3_8840_5727',
    'vocab_n3_75c7_72b6',
    'vocab_n3_51e6_65b9_7b8b',
    'vocab_n3_9060_616e',
    'vocab_n3_6559_3048_3066_3044_305f_3060_3051_307e_3059_304b',
    'vocab_n3_5c45_5fc3_5730_304c_3044_3044',
    'vocab_n3_5ac1',
    'vocab_n3_3053_3053_306b_6765_3066',
  ],
  storyFactory: getVocabularyLesson18,
);

StoryData getVocabularyLesson18() => dialogue()
    .story(18, tr('vl18.title'), tr('vl18.subtitle'))
    .description(tr('vl18.description'))
    .estimatedTime('35–40 min')
    .jlptFocus('N3')
    .scene('vl18_home', 'vl18_home')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .bg('university_building', 'morning')
    .titleCard(tr('vl18.title'), tr('vl18.subtitle'), 2500)
    .n(tr('vl18.setup'))
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.t_intro'), 'happy')
    .tanaka(tr('vl18.w1'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl18.w1_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl18.w1_a'), 'speaking')
    .tanaka(tr('vl18.p1_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c1_natural'), 'vl18_p1_natural')
    .choice(tr('vl18.c1_formal'), 'vl18_p1_formal')
    .choice(tr('vl18.c1_mistake'), 'vl18_p1_mistake')
    .choice(tr('vl18.c1_own'), 'vl18_p1_own')
    .choice(tr('vl18.c1_min'), 'vl18_p1_min')
    .endMenu()
    .scene('vl18_p1_natural', 'vl18_p1_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c1_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p1_natural_r'), 'neutral')
    .jump('vl18_after_p1')
    .scene('vl18_p1_formal', 'vl18_p1_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c1_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl18.p1_formal_r'), 'laugh')
    .jump('vl18_after_p1')
    .scene('vl18_p1_mistake', 'vl18_p1_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c1_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p1_mistake_r'), 'neutral')
    .jump('vl18_p1_mistake2')
    .scene('vl18_p1_mistake2', 'vl18_p1_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p1_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p1_mis_relief'), 'happy')
    .jump('vl18_after_p1')
    .scene('vl18_p1_own', 'vl18_p1_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c1_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p1_own_r'), 'neutral')
    .jump('vl18_after_p1')
    .scene('vl18_p1_min', 'vl18_p1_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c1_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl18.p1_min_r'), 'gentle')
    .jump('vl18_after_p1')
    .scene('vl18_after_p1', 'vl18_after_p1')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w2'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl18.w2_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl18.w2_a'), 'speaking')
    .tanaka(tr('vl18.p2_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c2_natural'), 'vl18_p2_natural')
    .choice(tr('vl18.c2_formal'), 'vl18_p2_formal')
    .choice(tr('vl18.c2_mistake'), 'vl18_p2_mistake')
    .choice(tr('vl18.c2_own'), 'vl18_p2_own')
    .choice(tr('vl18.c2_min'), 'vl18_p2_min')
    .endMenu()
    .scene('vl18_p2_natural', 'vl18_p2_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c2_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p2_natural_r'), 'neutral')
    .jump('vl18_after_p2')
    .scene('vl18_p2_formal', 'vl18_p2_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c2_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl18.p2_formal_r'), 'laugh')
    .jump('vl18_after_p2')
    .scene('vl18_p2_mistake', 'vl18_p2_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c2_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p2_mistake_r'), 'neutral')
    .jump('vl18_p2_mistake2')
    .scene('vl18_p2_mistake2', 'vl18_p2_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p2_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p2_mis_relief'), 'happy')
    .jump('vl18_after_p2')
    .scene('vl18_p2_own', 'vl18_p2_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c2_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p2_own_r'), 'neutral')
    .jump('vl18_after_p2')
    .scene('vl18_p2_min', 'vl18_p2_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c2_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl18.p2_min_r'), 'gentle')
    .jump('vl18_after_p2')
    .scene('vl18_after_p2', 'vl18_after_p2')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl18.exam'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w3'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl18.w3_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl18.w3_a'), 'speaking')
    .tanaka(tr('vl18.p3_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c3_natural'), 'vl18_p3_natural')
    .choice(tr('vl18.c3_formal'), 'vl18_p3_formal')
    .choice(tr('vl18.c3_mistake'), 'vl18_p3_mistake')
    .choice(tr('vl18.c3_own'), 'vl18_p3_own')
    .choice(tr('vl18.c3_min'), 'vl18_p3_min')
    .endMenu()
    .scene('vl18_p3_natural', 'vl18_p3_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c3_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p3_natural_r'), 'neutral')
    .jump('vl18_after_p3')
    .scene('vl18_p3_formal', 'vl18_p3_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c3_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl18.p3_formal_r'), 'laugh')
    .jump('vl18_after_p3')
    .scene('vl18_p3_mistake', 'vl18_p3_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c3_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p3_mistake_r'), 'neutral')
    .jump('vl18_p3_mistake2')
    .scene('vl18_p3_mistake2', 'vl18_p3_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p3_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p3_mis_relief'), 'happy')
    .jump('vl18_after_p3')
    .scene('vl18_p3_own', 'vl18_p3_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c3_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p3_own_r'), 'neutral')
    .jump('vl18_after_p3')
    .scene('vl18_p3_min', 'vl18_p3_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c3_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl18.p3_min_r'), 'gentle')
    .jump('vl18_after_p3')
    .scene('vl18_after_p3', 'vl18_after_p3')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w4'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl18.w4_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl18.w4_a'), 'speaking')
    .tanaka(tr('vl18.p4_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c4_natural'), 'vl18_p4_natural')
    .choice(tr('vl18.c4_formal'), 'vl18_p4_formal')
    .choice(tr('vl18.c4_mistake'), 'vl18_p4_mistake')
    .choice(tr('vl18.c4_own'), 'vl18_p4_own')
    .choice(tr('vl18.c4_min'), 'vl18_p4_min')
    .endMenu()
    .scene('vl18_p4_natural', 'vl18_p4_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c4_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p4_natural_r'), 'neutral')
    .jump('vl18_after_p4')
    .scene('vl18_p4_formal', 'vl18_p4_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c4_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl18.p4_formal_r'), 'laugh')
    .jump('vl18_after_p4')
    .scene('vl18_p4_mistake', 'vl18_p4_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c4_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p4_mistake_r'), 'neutral')
    .jump('vl18_p4_mistake2')
    .scene('vl18_p4_mistake2', 'vl18_p4_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p4_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p4_mis_relief'), 'happy')
    .jump('vl18_after_p4')
    .scene('vl18_p4_own', 'vl18_p4_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c4_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p4_own_r'), 'neutral')
    .jump('vl18_after_p4')
    .scene('vl18_p4_min', 'vl18_p4_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c4_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl18.p4_min_r'), 'gentle')
    .jump('vl18_after_p4')
    .scene('vl18_after_p4', 'vl18_after_p4')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl18.prescription'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w5'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl18.w5_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl18.w5_a'), 'speaking')
    .tanaka(tr('vl18.p5_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c5_natural'), 'vl18_p5_natural')
    .choice(tr('vl18.c5_formal'), 'vl18_p5_formal')
    .choice(tr('vl18.c5_mistake'), 'vl18_p5_mistake')
    .choice(tr('vl18.c5_own'), 'vl18_p5_own')
    .choice(tr('vl18.c5_min'), 'vl18_p5_min')
    .endMenu()
    .scene('vl18_p5_natural', 'vl18_p5_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c5_natural'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl18.p5_natural_r'), 'happy')
    .jump('vl18_after_p5')
    .scene('vl18_p5_formal', 'vl18_p5_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c5_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl18.p5_formal_r'), 'laugh')
    .jump('vl18_after_p5')
    .scene('vl18_p5_mistake', 'vl18_p5_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c5_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p5_mistake_r'), 'neutral')
    .jump('vl18_p5_mistake2')
    .scene('vl18_p5_mistake2', 'vl18_p5_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p5_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p5_mis_relief'), 'happy')
    .jump('vl18_after_p5')
    .scene('vl18_p5_own', 'vl18_p5_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c5_own'), 'happy')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl18.p5_own_r'), 'happy')
    .jump('vl18_after_p5')
    .scene('vl18_p5_min', 'vl18_p5_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c5_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl18.p5_min_r'), 'happy')
    .jump('vl18_after_p5')
    .scene('vl18_after_p5', 'vl18_after_p5')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl18.back'))
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.gm_hesitate'), 'neutral')
    .hide('grandpa')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w6'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl18.w6_q'), 'neutral')
    .hide('ken')
    .tanaka(tr('vl18.w6_a'), 'speaking')
    .tanaka(tr('vl18.p6_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c6_natural'), 'vl18_p6_natural')
    .choice(tr('vl18.c6_formal'), 'vl18_p6_formal')
    .choice(tr('vl18.c6_mistake'), 'vl18_p6_mistake')
    .choice(tr('vl18.c6_own'), 'vl18_p6_own')
    .choice(tr('vl18.c6_min'), 'vl18_p6_min')
    .endMenu()
    .scene('vl18_p6_natural', 'vl18_p6_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c6_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p6_natural_r'), 'neutral')
    .jump('vl18_after_p6')
    .scene('vl18_p6_formal', 'vl18_p6_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c6_formal'), 'neutral')
    .show('mei', 'right', 'laugh')
    .mei(tr('vl18.p6_formal_r'), 'laugh')
    .jump('vl18_after_p6')
    .scene('vl18_p6_mistake', 'vl18_p6_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c6_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p6_mistake_r'), 'neutral')
    .jump('vl18_p6_mistake2')
    .scene('vl18_p6_mistake2', 'vl18_p6_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p6_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p6_mis_relief'), 'happy')
    .jump('vl18_after_p6')
    .scene('vl18_p6_own', 'vl18_p6_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c6_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p6_own_r'), 'neutral')
    .jump('vl18_after_p6')
    .scene('vl18_p6_min', 'vl18_p6_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c6_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl18.p6_min_r'), 'gentle')
    .jump('vl18_after_p6')
    .scene('vl18_after_p6', 'vl18_after_p6')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w7'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl18.w7_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl18.w7_a'), 'speaking')
    .tanaka(tr('vl18.p7_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c7_natural'), 'vl18_p7_natural')
    .choice(tr('vl18.c7_formal'), 'vl18_p7_formal')
    .choice(tr('vl18.c7_mistake'), 'vl18_p7_mistake')
    .choice(tr('vl18.c7_own'), 'vl18_p7_own')
    .choice(tr('vl18.c7_min'), 'vl18_p7_min')
    .endMenu()
    .scene('vl18_p7_natural', 'vl18_p7_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c7_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p7_natural_r'), 'neutral')
    .jump('vl18_after_p7')
    .scene('vl18_p7_formal', 'vl18_p7_formal')
    .hide('tanaka')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c7_formal'), 'neutral')
    .show('ken', 'left', 'laugh')
    .ken(tr('vl18.p7_formal_r'), 'laugh')
    .jump('vl18_after_p7')
    .scene('vl18_p7_mistake', 'vl18_p7_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c7_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p7_mistake_r'), 'neutral')
    .jump('vl18_p7_mistake2')
    .scene('vl18_p7_mistake2', 'vl18_p7_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p7_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p7_mis_relief'), 'happy')
    .jump('vl18_after_p7')
    .scene('vl18_p7_own', 'vl18_p7_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c7_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p7_own_r'), 'neutral')
    .jump('vl18_after_p7')
    .scene('vl18_p7_min', 'vl18_p7_min')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c7_min'), 'concerned')
    .show('yuki', 'far-right', 'gentle')
    .yuki(tr('vl18.p7_min_r'), 'gentle')
    .jump('vl18_after_p7')
    .scene('vl18_after_p7', 'vl18_after_p7')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .n(tr('vl18.wait'))
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w8'), 'speaking')
    .show('mei', 'right', 'neutral')
    .mei(tr('vl18.w8_q'), 'neutral')
    .hide('mei')
    .tanaka(tr('vl18.w8_a'), 'speaking')
    .tanaka(tr('vl18.p8_prompt'), 'happy')
    .menu()
    .choice(tr('vl18.c8_natural'), 'vl18_p8_natural')
    .choice(tr('vl18.c8_formal'), 'vl18_p8_formal')
    .choice(tr('vl18.c8_mistake'), 'vl18_p8_mistake')
    .choice(tr('vl18.c8_own'), 'vl18_p8_own')
    .choice(tr('vl18.c8_min'), 'vl18_p8_min')
    .endMenu()
    .scene('vl18_p8_natural', 'vl18_p8_natural')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c8_natural'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p8_natural_r'), 'neutral')
    .jump('vl18_after_p8')
    .scene('vl18_p8_formal', 'vl18_p8_formal')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c8_formal'), 'neutral')
    .show('yuki', 'far-right', 'laugh')
    .yuki(tr('vl18.p8_formal_r'), 'laugh')
    .jump('vl18_after_p8')
    .scene('vl18_p8_mistake', 'vl18_p8_mistake')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c8_mistake'), 'concerned')
    .show('tanaka', 'center', 'neutral')
    .tanaka(tr('vl18.p8_mistake_r'), 'neutral')
    .jump('vl18_p8_mistake2')
    .scene('vl18_p8_mistake2', 'vl18_p8_mistake2')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.p8_mis_retry'), 'concerned')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.p8_mis_relief'), 'happy')
    .jump('vl18_after_p8')
    .scene('vl18_p8_own', 'vl18_p8_own')
    .hide('tanaka')
    .hide('ken')
    .hide('mei')
    .hide('yuki')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c8_own'), 'happy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.p8_own_r'), 'neutral')
    .jump('vl18_after_p8')
    .scene('vl18_p8_min', 'vl18_p8_min')
    .hide('tanaka')
    .hide('ken')
    .hide('yuki')
    .hide('grandma')
    .hide('grandpa')
    .hide('little_girl')
    .hide('little_boy')
    .player(tr('vl18.c8_min'), 'concerned')
    .show('mei', 'right', 'happy')
    .mei(tr('vl18.p8_min_r'), 'happy')
    .jump('vl18_after_p8')
    .scene('vl18_after_p8', 'vl18_after_p8')
    .hide('grandma')
    .hide('little_girl')
    .hide('little_boy')
    .show('grandpa', 'far-left', 'neutral')
    .say('grandpa', tr('vl18.gm_yome'), 'neutral')
    .hide('grandpa')
    .show('tanaka', 'center', 'speaking')
    .tanaka(tr('vl18.w9'), 'speaking')
    .show('yuki', 'far-right', 'neutral')
    .yuki(tr('vl18.w9_q'), 'neutral')
    .hide('yuki')
    .tanaka(tr('vl18.w9_a'), 'speaking')
    .tanaka(tr('vl18.w10'), 'speaking')
    .show('ken', 'left', 'neutral')
    .ken(tr('vl18.w10_q'), 'neutral')
    .tanaka(tr('vl18.w10_a'), 'speaking')
    .tanaka(tr('vl18.talk_open'), 'happy')
    .hide('tanaka')
    .ken(tr('vl18.talk_ken'), 'happy')
    .hide('ken')
    .show('mei', 'right', 'happy')
    .mei(tr('vl18.talk_mei'), 'happy')
    .hide('mei')
    .show('yuki', 'far-right', 'happy')
    .yuki(tr('vl18.talk_yuki'), 'happy')
    .hide('yuki')
    .show('tanaka', 'center', 'happy')
    .tanaka(tr('vl18.talk_tanaka'), 'happy')
    .player(tr('vl18.talk_player'), 'happy')
    .tanaka(tr('vl18.talk_close'), 'happy')
    .n(tr('vl18.complete'))
    .end()
    .build();
